/**
 * manage_effect records — part 3 of 3 (renderers, data interfaces, events, GPU
 * sim, validation/info). Grounded in manage-effect-tool.ts enum and native
 * Effect/Niagara domains.
 */
import type { CapabilityRecordSource } from '../../../index.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { E } from './effect-properties.js';

const T = 'manage_effect';
const F = 'effect';
const NIAGARA = ['Niagara'];
const EMITTER_REQUIRED = ['action', 'systemPath', 'emitterName'];

export const EFFECT_3: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.add_sprite_renderer_module`, action: 'add_sprite_renderer_module', family: F,
    summary: 'Add a sprite renderer module.', whenToUse: ['Sprite rendering needed.'], whenNotToUse: ['Use add_mesh_renderer_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, materialPath: E.materialPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_sprite_renderer_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', materialPath: '/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial' }, exampleOutput: { success: true, message: 'Sprite renderer added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_mesh_renderer_module`, action: 'add_mesh_renderer_module', family: F,
    summary: 'Add a mesh renderer module.', whenToUse: ['Mesh rendering needed.'], whenNotToUse: ['Use add_sprite_renderer_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, meshPath: P.meshPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_mesh_renderer_module', systemPath: '/Game/NS_Debris', emitterName: 'Chunks', meshPath: '/Engine/BasicShapes/Cube.Cube' }, exampleOutput: { success: true, message: 'Mesh renderer added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_ribbon_renderer_module`, action: 'add_ribbon_renderer_module', family: F,
    summary: 'Add a ribbon renderer module.', whenToUse: ['Ribbon/trail rendering.'], whenNotToUse: ['Use add_mesh_renderer_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, materialPath: E.materialPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_ribbon_renderer_module', systemPath: '/Game/NS_Trail', emitterName: 'Trail' }, exampleOutput: { success: true, message: 'Ribbon renderer added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_light_renderer_module`, action: 'add_light_renderer_module', family: F,
    summary: 'Add a light renderer module.', whenToUse: ['Per-particle light needed.'], whenNotToUse: ['Use add_sprite_renderer_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, lightRadius: E.lightRadius, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_light_renderer_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', lightRadius: 200 }, exampleOutput: { success: true, message: 'Light renderer added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_collision_module`, action: 'add_collision_module', family: F,
    summary: 'Add a collision module.', whenToUse: ['Particles must collide.'], whenNotToUse: ['Use add_kill_particles_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, collisionMode: E.collisionMode, restitution: E.restitution, friction: E.friction, dieOnCollision: E.dieOnCollision, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_collision_module', systemPath: '/Game/NS_Debris', emitterName: 'Chunks', collisionMode: 'SceneDepth', dieOnCollision: true }, exampleOutput: { success: true, message: 'Collision module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_kill_particles_module`, action: 'add_kill_particles_module', family: F,
    summary: 'Add a kill-particles module.', whenToUse: ['Particles must die on condition.'], whenNotToUse: ['Use add_collision_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, killCondition: E.killCondition, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_kill_particles_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', killCondition: 'Age' }, exampleOutput: { success: true, message: 'Kill particles module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_camera_offset_module`, action: 'add_camera_offset_module', family: F,
    summary: 'Add a camera-offset module.', whenToUse: ['Camera-relative particles.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, cameraOffset: E.cameraOffset, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_camera_offset_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', cameraOffset: 4 }, exampleOutput: { success: true, message: 'Camera offset module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_skeletal_mesh_data_interface`, action: 'add_skeletal_mesh_data_interface', family: F,
    summary: 'Add a skeletal-mesh data interface.', whenToUse: ['Read skeletal mesh data.'], whenNotToUse: ['Use add_static_mesh_data_interface.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_skeletal_mesh_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'SkelDI' }, exampleOutput: { success: true, message: 'Skeletal mesh DI added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_static_mesh_data_interface`, action: 'add_static_mesh_data_interface', family: F,
    summary: 'Add a static-mesh data interface.', whenToUse: ['Read static mesh data.'], whenNotToUse: ['Use add_skeletal_mesh_data_interface.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_static_mesh_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'StaticDI' }, exampleOutput: { success: true, message: 'Static mesh DI added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spline_data_interface`, action: 'add_spline_data_interface', family: F,
    summary: 'Add a spline data interface.', whenToUse: ['Sample spline data.'], whenNotToUse: ['Use add_static_mesh_data_interface.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spline_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'SplineDI' }, exampleOutput: { success: true, message: 'Spline DI added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_audio_spectrum_data_interface`, action: 'add_audio_spectrum_data_interface', family: F,
    summary: 'Add an audio-spectrum data interface.', whenToUse: ['Audio-reactive particles.'], whenNotToUse: ['Use add_spline_data_interface.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_audio_spectrum_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'AudioDI' }, exampleOutput: { success: true, message: 'Audio spectrum DI added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_collision_query_data_interface`, action: 'add_collision_query_data_interface', family: F,
    summary: 'Add a collision-query data interface.', whenToUse: ['Query collisions in graph.'], whenNotToUse: ['Use add_collision_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_collision_query_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'CollisionDI' }, exampleOutput: { success: true, message: 'Collision query DI added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_event_generator`, action: 'add_event_generator', family: F,
    summary: 'Add a Niagara event generator.', whenToUse: ['Emitter emits events.'], whenNotToUse: ['Use add_event_receiver.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, eventName: E.eventName, eventType: E.eventType, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_event_generator', systemPath: '/Game/NS_Fire', emitterName: 'Spark', eventName: 'Burst', eventType: 'Location' }, exampleOutput: { success: true, message: 'Event generator added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_event_receiver`, action: 'add_event_receiver', family: F,
    summary: 'Add a Niagara event receiver.', whenToUse: ['Emitter consumes events.'], whenNotToUse: ['Use add_event_generator.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, eventName: E.eventName, spawnOnEvent: E.spawnOnEvent, eventSpawnCount: E.eventSpawnCount, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_event_receiver', systemPath: '/Game/NS_Fire', emitterName: 'Spark', eventName: 'Burst', spawnOnEvent: true, eventSpawnCount: 2 }, exampleOutput: { success: true, message: 'Event receiver added' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_event_payload`, action: 'configure_event_payload', family: F,
    summary: 'Configure an event payload.', whenToUse: ['Event carries data.'], whenNotToUse: ['Use add_event_generator.'],
    inputProps: { action: P.action, systemPath: E.systemPath, eventName: E.eventName, eventPayload: E.eventPayload, save: P.save }, required: ['action', 'systemPath', 'eventName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'configure_event_payload', systemPath: '/Game/NS_Fire', eventName: 'Burst', eventPayload: [{ name: 'PayloadFloat', type: 'Float' }] }, exampleOutput: { success: true, message: 'Event payload configured' } }),
  buildRecord({ parentTool: T, id: `${T}.enable_gpu_simulation`, action: 'enable_gpu_simulation', family: F,
    summary: 'Enable GPU simulation on a system.', whenToUse: ['GPU particles needed.'], whenNotToUse: ['Use add_simulation_stage.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, fixedBoundsEnabled: E.fixedBoundsEnabled, deterministicEnabled: E.deterministicEnabled, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'enable_gpu_simulation', systemPath: '/Game/NS_Fire', emitterName: 'Spark', fixedBoundsEnabled: true }, exampleOutput: { success: true, message: 'GPU simulation enabled' } }),
  buildRecord({ parentTool: T, id: `${T}.add_simulation_stage`, action: 'add_simulation_stage', family: F,
    summary: 'Add a simulation stage.', whenToUse: ['Custom sim stage needed.'], whenNotToUse: ['Use enable_gpu_simulation.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, stageName: E.stageName, stageIterationSource: E.stageIterationSource, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_simulation_stage', systemPath: '/Game/NS_Fire', emitterName: 'Spark', stageName: 'Stage_0', stageIterationSource: 'Particles' }, exampleOutput: { success: true, message: 'Simulation stage added' } }),
  buildRecord({ parentTool: T, id: `${T}.get_niagara_info`, action: 'get_niagara_info', family: F,
    summary: 'Read Niagara system metadata.', whenToUse: ['Inspect a Niagara system.'], whenNotToUse: ['Mutate the system.'],
    inputProps: { action: P.action, assetPath: P.assetPath }, required: ['action', 'assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: NIAGARA,
    outputProps: { emitterCount: P.num_ }, outputRequired: [],
    exampleInput: { action: 'get_niagara_info', assetPath: '/Game/NS_Fire' }, exampleOutput: { success: true, message: 'Niagara info', emitterCount: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.validate_niagara_system`, action: 'validate_niagara_system', family: F,
    summary: 'Validate a Niagara system for errors.', whenToUse: ['Catch authoring errors.'], whenNotToUse: ['Use get_niagara_info.'],
    inputProps: { action: P.action, systemPath: E.systemPath, assetPath: P.assetPath, system: E.system }, required: ['action'], requiredOneOf: ['systemPath', 'assetPath', 'system'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: NIAGARA,
    outputProps: { valid: P.bool_, errors: P.arrayOfStrings }, outputRequired: ['valid'],
    exampleInput: { action: 'validate_niagara_system', systemPath: '/Game/NS_Fire' }, exampleOutput: { success: true, message: 'Niagara validated', valid: true, errors: [] } }),
];
