/**
 * manage_effect records — part 2 of 3 (Niagara parameters, emitter props,
 * spawn/init/particle modules). Grounded in manage-effect-tool.ts enum and the
 * native Effect/Niagara domains.
 */
import type { CapabilityRecordSource } from '../../../index.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { E } from './effect-properties.js';

const T = 'manage_effect';
const F = 'effect';
const NIAGARA = ['Niagara'];

export const EFFECT_2: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.set_niagara_parameter`, action: 'set_niagara_parameter', family: F,
    summary: 'Set a Niagara system parameter.', whenToUse: ['A parameter value must change.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { action: P.action, actorName: P.actorName, assetPath: P.assetPath, parameterName: E.parameterName, parameterType: E.parameterType, value: P.value }, required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_niagara_parameter', actorName: 'FX_1', parameterName: 'SpawnRate', parameterType: 'Float', value: 1.25 }, exampleOutput: { success: true, message: 'Niagara parameter set' } }),
  buildRecord({ parentTool: T, id: `${T}.clear_debug_shapes`, action: 'clear_debug_shapes', family: F,
    summary: 'Clear all editor debug shapes.', whenToUse: ['Debug shapes must be removed.'], whenNotToUse: ['Use debug_shape.'],
    inputProps: { action: P.action }, required: ['action'], effect: 'write', editorStates: ['edit'], behavior: { safeToRetry: true }, latency: 'instant', resources: 'low',
    exampleInput: { action: 'clear_debug_shapes' }, exampleOutput: { success: true, message: 'Debug shapes cleared' } }),
  buildRecord({ parentTool: T, id: `${T}.cleanup`, action: 'cleanup', family: F,
    summary: 'Clean up transient effect authoring state.', whenToUse: ['Reset authoring session.'], whenNotToUse: ['Persist work.'],
    inputProps: { action: P.action, filter: E.filter }, required: ['action'], effect: 'write', behavior: { safeToRetry: true, supportsUndo: false }, latency: 'instant', resources: 'low',
    exampleInput: { action: 'cleanup', filter: 'MCP_ManageEffectDefaultActor_' }, exampleOutput: { success: true, message: 'Cleanup done' } }),
  buildRecord({ parentTool: T, id: `${T}.list_debug_shapes`, action: 'list_debug_shapes', family: F,
    summary: 'List active editor debug shapes.', whenToUse: ['Enumerate debug shapes.'], whenNotToUse: ['Mutate shapes.'],
    inputProps: { action: P.action }, required: ['action'], effect: 'read', editorStates: ['edit'], latency: 'instant', resources: 'low',
    outputProps: { shapes: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'list_debug_shapes' }, exampleOutput: { success: true, message: 'Debug shapes listed', shapes: ['Sphere_0'] } }),
  buildRecord({ parentTool: T, id: `${T}.add_emitter_to_system`, action: 'add_emitter_to_system', family: F,
    summary: 'Add an emitter to a Niagara system.', whenToUse: ['System needs an emitter.'], whenNotToUse: ['Use create_niagara_emitter.'],
    inputProps: { action: P.action, assetPath: P.assetPath, systemPath: E.systemPath, emitterPath: P.assetPath, save: P.save }, required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    outputProps: { emitterName: E.emitterName }, outputRequired: [],
    exampleInput: { action: 'add_emitter_to_system', systemPath: '/Game/NS_Fire', emitterPath: '/Game/NE_Spark', save: false }, exampleOutput: { success: true, message: 'Emitter added', emitterName: 'NE_Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.set_emitter_properties`, action: 'set_emitter_properties', family: F,
    summary: 'Set emitter properties.', whenToUse: ['Emitter config must change.'], whenNotToUse: ['Use add_emitter_to_system.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, emitterProperties: E.emitterProperties, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_emitter_properties', systemPath: '/Game/NS_Fire', emitterName: 'Spark', emitterProperties: { enabled: true } }, exampleOutput: { success: true, message: 'Emitter properties set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_rate_module`, action: 'add_spawn_rate_module', family: F,
    summary: 'Add a spawn-rate module to an emitter.', whenToUse: ['Emitter spawns over time.'], whenNotToUse: ['Use add_spawn_burst_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, emitter: E.emitter, spawnRate: E.spawnRate, save: P.save }, required: ['action', 'systemPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_rate_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', spawnRate: 50 }, exampleOutput: { success: true, message: 'Spawn rate module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_burst_module`, action: 'add_spawn_burst_module', family: F,
    summary: 'Add a spawn-burst module to an emitter.', whenToUse: ['Burst spawn needed.'], whenNotToUse: ['Use add_spawn_rate_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, burstCount: E.burstCount, count: P.count, burstTime: E.burstTime, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_burst_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', burstCount: 20, burstTime: 0.25 }, exampleOutput: { success: true, message: 'Spawn burst module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_per_unit_module`, action: 'add_spawn_per_unit_module', family: F,
    summary: 'Add a spawn-per-unit module.', whenToUse: ['Spawn along a path/unit.'], whenNotToUse: ['Use add_spawn_rate_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, spawnPerUnit: E.spawnPerUnit, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_per_unit_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', spawnPerUnit: 2.5 }, exampleOutput: { success: true, message: 'Spawn per unit module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_initialize_particle_module`, action: 'add_initialize_particle_module', family: F,
    summary: 'Add an initialize-particle module.', whenToUse: ['Particle init needed.'], whenNotToUse: ['Use add_particle_state_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, lifetime: E.lifetime, mass: P.mass, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_initialize_particle_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', lifetime: 3, mass: 1.5 }, exampleOutput: { success: true, message: 'Init particle module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_particle_state_module`, action: 'add_particle_state_module', family: F,
    summary: 'Add a particle-state module.', whenToUse: ['Particle lifecycle state needed.'], whenNotToUse: ['Use add_initialize_particle_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_particle_state_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' }, exampleOutput: { success: true, message: 'Particle state module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_force_module`, action: 'add_force_module', family: F,
    summary: 'Add a force module.', whenToUse: ['Particles need force.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, forceType: E.forceType, forceStrength: E.forceStrength, save: P.save }, required: ['action', 'systemPath', 'emitterName', 'forceType'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_force_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', forceType: 'Gravity', forceStrength: 980 }, exampleOutput: { success: true, message: 'Force module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_velocity_module`, action: 'add_velocity_module', family: F,
    summary: 'Add a velocity module.', whenToUse: ['Particles need velocity.'], whenNotToUse: ['Use add_force_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, velocityMode: E.velocityMode, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_velocity_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', velocityMode: 'Linear' }, exampleOutput: { success: true, message: 'Velocity module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_acceleration_module`, action: 'add_acceleration_module', family: F,
    summary: 'Add an acceleration module.', whenToUse: ['Particles need acceleration.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, acceleration: E.acceleration, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_acceleration_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', acceleration: { x: 0, y: 0, z: -980 } }, exampleOutput: { success: true, message: 'Acceleration module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_size_module`, action: 'add_size_module', family: F,
    summary: 'Add a size module.', whenToUse: ['Particle size must change.'], whenNotToUse: ['Use add_color_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, sizeMode: E.sizeMode, uniformSize: E.uniformSize, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_size_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', sizeMode: 'Uniform', uniformSize: 12 }, exampleOutput: { success: true, message: 'Size module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_color_module`, action: 'add_color_module', family: F,
    summary: 'Add a color module.', whenToUse: ['Particle color must change.'], whenNotToUse: ['Use add_size_module.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, color: E.color, colorMode: E.colorMode, save: P.save }, required: ['action', 'systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_color_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', color: { r: 1, g: 0.5, b: 0.25, a: 1 }, colorMode: 'Direct' }, exampleOutput: { success: true, message: 'Color module added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_user_parameter`, action: 'add_user_parameter', family: F,
    summary: 'Add a user parameter to a system.', whenToUse: ['Expose a user param.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { action: P.action, systemPath: E.systemPath, parameterName: E.parameterName, parameterType: E.parameterType, save: P.save }, required: ['action', 'systemPath', 'parameterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_user_parameter', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', parameterType: 'Float' }, exampleOutput: { success: true, message: 'User parameter added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_parameter_value`, action: 'set_parameter_value', family: F,
    summary: 'Set a user parameter value.', whenToUse: ['Param value must change.'], whenNotToUse: ['Use add_user_parameter.'],
    inputProps: { action: P.action, systemPath: E.systemPath, parameterName: E.parameterName, parameterValue: E.parameterValue, save: P.save }, required: ['action', 'systemPath', 'parameterName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_parameter_value', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', parameterValue: 2 }, exampleOutput: { success: true, message: 'Parameter value set' } }),
  buildRecord({ parentTool: T, id: `${T}.bind_parameter_to_source`, action: 'bind_parameter_to_source', family: F,
    summary: 'Bind a parameter to a data source.', whenToUse: ['Param driven externally.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, parameterType: E.parameterType, sourceBinding: E.sourceBinding, save: P.save }, required: ['action', 'systemPath', 'parameterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'bind_parameter_to_source', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', sourceBinding: 'Emitter.Age' }, exampleOutput: { success: true, message: 'Parameter bound' } }),
  buildRecord({ parentTool: T, id: `${T}.set_niagara_dynamic_input`, action: 'set_niagara_dynamic_input', family: F,
    summary: 'Configure a Niagara dynamic input expression.', whenToUse: ['Expression-driven value needed.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { action: P.action, systemPath: E.systemPath, emitterName: E.emitterName, targetNodeId: E.targetNodeId, moduleName: { type: 'string', description: 'Module (function call) name that owns inputName; alternative to targetNodeId.' }, inputName: E.inputName, dynamicInputScriptPath: E.dynamicInputScriptPath, replaceExisting: E.replaceExisting, save: P.save }, required: ['action', 'systemPath', 'inputName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_niagara_dynamic_input', systemPath: '/Game/NS_Fire', inputName: 'EmitterState.ScaleSpawnCountCurve', dynamicInputScriptPath: '/Niagara/DynamicInputs/Add/Add_Float.Add_Float' }, exampleOutput: { success: true, message: 'Dynamic input set' } }),
];
