/**
 * manage_effect records — part 1 of 3 (particle/niagara core, debug, lifecycle).
 * Grounded in manage-effect-tool.ts enum, effect handlers
 * (src/tools/handlers/effect/), and native Effect domain
 * (Plugins/.../Private/Domains/Effect/). Niagara-gated via the Niagara plugin.
 */
import type { CapabilityRecordSource } from '../../../index.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { E } from './effect-properties.js';

const T = 'manage_effect';
const F = 'effect';
const W = ['A particle, Niagara or debug effect must be authored or run.'];
const NIAGARA = ['Niagara'];

export const EFFECT_1: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.particle`, action: 'particle', family: F,
    summary: 'Author a particle effect (Cascade/Niagara).', whenToUse: W, whenNotToUse: ['Use niagara.'],
    inputProps: { action: P.action, name: P.name, path: P.path, preset: E.preset, shapeType: E.shapeType, color: E.color, duration: P.duration, location: P.location, radius: P.radius }, required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'particle', preset: 'Default', shapeType: 'sphere', radius: 30 }, exampleOutput: { success: true, message: 'Particle effect created' } }),
  buildRecord({ parentTool: T, id: `${T}.niagara`, action: 'niagara', family: F,
    summary: 'Author a Niagara system.', whenToUse: W, whenNotToUse: ['Use particle.'],
    inputProps: { action: P.action, name: P.name, path: P.path, actorName: P.actorName, systemPath: E.systemPath, attachToActor: E.attachToActor, location: P.location }, required: ['action', 'systemPath'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    outputProps: { actorPath: P.string_, actorName: P.actorName, actorGuid: P.string_, existsAfter: P.bool_, actorClass: P.string_ }, outputRequired: [],
    exampleInput: { action: 'niagara', systemPath: '/Game/NS_Explosion', actorName: 'FX_1' }, exampleOutput: { success: true, message: 'Niagara system authored', actorName: 'FX_1' } }),
  buildRecord({ parentTool: T, id: `${T}.debug_shape`, action: 'debug_shape', family: F,
    summary: 'Spawn a debug shape in the editor viewport.', whenToUse: ['Visualize a region/volume.'], whenNotToUse: ['Use spawn_niagara.'],
    inputProps: { action: P.action, shape: P.string_, shapeType: E.shapeType, location: P.location, radius: P.radius, color: E.color, duration: P.duration }, required: ['action'],
    effect: 'write', editorStates: ['edit'], latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'debug_shape', shape: 'Sphere', location: [0, 0, 0], radius: 100 }, exampleOutput: { success: true, message: 'Debug shape spawned' } }),
  buildRecord({ parentTool: T, id: `${T}.spawn_niagara`, action: 'spawn_niagara', family: F,
    topics: ['spawn particle', 'play effect', 'spawn vfx', 'spawn niagara system', 'emit particles'],
    summary: 'Spawn a Niagara system instance at runtime (PIE).', whenToUse: ['A Niagara effect must play on a live actor.'], whenNotToUse: ['Author the system.'],
    inputProps: { action: P.action, actorName: P.actorName, assetPath: P.assetPath, system: E.system, systemPath: E.systemPath, location: P.location }, required: ['action'],
    effect: 'write', editorStates: ['edit', 'pie', 'simulate'], behavior: { supportsUndo: false }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'spawn_niagara', system: '/Game/NS_Explosion', location: [0, 0, 100] }, exampleOutput: { success: true, message: 'Niagara spawned' } }),
  buildRecord({ parentTool: T, id: `${T}.create_dynamic_light`, action: 'create_dynamic_light', family: F,
    summary: 'Create a dynamic light actor.', whenToUse: ['Runtime light needed.'], whenNotToUse: ['Use build_environment lights.'],
    inputProps: { action: P.action, name: P.name, location: P.location, lightType: E.lightType, intensity: E.intensity, color: E.color }, required: ['action', 'name'],
    effect: 'write', editorStates: ['edit', 'pie'], latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_dynamic_light', name: 'Light_1', lightType: 'Point', intensity: 750 }, exampleOutput: { success: true, message: 'Dynamic light created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_system`, action: 'create_niagara_system', family: F,
    topics: ['niagara', 'particle system', 'vfx', 'particle effect', 'new niagara system'],
    summary: 'Create a Niagara System asset.', whenToUse: W, whenNotToUse: ['Use niagara.'],
    inputProps: { action: P.action, name: P.name, path: P.path, savePath: E.savePath }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    outputProps: { systemPath: P.assetPath }, outputRequired: ['systemPath'],
    exampleInput: { action: 'create_niagara_system', name: 'NS_Fire' }, exampleOutput: { success: true, message: 'Niagara system created', systemPath: '/Game/NS_Fire' } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_emitter`, action: 'create_niagara_emitter', family: F,
    summary: 'Create a Niagara Emitter asset.', whenToUse: ['A reusable emitter is needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { action: P.action, name: P.name, path: P.path, savePath: E.savePath, emitterName: E.emitterName }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_niagara_emitter', name: 'NE_Spark' }, exampleOutput: { success: true, message: 'Niagara emitter created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_volumetric_fog`, action: 'create_volumetric_fog', family: F,
    summary: 'Create a volumetric fog effect.', whenToUse: ['Volumetric fog needed.'], whenNotToUse: ['Use build_environment fog.'],
    inputProps: { action: P.action, name: P.name, path: P.path, density: E.density, scattering: E.scattering, extinction: E.extinction }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_volumetric_fog', name: 'VF_Mist', density: 0.02 }, exampleOutput: { success: true, message: 'Volumetric fog created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_particle_trail`, action: 'create_particle_trail', family: F,
    summary: 'Create a particle trail effect.', whenToUse: ['A trailing effect is needed.'], whenNotToUse: ['Use create_particle_trail via ribbon.'],
    inputProps: { action: P.action, name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_particle_trail', name: 'PT_Trail' }, exampleOutput: { success: true, message: 'Particle trail created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_environment_effect`, action: 'create_environment_effect', family: F,
    summary: 'Create an environment effect (weather/atmosphere).', whenToUse: ['Ambient FX needed.'], whenNotToUse: ['Use build_environment weather.'],
    inputProps: { action: P.action, name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_environment_effect', name: 'EE_Rain' }, exampleOutput: { success: true, message: 'Environment effect created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_impact_effect`, action: 'create_impact_effect', family: F,
    summary: 'Create an impact effect.', whenToUse: ['Hit FX needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { action: P.action, name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_impact_effect', name: 'IE_Bullet' }, exampleOutput: { success: true, message: 'Impact effect created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_ribbon`, action: 'create_niagara_ribbon', family: F,
    summary: 'Create a Niagara ribbon effect.', whenToUse: ['Trail/ribbon FX needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { action: P.action, name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_niagara_ribbon', name: 'NR_Slash' }, exampleOutput: { success: true, message: 'Niagara ribbon created' } }),
  buildRecord({ parentTool: T, id: `${T}.activate`, action: 'activate', family: F,
    summary: 'Activate a spawned effect component (PIE).', whenToUse: ['Effect must turn on at runtime.'], whenNotToUse: ['Author the effect.'],
    inputProps: { action: P.action, actorName: P.actorName, reset: E.reset }, required: ['action', 'actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', supportsUndo: false }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'activate', actorName: 'FX_1', reset: false }, exampleOutput: { success: true, message: 'Effect activated' } }),
  buildRecord({ parentTool: T, id: `${T}.activate_effect`, action: 'activate_effect', family: F,
    summary: 'Activate an effect by asset on a runtime actor.', whenToUse: ['Asset-driven runtime FX.'], whenNotToUse: ['Use activate.'],
    inputProps: { action: P.action, actorName: P.actorName, assetPath: P.assetPath, systemName: E.systemName }, required: ['action'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { supportsUndo: false }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'activate_effect', systemName: 'FX_1' }, exampleOutput: { success: true, message: 'Effect activated' } }),
  buildRecord({ parentTool: T, id: `${T}.deactivate`, action: 'deactivate', family: F,
    summary: 'Deactivate a runtime effect component.', whenToUse: ['Effect must turn off.'], whenNotToUse: ['Use activate.'],
    inputProps: { action: P.action, actorName: P.actorName }, required: ['action', 'actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', supportsUndo: false }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'deactivate', actorName: 'FX_1' }, exampleOutput: { success: true, message: 'Effect deactivated' } }),
  buildRecord({ parentTool: T, id: `${T}.reset`, action: 'reset', family: F,
    summary: 'Reset a runtime effect to initial state.', whenToUse: ['Effect must restart.'], whenNotToUse: ['Use deactivate.'],
    inputProps: { action: P.action, actorName: P.actorName, reset: E.reset }, required: ['action', 'actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { safeToRetry: true, supportsUndo: false }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'reset', actorName: 'FX_1', reset: true }, exampleOutput: { success: true, message: 'Effect reset' } }),
  buildRecord({ parentTool: T, id: `${T}.advance_simulation`, action: 'advance_simulation', family: F,
    summary: 'Advance a Niagara simulation by time (PIE/editor).', whenToUse: ['Step the sim manually.'], whenNotToUse: ['Let it run.'],
    inputProps: { action: P.action, actorName: P.actorName, deltaTime: E.deltaTime, steps: E.steps }, required: ['action'],
    effect: 'write', editorStates: ['edit', 'pie', 'simulate'], latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'advance_simulation', deltaTime: 0.016, steps: 2 }, exampleOutput: { success: true, message: 'Simulation advanced' } }),
  buildRecord({ parentTool: T, id: `${T}.add_niagara_module`, action: 'add_niagara_module', family: F,
    summary: 'Add a module to a Niagara emitter.', whenToUse: ['Emitter needs a module.'], whenNotToUse: ['Use connect_niagara_pins.'],
    inputProps: { action: P.action, assetPath: P.assetPath, systemPath: E.systemPath, emitterName: E.emitterName, modulePath: E.modulePath, scriptType: E.scriptType, name: P.name }, required: ['action', 'assetPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    outputProps: { nodeId: E.nodeId }, outputRequired: [],
    exampleInput: { action: 'add_niagara_module', assetPath: '/Game/NS_Fire', emitterName: 'Spark', modulePath: '/Niagara/Modules/Emitter/EmitterState.EmitterState', scriptType: 'Update' }, exampleOutput: { success: true, message: 'Niagara module added', nodeId: 'A1B2C3' } }),
  buildRecord({ parentTool: T, id: `${T}.connect_niagara_pins`, action: 'connect_niagara_pins', family: F,
    summary: 'Connect Niagara graph pins.', whenToUse: ['Modules must wire together.'], whenNotToUse: ['Use add_niagara_module.'],
    inputProps: { action: P.action, assetPath: P.assetPath, emitterName: E.emitterName, scriptType: E.scriptType, autoConnect: E.autoConnect }, required: ['action', 'assetPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'connect_niagara_pins', assetPath: '/Game/NS_Fire', scriptType: 'Update', autoConnect: true }, exampleOutput: { success: true, message: 'Niagara pins connected' } }),
  buildRecord({ parentTool: T, id: `${T}.remove_niagara_node`, action: 'remove_niagara_node', family: F,
    summary: 'Remove a Niagara graph node.', whenToUse: ['Node must be removed.'], whenNotToUse: ['Use connect_niagara_pins.'],
    inputProps: { action: P.action, assetPath: P.assetPath, systemPath: E.systemPath, emitterName: E.emitterName, scriptType: E.scriptType, nodeId: E.nodeId }, required: ['action', 'assetPath'],
    effect: 'destructive', behavior: { safeToRetry: false, supportsUndo: false }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'remove_niagara_node', assetPath: '/Game/NS_Fire', nodeId: 'A1B2C3' }, exampleOutput: { success: true, message: 'Niagara node removed' } }),
];
