import { commonSchemas } from '../../catalog/tool-definition-utils.js';
import {
  CINEMATICS_ACTIONS,
  MEDIA_ACTIONS,
  MOVIE_RENDER_ACTIONS,
  RECORD_REPLAY_ACTIONS,
} from '../shared/action-sets.js';
import type { ToolDefinition } from '../shared/tool-definition.js';

// manage_sequence exposes ~130 optional properties covering five action
// domains (core Sequencer, Cinematics, Movie Render Queue, Media, Take
// Recorder / Replay).  Only the subset relevant to the requested `action`
// is required at runtime; all others are optional.  When MCP clients
// support JSON Schema `oneOf` / `if-then`, this can be refactored into
// action-specific parameter groups to reduce client context consumption.
export const manageSequenceToolDefinition: ToolDefinition = {
    name: 'manage_sequence',
    category: 'utility',
    description: 'Edit Level Sequences, cinematic tracks, Movie Render Queue jobs, media playback assets, Take Recorder, and replay controls.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'create', 'open', 'add_camera', 'add_actor', 'add_actors', 'remove_actors',
            'get_bindings', 'play', 'pause', 'stop', 'set_playback_speed', 'add_keyframe',
            'get_properties', 'set_properties', 'duplicate', 'rename', 'delete', 'list', 'get_metadata', 'set_metadata',
            'add_spawnable_from_class', 'add_track', 'add_section', 'set_display_rate', 'set_tick_resolution',
            'set_work_range', 'set_view_range', 'set_track_muted', 'set_track_solo', 'set_track_locked',
            'list_tracks', 'remove_track', 'list_track_types',
            ...CINEMATICS_ACTIONS,
            ...MOVIE_RENDER_ACTIONS,
            ...MEDIA_ACTIONS,
            ...RECORD_REPLAY_ACTIONS
          ],
          description: 'Action'
        },
        name: commonSchemas.name,
        path: commonSchemas.assetPath,
        assetPath: commonSchemas.assetPath,
        sequencePath: commonSchemas.assetPath,
        masterSequencePath: commonSchemas.assetPath,
        subsequencePath: commonSchemas.assetPath,
        shotSequencePath: commonSchemas.assetPath,
        mapPath: commonSchemas.levelPath,
        mediaPlayerPath: commonSchemas.assetPath,
        mediaSourcePath: commonSchemas.assetPath,
        mediaTexturePath: commonSchemas.assetPath,
        mediaPlaylistPath: commonSchemas.assetPath,
        playlistPath: commonSchemas.assetPath,
        playerPath: commonSchemas.assetPath,
        sourcePath: commonSchemas.sourcePath,
        defaultSourcePath: commonSchemas.assetPath,
        sourcePaths: commonSchemas.arrayOfStrings,
        platformSources: commonSchemas.objectProp,
        animationPath: commonSchemas.animationPath,
        animationSequencePath: commonSchemas.animationPath,
        skeletalMeshPath: commonSchemas.skeletalMeshPath,
        materialPath: {
          ...commonSchemas.materialPath,
          description:
            'Optional expected material asset for the selected component slot.',
        },
        cameraShakePath: commonSchemas.cameraShakePath,
        cameraShakeClass: commonSchemas.stringProp,
        takePresetPath: commonSchemas.assetPath,
        recordingSequencePath: commonSchemas.assetPath,
        takeSequencePath: commonSchemas.assetPath,
        actorName: commonSchemas.actorName,
        actorNames: commonSchemas.arrayOfStrings,
        actors: commonSchemas.arrayOfStrings,
        sourceClasses: commonSchemas.arrayOfStrings,
        cameraActorName: commonSchemas.actorName,
        cameraName: commonSchemas.actorName,
        targetActorName: commonSchemas.actorName,
        targetActor: commonSchemas.actorName,
        sourceActors: commonSchemas.arrayOfStrings,
        location: commonSchemas.location,
        rotation: commonSchemas.rotation,
        bindingGuid: commonSchemas.stringProp,
        sectionName: commonSchemas.sectionName,
        shotName: commonSchemas.name,
        label: commonSchemas.stringProp,
        displayName: commonSchemas.stringProp,
        renderJobName: commonSchemas.name,
        jobName: commonSchemas.name,
        jobId: commonSchemas.stringProp,
        renderJobId: commonSchemas.stringProp,
        replayName: commonSchemas.name,
        friendlyName: commonSchemas.stringProp,
        sourceType: commonSchemas.stringProp,
        filePath: commonSchemas.outputPath,
        mediaPath: commonSchemas.outputPath,
        filePaths: commonSchemas.arrayOfStrings,
        url: commonSchemas.stringProp,
        urls: commonSchemas.arrayOfStrings,
        streamUrl: commonSchemas.stringProp,
        outputDirectory: commonSchemas.outputPath,
        fileNameFormat: commonSchemas.stringProp,
        renderPass: commonSchemas.stringProp,
        renderPasses: commonSchemas.arrayOfStrings,
        antiAliasingMethod: commonSchemas.stringProp,
        method: commonSchemas.stringProp,
        executorClass: commonSchemas.stringProp,
        useCurrentLevel: commonSchemas.booleanProp,
        consoleVariables: commonSchemas.objectProp,
        burnIn: {
          type: 'object',
          properties: {
            enabled: commonSchemas.booleanProp,
            compositeOntoFinalImage: commonSchemas.booleanProp,
            classPath: commonSchemas.stringProp
          }
        },
        filmback: commonSchemas.objectProp,
        lens: commonSchemas.objectProp,
        focus: commonSchemas.objectProp,
        settings: {
          type: 'object',
          properties: {
            handleFrameCount: commonSchemas.integerProp,
            zeroPadFrameNumbers: commonSchemas.integerProp,
            spatialSampleCount: commonSchemas.integerProp,
            temporalSampleCount: commonSchemas.integerProp,
            antiAliasingMethod: commonSchemas.stringProp,
            method: commonSchemas.stringProp
          }
        },
        tracks: commonSchemas.arrayOfStrings,
        trackNames: commonSchemas.arrayOfStrings,
        levelNames: commonSchemas.arrayOfStrings,
        properties: commonSchemas.arrayOfStrings,
        additionalOptions: commonSchemas.arrayOfStrings,
        componentName: commonSchemas.componentName,
        demoName: commonSchemas.name,
        frame: commonSchemas.integerProp,
        value: commonSchemas.value,
        property: commonSchemas.propertyName,
        propertyName: commonSchemas.propertyName,
        propertyPath: commonSchemas.stringProp,
        propertyType: commonSchemas.stringProp,
        parameterName: commonSchemas.parameterName,
        destinationPath: commonSchemas.destinationPath,
        newName: commonSchemas.newName,
        speed: commonSchemas.numberProp,
        playbackSpeed: commonSchemas.numberProp,
        focalLength: commonSchemas.numberProp,
        aperture: commonSchemas.numberProp,
        focusDistance: commonSchemas.numberProp,
        currentFocalLength: commonSchemas.numberProp,
        currentAperture: commonSchemas.numberProp,
        manualFocusDistance: commonSchemas.numberProp,
        sensorWidth: commonSchemas.numberProp,
        sensorHeight: commonSchemas.numberProp,
        positionOnRail: commonSchemas.numberProp,
        cranePitch: commonSchemas.numberProp,
        craneYaw: commonSchemas.numberProp,
        craneArmLength: commonSchemas.numberProp,
        width: commonSchemas.integerProp,
        height: commonSchemas.integerProp,
        temporalSampleCount: commonSchemas.integerProp,
        spatialSampleCount: commonSchemas.integerProp,
        playlistIndex: commonSchemas.integerProp,
        seekTime: commonSchemas.numberProp,
        time: commonSchemas.numberProp,
        timeSeconds: commonSchemas.numberProp,
        seconds: commonSchemas.numberProp,
        duration: commonSchemas.duration,
        durationFrames: commonSchemas.integerProp,
        durationSeconds: commonSchemas.duration,
        startTime: commonSchemas.numberProp,
        endTime: commonSchemas.numberProp,
        from: commonSchemas.numberProp,
        to: commonSchemas.numberProp,
        loopMode: commonSchemas.stringProp,
        className: commonSchemas.stringProp,
        spawnable: commonSchemas.booleanProp,
        activate: commonSchemas.booleanProp,
        autoClear: commonSchemas.booleanProp,
        autoPlay: commonSchemas.booleanProp,
        playOnOpen: commonSchemas.booleanProp,
        loop: commonSchemas.booleanProp,
        looping: commonSchemas.looping,
        enabled: commonSchemas.enabled,
        paused: commonSchemas.booleanProp,
        clearSources: commonSchemas.booleanProp,
        disableOthers: commonSchemas.booleanProp,
        includeTranslucentObjects: commonSchemas.booleanProp,
        loadDefaultMapOnStop: commonSchemas.booleanProp,
        onlyJob: commonSchemas.booleanProp,
        precacheFile: commonSchemas.booleanProp,
        prioritizeActors: commonSchemas.booleanProp,
        recordParentHierarchy: commonSchemas.booleanProp,
        recordInto: commonSchemas.booleanProp,
        reduceKeys: commonSchemas.booleanProp,
        save: commonSchemas.save,
        trackType: commonSchemas.stringProp,
        trackName: commonSchemas.stringProp,
        recordType: commonSchemas.stringProp,
        visibility: commonSchemas.stringProp,
        muted: commonSchemas.booleanProp,
        solo: commonSchemas.booleanProp,
        locked: commonSchemas.booleanProp,
        startFrame: commonSchemas.integerProp,
        endFrame: commonSchemas.integerProp,
        rowIndex: commonSchemas.integerProp,
        sectionIndex: commonSchemas.integerProp,
        frameRate: {
          type: ['number', 'string'],
          description: 'Frame rate as frames per second or a rate string such as 24fps or 24000/1001.'
        },
        resolution: commonSchemas.stringProp,
        materialIndex: commonSchemas.integerProp,
        checkpointSaveMaxMSPerFrame: commonSchemas.numberProp,
        maxRecordTimeSeconds: commonSchemas.numberProp,
        timeoutMs: commonSchemas.numberProp,
        start: commonSchemas.numberProp,
        end: commonSchemas.numberProp,
        lengthInFrames: commonSchemas.integerProp,
        playbackStart: commonSchemas.integerProp,
        playbackEnd: commonSchemas.integerProp,
        metadata: commonSchemas.objectProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase
      }
    }
  };
