// GENERATED-NOT-HERE: this file re-exports the canonical typed policy so the
// runtime validators can import one deterministic source. The serialized artifacts
// (src/utils/commands/console-command-policy.generated.ts and the native .h)
// are produced by scripts/generate-console-command-policy.ts. This module is NOT
// hand-edited with block lists; it imports the typed rule data only.
//
// Owner: Task 22 (console-command policy generation). Do not add handwritten
// DANGEROUS/FORBIDDEN arrays here.

import {
  CONSOLE_COMMAND_POLICY_RULES,
  type ConsoleCommandPolicySurface,
} from './console-command-policy-rules.js';
import type { ConsoleCommandPolicyBlockReason } from './console-command-policy-rules.js';
import { matchesRule } from './console-command-policy-matching.js';

export const CONSOLE_COMMAND_POLICY_GENERATED_TS_PATH =
  'src/utils/commands/console-command-policy.generated.ts';

export const CONSOLE_COMMAND_POLICY_GENERATED_NATIVE_PATH =
  'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/Domains/ConsoleCommand/McpAutomationBridge_ConsoleCommandPolicy.generated.h';

export const GENERATED_POLICY_HEADER =
  '// GENERATED by scripts/generate-console-command-policy.ts -- do not edit.';

type SurfaceNormalized = 'typescript' | 'native';

function appliesToSurface(
  appliesTo: 'typescript' | 'native' | 'both',
  surface: SurfaceNormalized,
): boolean {
  if (appliesTo === 'both') return true;
  return appliesTo === surface;
}

export type GeneratedConsoleCommandDecision = {
  readonly blocked: boolean;
  readonly reasonCode: ConsoleCommandPolicyBlockReason | 'ALLOWED';
  readonly ruleId: string | null;
};

/**
 * Evaluate a console command against the single canonical generated policy for a
 * given surface. Returns the same fail-closed decision the runtime validators
 * used before Task 22, now sourced from one generated rule set.
 */
export function evaluateGeneratedConsoleCommandPolicy(
  command: string,
  surface: ConsoleCommandPolicySurface,
): GeneratedConsoleCommandDecision {
  const normalized = command.trim().toLowerCase();
  for (const rule of CONSOLE_COMMAND_POLICY_RULES) {
    if (
      appliesToSurface(rule.appliesTo, surface) &&
      matchesRule(normalized, rule.matcher)
    ) {
      return {
        blocked: true,
        reasonCode: rule.reasonCode,
        ruleId: rule.id,
      };
    }
  }
  return { blocked: false, reasonCode: 'ALLOWED', ruleId: null };
}

/**
 * Convenience boolean helper matching the boolean contract the validators used.
 */
export function applyGeneratedConsoleCommandPolicy(
  command: string,
  surface: ConsoleCommandPolicySurface,
): boolean {
  return evaluateGeneratedConsoleCommandPolicy(command, surface).blocked;
}

/**
 * Boolean helper that unions both surfaces (intended fail-closed policy).
 */
export function applyGeneratedConsoleCommandPolicyFailClosed(command: string): boolean {
  return (
    applyGeneratedConsoleCommandPolicy(command, 'typescript') ||
    applyGeneratedConsoleCommandPolicy(command, 'native')
  );
}

export function serializeConsoleCommandPolicyGenerated(): string {
  return JSON.stringify({
    schema: 'unreal.console-command-policy-generated.v1',
    generated: true,
    source: 'console-command-policy-rules',
    surfaces: ['typescript', 'native'],
    rules: CONSOLE_COMMAND_POLICY_RULES,
  });
}
