// scripts/canonical-registry/cpp-registry.ts
//
// Deterministic emission of the native C++ parent registry:
//   - a thin aggregator McpGeneratedParentRegistry.h / .cpp
//   - one shard .cpp per PARENT_GROUPS entry
//   - schema fragment .cpp files for each parent that opts into a schema split
//
// Each shard declares its FMcpToolDefinition subclasses BEFORE the
// RegisterGenerated*Capabilities() function that instantiates them (a class
// must be complete where `new` is evaluated), so the emitted translation
// unit compiles cleanly.
//
// A split parent delegates ONLY its parameter catalog to the fragments; its
// name, action enum, Required set and registration stay in the shard. That
// division is not cosmetic: the native parity audit reads a tool's name and
// actions from the enclosing class body alone, and follows namespace-qualified
// calls into other files only when collecting schema properties.

import { cppStringLiteral, type JsonSchemaNode } from './types.js';
import type { ToolDefinition } from '../../src/tools/definitions/shared/tool-definition.js';
import {
  GENERATED_SHARD_STEMS,
  PARENT_GROUPS,
  REGISTRY_CLASS,
  SCHEMA_FRAGMENT_NAMESPACE,
  SCHEMA_FRAGMENT_SUFFIXES,
  classNameFor,
  groupedParents,
  isStrict,
  schemaFragmentFunction,
  type GroupedShard,
  type SchemaFragmentSuffix,
} from './grouping.js';
import { jsonSchemaToCppCalls } from './cpp-schema.js';

const GENERATED_BANNER =
  '// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.\n';

// ---- aggregator header ------------------------------------------------------
const splitSchemaParents = (): readonly string[] =>
  PARENT_GROUPS.flatMap((g) => (g.splitSchemaParent === undefined ? [] : [g.splitSchemaParent]));

const buildFragmentDeclarations = (): string => {
  const parents = splitSchemaParents();
  if (parents.length === 0) return '';
  const decls = parents
    .flatMap((parent) =>
      SCHEMA_FRAGMENT_SUFFIXES.map(
        (suffix) => `\tvoid ${schemaFragmentFunction(parent, suffix)}(FMcpSchemaBuilder& Schema);`,
      ),
    )
    .join('\n');
  return (
    '\n/**\n' +
    ' * Parameter-catalog fragments for parents whose schema is emitted into\n' +
    ' * separate translation units to stay within the source-size ceiling.\n' +
    ' * Each appends its parameters onto the builder it receives.\n' +
    ' */\n' +
    `namespace ${SCHEMA_FRAGMENT_NAMESPACE}\n{\n` +
    decls +
    '\n}\n'
  );
};

export const buildAggregatorHeader = (): string => {
  const decls = PARENT_GROUPS.map(
    (g) => `\tstatic void RegisterGenerated${g.shard}Capabilities(FMcpToolRegistry& Registry);`,
  ).join('\n');
  return (
    `${GENERATED_BANNER}` +
    '#pragma once\n\n' +
    '#include "CoreMinimal.h"\n' +
    '#include "MCP/Registry/McpToolDefinition.h"\n' +
    '#include "MCP/Registry/McpToolRegistry.h"\n' +
    '#include "MCP/Registry/McpSchemaBuilder.h"\n\n' +
    '/**\n' +
    ' * Generated canonical parent tool registry (Task 23).\n' +
    ' *\n' +
    ' * One FMcpToolDefinition per canonical parent tool, built from the same\n' +
    ' * 23-tool contract source that drives the TypeScript gateway manifest.\n' +
    ' * Registered into FMcpToolRegistry at static-init time; the canonical-name\n' +
    ' * gate in McpToolRegistry.cpp admits exactly these 23 names.\n' +
    ' *\n' +
    ' * Union/any schema fields are emitted through first-class FMcpSchemaBuilder\n' +
    ' * methods (TypeUnion / AnyValue), so no shared helper block is required.\n' +
    ' */\n' +
    `class ${REGISTRY_CLASS}\n{\npublic:\n` +
    '\tstatic void RegisterAll();\n\n' +
    '// One entry point per generated capability shard; RegisterAll() calls each.\n' +
    decls +
    '\n};\n' +
    buildFragmentDeclarations()
  );
};

// ---- aggregator source ------------------------------------------------------
export const buildAggregatorSource = (): string => {
  const calls = PARENT_GROUPS.map(
    (g) =>
      `\tRegisterGenerated${g.shard}Capabilities(FMcpToolRegistry::Get());`,
  ).join('\n\n');
  return (
    `${GENERATED_BANNER}\n` +
    '#include "MCP/Tools/McpGeneratedParentRegistry.h"\n\n\n' +
    `void ${REGISTRY_CLASS}::RegisterAll()\n\n{\n\n` +
    calls +
    '\n\n}\n\n\n' +
    'namespace\n\n{\n\n' +
    '\tstruct FRegisterGeneratedParentTools\n\t{\n\t\tFRegisterGeneratedParentTools()\n\t\t{\n' +
    `\t\t\t${REGISTRY_CLASS}::RegisterAll();\n` +
    '\t\t}\n\t};\n\n' +
    '\tstatic FRegisterGeneratedParentTools GRegisterGeneratedParentTools;\n\n}\n'
  );
};

// ---- schema partition ------------------------------------------------------
// The action enum is matched by name by the parity audit and must stay in the
// class body, so it is never routed to a fragment.
const ACTION_PROPERTY = 'action';

// Emit one property through the shared emitter, so a relocated parameter is
// byte-identical to what an unsplit shard would have contained.
const emitProperty = (name: string, node: JsonSchemaNode): readonly string[] =>
  jsonSchemaToCppCalls({ properties: { [name]: node } }).lines;

interface PartitionedSchema {
  readonly fragments: ReadonlyMap<SchemaFragmentSuffix, readonly string[]>;
  readonly inClass: readonly string[];
}

// A parameter that emits a single line is a leaf ("Fields"); one that opens a
// sub-builder lambda spans several lines and is composite ("Structures"). The
// buckets are therefore self-classifying: a new parameter lands in the right
// fragment with no table to maintain.
const partitionSchema = (parent: ToolDefinition): PartitionedSchema => {
  const schema = (parent.inputSchema ?? {}) as JsonSchemaNode;
  const properties = (schema.properties ?? {}) as Record<string, JsonSchemaNode>;
  const fields: string[] = [];
  const structures: string[] = [];
  const inClass: string[] = [];

  for (const [name, node] of Object.entries(properties)) {
    const lines = emitProperty(name, node);
    if (name === ACTION_PROPERTY) inClass.push(...lines);
    else if (lines.length === 1) fields.push(...lines);
    else structures.push(...lines);
  }
  inClass.push(...jsonSchemaToCppCalls({ required: schema.required ?? [] }).lines);

  return {
    fragments: new Map<SchemaFragmentSuffix, readonly string[]>([
      ['Fields', fields],
      ['Structures', structures],
    ]),
    inClass,
  };
};

const buildSchemaBody = (parent: ToolDefinition, split: boolean): string => {
  if (!split) {
    return jsonSchemaToCppCalls((parent.inputSchema ?? {}) as JsonSchemaNode).lines.join('\n');
  }
  const appends = SCHEMA_FRAGMENT_SUFFIXES.map(
    (suffix) =>
      `\t\t${SCHEMA_FRAGMENT_NAMESPACE}::${schemaFragmentFunction(parent.name, suffix)}(Schema);`,
  );
  return [...appends, ...partitionSchema(parent).inClass].join('\n');
};

// ---- one shard -------------------------------------------------------------
const buildToolClass = (parent: ToolDefinition, split: boolean): string => {
  const className = classNameFor(parent.name);
  const strict = isStrict(parent.name)
    ? '\tbool EnforceStrictArguments() const override { return true; }\n'
    : '';
  const body = buildSchemaBody(parent, split);
  return (
    `class ${className} : public FMcpToolDefinition\n{\npublic:\n` +
    `\tFString GetName() const override { return TEXT("${cppStringLiteral(parent.name)}"); }\n` +
    `\tFString GetDescription() const override { return TEXT("${cppStringLiteral(parent.description)}"); }\n` +
    `\tFString GetCategory() const override { return TEXT("${cppStringLiteral(parent.category ?? 'utility')}"); }\n` +
    strict +
    '\tTSharedPtr<FJsonObject> BuildInputSchema() const override\n\t{\n' +
    '\t\tFMcpSchemaBuilder Schema;\n' +
    `${body}\n` +
    '\t\treturn Schema.Build();\n\t}\n};'
  );
};

const buildShardSource = (group: GroupedShard): string => {
  const classes = group.parents
    .map((p) => buildToolClass(p, p.name === group.splitSchemaParent))
    .join('\n\n');
  const registers = group.parents
    .map((p) => `\tRegistry.Register(new ${classNameFor(p.name)}());`)
    .join('\n\n');
  return (
    `${GENERATED_BANNER}\n` +
    '#include "MCP/Tools/McpGeneratedParentRegistry.h"\n\n' +
    classes +
    `\n\n\nvoid ${REGISTRY_CLASS}::RegisterGenerated${group.shard}Capabilities(FMcpToolRegistry& Registry)\n\n{\n\n` +
    registers +
    '\n\n}\n'
  );
};

// ---- one schema fragment ----------------------------------------------------
const buildFragmentSource = (
  parent: ToolDefinition,
  suffix: SchemaFragmentSuffix,
  lines: readonly string[],
): string =>
  `${GENERATED_BANNER}\n` +
  '#include "MCP/Tools/McpGeneratedParentRegistry.h"\n\n' +
  `namespace ${SCHEMA_FRAGMENT_NAMESPACE}\n{\n` +
  `void ${schemaFragmentFunction(parent.name, suffix)}(FMcpSchemaBuilder& Schema)\n{\n` +
  lines.join('\n') +
  '\n}\n}\n';

const buildFragmentTargets = (group: GroupedShard): GeneratedSourceTarget[] => {
  const split = group.splitSchemaParent;
  if (split === undefined) return [];

  const parent = group.parents.find((p) => p.name === split);
  if (!parent) {
    throw new Error(
      `FATAL: shard "${group.shard}" splits the schema of "${split}", which is absent from its ` +
        'resolved parents.',
    );
  }

  const { fragments } = partitionSchema(parent);
  return SCHEMA_FRAGMENT_SUFFIXES.map((suffix) => {
    const lines = fragments.get(suffix);
    if (lines === undefined) {
      throw new Error(
        `FATAL: schema fragment "${suffix}" has no partition bucket for parent "${split}".`,
      );
    }
    return {
      stem: `${group.shard}${suffix}`,
      content: buildFragmentSource(parent, suffix, lines),
    };
  });
};

// ---- all shard targets ------------------------------------------------------
export interface ShardTarget {
  readonly shard: string;
  readonly content: string;
}

export const buildShardTargets = (
  parents: readonly ToolDefinition[],
): ShardTarget[] =>
  groupedParents(parents).map((group) => ({
    shard: group.shard,
    content: buildShardSource(group),
  }));

export interface GeneratedSourceTarget {
  readonly stem: string;
  readonly content: string;
}

// Every McpGeneratedParentRegistry_<stem>.cpp the generator owns, in
// GENERATED_SHARD_STEMS order. Emission validates itself against that plan so a
// drifting stem fails before any file is written.
export const buildRegistrySourceTargets = (
  parents: readonly ToolDefinition[],
): GeneratedSourceTarget[] => {
  const targets = groupedParents(parents).flatMap((group) => [
    { stem: group.shard, content: buildShardSource(group) },
    ...buildFragmentTargets(group),
  ]);

  const stems = targets.map((t) => t.stem);
  if (
    stems.length !== GENERATED_SHARD_STEMS.length ||
    stems.some((stem, index) => stem !== GENERATED_SHARD_STEMS[index])
  ) {
    throw new Error(
      `FATAL: emitted registry stems [${stems.join(', ')}] do not match the canonical plan ` +
        `[${GENERATED_SHARD_STEMS.join(', ')}].`,
    );
  }
  return targets;
};
