// scripts/canonical-registry/targets.ts
//
// Authoritative target-file plan for the Task-23 canonical registry generator.
//
// Owns EVERY generated artifact target (TS data, neutral JSON, parent defs,
// routing index, native parent registry, native capability shards + index).
// Malformed / duplicate / missing input fails BEFORE any target content is
// constructed (see native-shards / types validation), so the generator refuses
// to emit a partial or foreign set.
//
// Includes stale-target cleanup metadata: the generated file paths that this
// lane now owns, and the orphan header (NOT generated by this lane) that the
// orchestrator must delete on regeneration. Nothing is deleted here.

import { existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CapabilityRecord } from '../../src/tools/catalog/capabilities/model.js';
import { ALL_CAPABILITY_RECORD_COUNT } from '../../src/tools/catalog/capabilities/records/aggregate.js';
import {
  buildRecordSummaries,
  buildLexicalIndex,
  buildMigrationData,
  buildAliasData,
  buildDocsData,
  buildSortedRecords,
  sha256Hex,
} from './types.js';
import {
  buildTsDataModule,
  buildParentDefsModule,
  buildRoutingIndexModule,
  buildCostIndexModule,
  buildNeutralModel,
} from './ts-targets.js';
import {
  buildAggregatorHeader,
  buildAggregatorSource,
  buildRegistrySourceTargets,
} from './cpp-registry.js';
import {
  buildNativeCapabilityShards,
  buildNativeCapabilityIndexHeader,
  buildNativeCapabilityShardSource,
  type NativeCapabilityShard,
} from './native-shards.js';
import { GENERATED_SHARD_STEMS } from './grouping.js';
import { deriveParents } from './parent-derivation.js';
import { buildSupportMatrixDoc, buildSupportMatrixJson } from './support-matrix.js';
import {
  buildActionReferenceDoc,
  buildMigrationReferenceDoc,
  type MigrationEntryView,
} from './docs-reference.js';

export type ManifestTarget = readonly [path: string, content: string];

export interface BuildTargetsInput {
  readonly records: readonly CapabilityRecord[];
  // The 23 canonical parent definitions are DERIVED EXCLUSIVELY from the
  // records (no hand-authored base / allToolDefinitions / generated artifact
  // is consulted), so the generator bootstrap stays acyclic with its own
  // generated output.
  readonly migrationMap: {
    readonly entries: ReadonlyMap<string, MigrationEntryView>;
  };
  readonly generateAliases: () => {
    readonly aliases: ReadonlyArray<{ alias: string; canonicalId: string; source: string }>;
    readonly conflicts: ReadonlyArray<{ alias: string; canonicalIds: readonly string[] }>;
  };
}

const ROOT = resolve(process.cwd());

// Stale-target cleanup metadata.
export interface StaleTargetMeta {
  readonly orphanHeader: string; // orphan file superseded by generator-owned shards
  readonly ownedFiles: readonly string[]; // all generator-owned target paths
}

// Capability shards moved from orphan `.h` payloads to compiled `.cpp`
// translation units. A leftover header would keep a stale copy of the canonical
// records on disk next to the live shards, so the generator deletes these on
// write and `--check` reports them as drift.
export const listStaleCapabilityShardHeaders = (): readonly string[] => {
  const dir = nativeCapabilityDir();
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.startsWith('McpGeneratedCapabilityShards_') && name.endsWith('.h'))
    .sort()
    .map((name) => resolve(dir, name));
};

const nativeCapabilityDir = (): string =>
  resolve(ROOT, 'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/MCP/Generated');

const nativeToolsDir = (): string =>
  resolve(ROOT, 'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/MCP/Tools');

const genDir = (): string =>
  resolve(ROOT, 'src/tools/catalog/capabilities/generated');

const orchestrationDir = (): string =>
  resolve(ROOT, 'src/tools/orchestration');

const docsDir = (): string => resolve(ROOT, 'docs');

export const buildTargets = (input: BuildTargetsInput): ManifestTarget[] => {
  const { records, migrationMap, generateAliases } = input;
  if (records.length !== ALL_CAPABILITY_RECORD_COUNT) {
    throw new Error(
      `FATAL: expected ${ALL_CAPABILITY_RECORD_COUNT} capability records, `
      + `received ${records.length}. Refusing to generate.`,
    );
  }

  // Single deterministic sort by canonical id; shared by TS module, neutral
  // JSON, and native capability shards -- the record artifacts ONLY.
  const sortedRecords = buildSortedRecords(records);
  // Parents are derived EXCLUSIVELY from the records (no hand-authored base),
  // which keeps the generator's bootstrap acyclic with its own generated
  // output, and from the canonical record SEQUENCE rather than the id-sorted
  // view so each action enum keeps its authored (non-alphabetical) order. The
  // generator entrypoint validates grouping against deriveParents(records), so
  // deriving from anything else here would emit a parent set that was never
  // grouping-checked.
  const parents = deriveParents(records);
  const summaries = buildRecordSummaries(sortedRecords);
  const lexicalIndex = buildLexicalIndex(sortedRecords);
  const migrationData = buildMigrationData(migrationMap);
  const aliasData = buildAliasData(generateAliases);
  const docsData = buildDocsData(parents);

  const revisionSource = JSON.stringify({ count: sortedRecords.length, summaries, migration: migrationData, aliases: aliasData });
  const catalogRevision = sha256Hex(revisionSource).slice(0, 16);

  const tsData = buildTsDataModule({
    records: sortedRecords, summaries, lexicalIndex, migrationData, aliasData, docsData,
    catalogRevision, recordCount: sortedRecords.length,
  });
  const parentDefs = buildParentDefsModule(parents);
  const routingIndex = buildRoutingIndexModule(parents);
  const costIndex = buildCostIndexModule(sortedRecords);
  const neutralJson = `${buildNeutralModel({
    catalogRevision, recordCount: sortedRecords.length, records: sortedRecords, summaries, lexicalIndex,
    migrationData, aliasData, docsData,
  })}\n`;

  // Native capability shards: complete canonical records, per-parent, sanitized symbols.
  const nativeShards: readonly NativeCapabilityShard[] = buildNativeCapabilityShards(sortedRecords);
  const capDir = nativeCapabilityDir();
  const capTargets: ManifestTarget[] = [
    [
      resolve(capDir, 'McpGeneratedCapabilityShards.h'),
      buildNativeCapabilityIndexHeader(nativeShards, catalogRevision),
    ],
    ...nativeShards.map(
      (s) => [resolve(capDir, `McpGeneratedCapabilityShards_${s.symbol}.cpp`), buildNativeCapabilityShardSource(s)] as ManifestTarget,
    ),
  ];

  // Shards plus the schema fragments of every split parent, self-validated
  // against GENERATED_SHARD_STEMS by the emitter.
  const registrySources = buildRegistrySourceTargets(parents);

  const targets: ManifestTarget[] = [
    [resolve(genDir(), 'canonical-registry.generated.ts'), tsData],
    [resolve(genDir(), 'canonical-registry.generated.json'), neutralJson],
    [resolve(genDir(), 'parent-tool-definitions.generated.ts'), parentDefs],
    [resolve(genDir(), 'capability-cost-index.generated.ts'), costIndex],
    [resolve(orchestrationDir(), 'generated-routing-index.generated.ts'), routingIndex],
    [
      resolve(docsDir(), 'capability-support-matrix.md'),
      buildSupportMatrixDoc({ records: sortedRecords, catalogRevision }),
    ],
    [
      resolve(docsDir(), 'capability-support-matrix.generated.json'),
      buildSupportMatrixJson({ records: sortedRecords, catalogRevision }),
    ],
    [
      resolve(docsDir(), 'action-reference.generated.md'),
      buildActionReferenceDoc({ records: sortedRecords, catalogRevision }),
    ],
    [
      resolve(docsDir(), 'migration-reference.generated.md'),
      buildMigrationReferenceDoc({
        records: sortedRecords,
        catalogRevision,
        migrationEntries: migrationMap.entries,
      }),
    ],
    [resolve(nativeToolsDir(), 'McpGeneratedParentRegistry.h'), buildAggregatorHeader()],
    [resolve(nativeToolsDir(), 'McpGeneratedParentRegistry.cpp'), buildAggregatorSource()],
    ...registrySources.map(
      (t) => [resolve(nativeToolsDir(), `McpGeneratedParentRegistry_${t.stem}.cpp`), t.content] as ManifestTarget,
    ),
    ...capTargets,
  ];

  if (registrySources.length !== GENERATED_SHARD_STEMS.length) {
    throw new Error(
      `FATAL: expected ${GENERATED_SHARD_STEMS.length} generated registry sources, ` +
        `emitted ${registrySources.length}.`,
    );
  }
  if (nativeShards.length === 0) {
    throw new Error('FATAL: native capability shards produced zero shards. Refusing to generate.');
  }

  return targets;
};

export const staleTargetMeta = (): StaleTargetMeta => ({
  orphanHeader: resolve(nativeCapabilityDir(), 'McpGeneratedCapabilityShards.h'),
  ownedFiles: [
    resolve(genDir(), 'canonical-registry.generated.ts'),
    resolve(genDir(), 'canonical-registry.generated.json'),
    resolve(genDir(), 'parent-tool-definitions.generated.ts'),
    resolve(genDir(), 'capability-cost-index.generated.ts'),
    resolve(orchestrationDir(), 'generated-routing-index.generated.ts'),
    resolve(docsDir(), 'capability-support-matrix.md'),
    resolve(docsDir(), 'capability-support-matrix.generated.json'),
    resolve(docsDir(), 'action-reference.generated.md'),
    resolve(docsDir(), 'migration-reference.generated.md'),
    resolve(nativeToolsDir(), 'McpGeneratedParentRegistry.h'),
    resolve(nativeToolsDir(), 'McpGeneratedParentRegistry.cpp'),
    ...GENERATED_SHARD_STEMS.map((stem) =>
      resolve(nativeToolsDir(), `McpGeneratedParentRegistry_${stem}.cpp`),
    ),
    resolve(nativeCapabilityDir(), 'McpGeneratedCapabilityShards.h'),
  ],
});
