/**
 * Foliage family records (14 actions).
 *
 * Grounded in environment-foliage-actions.ts and native
 * EnvironmentHandlers.cpp foliage dispatch. add_foliage dispatches to
 * add_foliage_type (when meshPath present) or paint_foliage (when
 * foliageType/locations present). create_foliage_type dispatches to
 * add_foliage_type. paint_foliage_instances and remove_foliage_instances
 * dispatch through build_environment. configure_foliage_* dispatch through
 * build_environment.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildRecord } from './helpers.js';
import { P } from './properties.js';

const F = 'foliage';
const WU = ['Foliage must be added, configured, or removed in the level.'];

export const FOLIAGE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'build_environment.add_foliage', action: 'add_foliage', family: F,
    summary: 'Add foliage: create a type (meshPath) or place instances (foliageType + locations).',
    whenToUse: WU, whenNotToUse: ['A procedural foliage volume should be used for large areas.'],
    inputProps: { count: P.count, action: P.action, name: P.name, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      meshPath: P.meshPath, density: P.density, minScale: P.minScale, maxScale: P.maxScale,
      alignToNormal: P.alignToNormal, randomYaw: P.randomYaw, cullDistance: P.cullDistance,
      locations: P.locations, location: P.location, radius: P.radius, position: P.position },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'add_foliage', dispatchMode: 'action',
    exampleInput: { action: 'add_foliage', meshPath: '/Game/Meshes/SM_Bush', name: 'Bush_Type' },
    exampleOutput: { success: true, message: 'Foliage type added' },
  }),
  buildRecord({
    id: 'build_environment.add_foliage_instances', action: 'add_foliage_instances', family: F,
    summary: 'Add explicit foliage instances with transforms.',
    whenToUse: WU, whenNotToUse: ['Random scatter via paint_foliage is sufficient.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      meshPath: P.meshPath, locations: P.locations, transforms: P.transforms },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'add_foliage_instances', dispatchMode: 'action',
    exampleInput: { action: 'add_foliage_instances', foliageType: 'Bush_Type', transforms: [{ location: { x: 0, y: 0, z: 0 } }] },
    exampleOutput: { success: true, message: 'Foliage instances added' },
  }),
  buildRecord({
    id: 'build_environment.get_foliage_instances', action: 'get_foliage_instances', family: F,
    summary: 'Retrieve foliage instances for a foliage type.',
    whenToUse: ['Existing foliage instances must be inspected.'],
    whenNotToUse: ['Foliage should be removed rather than inspected.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath },
    required: ['action'],
    effect: 'read', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'get_foliage_instances', foliageType: 'Bush_Type' },
    exampleOutput: { success: true, message: 'Instances retrieved' },
  }),
  buildRecord({
    id: 'build_environment.remove_foliage', action: 'remove_foliage', family: F,
    summary: 'Remove foliage instances or all foliage for a type.',
    whenToUse: WU, whenNotToUse: ['Foliage should be hidden rather than removed.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath, removeAll: P.removeAll },
    required: ['action'],
    effect: 'destructive', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'remove_foliage', foliageType: 'Bush_Type' },
    exampleOutput: { success: true, message: 'Foliage removed' },
  }),
  buildRecord({
    id: 'build_environment.remove_foliage_instances', action: 'remove_foliage_instances', family: F,
    summary: 'Remove foliage instances for a specific type or all types.',
    whenToUse: WU, whenNotToUse: ['All foliage should be removed via remove_foliage with removeAll.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath, removeAll: P.removeAll },
    required: ['action'],
    effect: 'destructive', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'remove_foliage_instances', foliageType: 'Bush_Type' },
    exampleOutput: { success: true, message: 'Foliage instances removed' },
  }),
  buildRecord({
    id: 'build_environment.paint_foliage', action: 'paint_foliage', family: F,
    summary: 'Paint foliage instances at a position or set of locations.',
    whenToUse: WU, whenNotToUse: ['Explicit transforms should be used via add_foliage_instances.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      locations: P.locations, position: P.position, location: P.location, radius: P.radius,
      density: P.density, strength: P.strength },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'paint_foliage', dispatchMode: 'action',
    exampleInput: { action: 'paint_foliage', foliageType: 'Bush_Type', position: { x: 0, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Foliage painted' },
  }),
  buildRecord({
    id: 'build_environment.paint_foliage_instances', action: 'paint_foliage_instances', family: F,
    summary: 'Paint foliage instances with brush-based placement.',
    whenToUse: WU, whenNotToUse: ['Explicit locations should be used via add_foliage_instances.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      locations: P.locations, position: P.position, radius: P.radius, density: P.density },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'paint_foliage_instances', foliageType: 'Bush_Type', position: { x: 0, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Foliage instances painted' },
  }),
  buildRecord({
    id: 'build_environment.create_foliage_type', action: 'create_foliage_type', family: F,
    summary: 'Create a foliage type asset from a static mesh.',
    whenToUse: ['A new foliage type asset is needed.'],
    whenNotToUse: ['An existing foliage type should be reused.'],
    inputProps: { action: P.action, name: P.name, foliageType: P.foliageType, meshPath: P.meshPath,
      staticMesh: P.staticMesh, path: P.path, density: P.density, minScale: P.minScale, maxScale: P.maxScale },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'add_foliage_type', dispatchMode: 'action',
    exampleInput: { action: 'create_foliage_type', name: 'Bush_Type', meshPath: '/Game/Meshes/SM_Bush' },
    exampleOutput: { success: true, message: 'Foliage type created' },
  }),
  buildRecord({
    id: 'build_environment.configure_foliage_mesh', action: 'configure_foliage_mesh', family: F,
    summary: 'Configure the mesh assignment for a foliage type.',
    whenToUse: ['A foliage type needs a different mesh.'],
    whenNotToUse: ['A new foliage type should be created instead.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      meshPath: P.meshPath, staticMesh: P.staticMesh },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_foliage_mesh', foliageType: 'Bush_Type', meshPath: '/Game/Meshes/SM_Bush_v2' },
    exampleOutput: { success: true, message: 'Foliage mesh configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_foliage_placement', action: 'configure_foliage_placement', family: F,
    summary: 'Configure placement parameters for a foliage type.',
    whenToUse: ['Foliage placement density or scale must be tuned.'],
    whenNotToUse: ['Foliage should be placed manually.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath,
      density: P.density, minScale: P.minScale, maxScale: P.maxScale, alignToNormal: P.alignToNormal, randomYaw: P.randomYaw },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_foliage_placement', foliageType: 'Bush_Type', density: 0.5 },
    exampleOutput: { success: true, message: 'Foliage placement configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_foliage_lod', action: 'configure_foliage_lod', family: F,
    summary: 'Configure LOD settings for a foliage type.',
    whenToUse: ['Foliage LOD distances must be tuned.'],
    whenNotToUse: ['LODs should be generated rather than configured.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath, settings: P.settings },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_foliage_lod', foliageType: 'Bush_Type' },
    exampleOutput: { success: true, message: 'Foliage LOD configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_foliage_collision', action: 'configure_foliage_collision', family: F,
    summary: 'Configure collision settings for a foliage type.',
    whenToUse: ['Foliage collision must be enabled or disabled.'],
    whenNotToUse: ['Collision is not needed for decorative foliage.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath, collisionEnabled: P.collisionEnabled },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_foliage_collision', foliageType: 'Bush_Type', collisionEnabled: true },
    exampleOutput: { success: true, message: 'Foliage collision configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_foliage_culling', action: 'configure_foliage_culling', family: F,
    summary: 'Configure culling distance for a foliage type.',
    whenToUse: ['Foliage cull distance must be tuned.'],
    whenNotToUse: ['All foliage should remain visible at all distances.'],
    inputProps: { action: P.action, foliageType: P.foliageType, foliageTypePath: P.foliageTypePath, cullDistance: P.cullDistance },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_foliage_culling', foliageType: 'Bush_Type', cullDistance: 5000 },
    exampleOutput: { success: true, message: 'Foliage culling configured' },
  }),
  buildRecord({
    id: 'build_environment.create_procedural_foliage', action: 'create_procedural_foliage', family: F,
    summary: 'Create a procedural foliage volume with seeded scatter.',
    whenToUse: ['Large-area procedural foliage scatter is needed.'],
    whenNotToUse: ['Manual foliage placement is sufficient.'],
    inputProps: { action: P.action, name: P.name, volumeName: P.volumeName, foliageTypes: P.foliageTypes,
      bounds: P.bounds, seed: P.seed, tileSize: P.tileSize },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'create_procedural_foliage', dispatchMode: 'action',
    exampleInput: { action: 'create_procedural_foliage', name: 'PFV_1', foliageTypes: [{ meshPath: '/Game/Meshes/SM_Bush', density: 0.5 }] },
    exampleOutput: { success: true, message: 'Procedural foliage created' },
  }),
];
