/**
 * Landscape family records (16 actions).
 *
 * Grounded in environment-landscape-actions.ts (create_landscape, sculpt,
 * sculpt_landscape, modify_heightmap), environment-misc-actions.ts
 * (set_landscape_material, configure_landscape_material, create_landscape_grass_type,
 * generate_lods, bake_lightmap), and native EnvironmentHandlers.cpp dispatch
 * for paint_landscape, paint_landscape_layer, import_heightmap, export_heightmap,
 * create_landscape_layer_info, configure_landscape_splines, configure_landscape_lod,
 * create_landscape_streaming_proxy.
 *
 * create_landscape dispatches to the 'create_landscape' bridge action (dispatchMode
 * 'action'); sculpt/sculpt_landscape dispatch to 'sculpt_landscape'; modify_heightmap
 * dispatches to 'modify_heightmap'. The remaining actions dispatch through the
 * 'build_environment' bridge tool.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildRecord } from './helpers.js';
import { P } from './properties.js';

const F = 'landscape';
const WU = ['A landscape must be created or modified in the current level.'];

export const LANDSCAPE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'build_environment.create_landscape', action: 'create_landscape', family: F,
    topics: ['landscape', 'terrain', 'new landscape', 'heightfield'],
    summary: 'Create a new Landscape actor in the current level.',
    whenToUse: WU, whenNotToUse: ['A landscape already exists and should be modified.'],
    inputProps: { action: P.action, name: P.name, landscapeName: P.landscapeName, location: P.location, sizeX: P.sizeX,
      sizeY: P.sizeY, quadsPerSection: P.quadsPerSection, sectionSize: P.sectionSize,
      sectionsPerComponent: P.sectionsPerComponent, componentCount: P.componentCount, materialPath: P.materialPath },
    required: ['action'],
    requiredOneOf: ['name', 'landscapeName'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'create_landscape', dispatchMode: 'action',
    exampleInput: { action: 'create_landscape', name: 'Landscape_1', sizeX: 1009, sizeY: 1009 },
    exampleOutput: { success: true, message: 'Landscape created' },
  }),
  buildRecord({
    id: 'build_environment.sculpt', action: 'sculpt', family: F,
    summary: 'Sculpt the landscape heightmap at a location with a brush.',
    whenToUse: WU, whenNotToUse: ['The landscape should be modified via raw heightmap data.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      tool: P.tool, location: P.location, radius: P.radius, strength: P.strength,
      falloff: P.falloff, skipFlush: P.skipFlush },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'sculpt_landscape', dispatchMode: 'action',
    exampleInput: { action: 'sculpt', landscapeName: 'Landscape_1', location: { x: 0, y: 0, z: 0 }, radius: 500 },
    exampleOutput: { success: true, message: 'Landscape sculpted' },
  }),
  buildRecord({
    id: 'build_environment.sculpt_landscape', action: 'sculpt_landscape', family: F,
    summary: 'Sculpt the landscape heightmap at a location with a brush.',
    whenToUse: WU, whenNotToUse: ['The landscape should be modified via raw heightmap data.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      tool: P.tool, location: P.location, radius: P.radius, strength: P.strength,
      falloff: P.falloff, skipFlush: P.skipFlush },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'sculpt_landscape', dispatchMode: 'action',
    exampleInput: { action: 'sculpt_landscape', landscapeName: 'Landscape_1', location: { x: 0, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Landscape sculpted' },
    aliases: ['build_environment.sculpt_heightmap'],
  }),
  buildRecord({
    id: 'build_environment.modify_heightmap', action: 'modify_heightmap', family: F,
    summary: 'Modify landscape heightmap data in a region.',
    whenToUse: WU, whenNotToUse: ['The landscape should be sculpted interactively.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      operation: P.operation, heightData: P.heightData, minX: P.minX, minY: P.minY,
      maxX: P.maxX, maxY: P.maxY, region: P.region, updateNormals: P.updateNormals, skipFlush: P.skipFlush },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'modify_heightmap', dispatchMode: 'action',
    exampleInput: { action: 'modify_heightmap', landscapeName: 'Landscape_1', operation: 'set', heightData: [100, 200] },
    exampleOutput: { success: true, message: 'Heightmap modified' },
  }),
  buildRecord({
    id: 'build_environment.set_landscape_material', action: 'set_landscape_material', family: F,
    summary: 'Set the material applied to a landscape.',
    whenToUse: ['A landscape needs a different material assignment.'],
    whenNotToUse: ['The material should be configured with layer blends.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath, materialPath: P.materialPath },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    dispatchAction: 'set_landscape_material', dispatchMode: 'action',
    exampleInput: { action: 'set_landscape_material', landscapeName: 'Landscape_1', materialPath: '/Game/Materials/M_Landscape' },
    exampleOutput: { success: true, message: 'Landscape material set' },
  }),
  buildRecord({
    id: 'build_environment.paint_landscape', action: 'paint_landscape', family: F,
    summary: 'Paint a landscape layer at a location.',
    whenToUse: WU, whenNotToUse: ['The landscape layer weight should be set via raw data.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      layerName: P.layerName, location: P.location, radius: P.radius, strength: P.strength },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'paint_landscape', landscapeName: 'Landscape_1', layerName: 'Grass', location: { x: 0, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Landscape painted' },
  }),
  buildRecord({
    id: 'build_environment.paint_landscape_layer', action: 'paint_landscape_layer', family: F,
    summary: 'Paint a specific landscape layer with weight data.',
    whenToUse: WU, whenNotToUse: ['The landscape should be painted interactively.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      layerName: P.layerName, layerInfoPath: P.layerInfoPath },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'paint_landscape_layer', landscapeName: 'Landscape_1', layerName: 'Grass' },
    exampleOutput: { success: true, message: 'Landscape layer painted' },
  }),
  buildRecord({
    id: 'build_environment.import_heightmap', action: 'import_heightmap', family: F,
    summary: 'Import a heightmap file into a landscape.',
    whenToUse: ['A heightmap file must be imported to create or update a landscape.'],
    whenNotToUse: ['The heightmap should be generated procedurally.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      landscapeActorPath: P.landscapeActorPath, path: P.path, heightmapPath: { type: 'string', description: 'Heightmap file path.' } },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    exampleInput: { action: 'import_heightmap', landscapeName: 'Landscape_1', path: '/Game/Heightmaps/terrain.raw' },
    exampleOutput: { success: true, message: 'Heightmap imported' },
  }),
  buildRecord({
    id: 'build_environment.export_heightmap', action: 'export_heightmap', family: F,
    summary: 'Export a landscape heightmap to a file.',
    whenToUse: ['A landscape heightmap must be exported for external editing.'],
    whenNotToUse: ['The heightmap should be modified in the editor.'],
    inputProps: { outputPath: P.outputPath, action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      landscapeActorPath: P.landscapeActorPath, path: P.path },
    required: ['action'],
    effect: 'read', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'export_heightmap', landscapeName: 'Landscape_1', path: '/Game/Heightmaps/export.raw' },
    exampleOutput: { success: true, message: 'Heightmap exported' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_layer_info', action: 'create_landscape_layer_info', family: F,
    summary: 'Create a landscape layer info asset.',
    whenToUse: ['A new landscape layer info asset is needed for painting.'],
    whenNotToUse: ['An existing layer info asset should be reused.'],
    inputProps: { hardness: P.hardness, noWeightBlend: P.noWeightBlend, action: P.action, name: P.name, path: P.path, layerName: P.layerName, physicalMaterialPath: P.physicalMaterialPath },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_landscape_layer_info', name: 'LI_Grass', path: '/Game/Landscape' },
    exampleOutput: { success: true, message: 'Layer info created' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_material', action: 'configure_landscape_material', family: F,
    summary: 'Configure a landscape material with layer blends.',
    whenToUse: ['A landscape material needs layer blend configuration.'],
    whenNotToUse: ['A simple material assignment is sufficient.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      landscapeActorPath: P.landscapeActorPath, materialPath: P.materialPath, layerInfoPath: P.layerInfoPath },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_material', landscapeName: 'Landscape_1', materialPath: '/Game/M_Landscape' },
    exampleOutput: { success: true, message: 'Landscape material configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_splines', action: 'configure_landscape_splines', family: F,
    summary: 'Configure landscape splines on a target landscape.',
    whenToUse: ['Landscape splines need to be added or modified.'],
    whenNotToUse: ['Standalone spline actors should be used instead.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      landscapeActorPath: P.landscapeActorPath, points: P.points },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_splines', landscapeName: 'Landscape_1' },
    exampleOutput: { success: true, message: 'Landscape splines configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_lod', action: 'configure_landscape_lod', family: F,
    summary: 'Configure LOD settings for a landscape.',
    whenToUse: ['Landscape LOD distance or screen-size must be tuned.'],
    whenNotToUse: ['LODs should be generated rather than configured.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath,
      path: P.path, settings: P.settings },
    required: ['action'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_lod', landscapeName: 'Landscape_1' },
    exampleOutput: { success: true, message: 'Landscape LOD configured' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_streaming_proxy', action: 'create_landscape_streaming_proxy', family: F,
    summary: 'Create a landscape streaming proxy for World Partition.',
    whenToUse: ['A landscape streaming proxy is needed for World Partition tiles.'],
    whenNotToUse: ['The level does not use World Partition.'],
    inputProps: { action: P.action, landscapeName: P.landscapeName, landscapePath: P.landscapePath },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    exampleInput: { action: 'create_landscape_streaming_proxy', landscapeName: 'Landscape_1' },
    exampleOutput: { success: true, message: 'Streaming proxy created' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_grass_type', action: 'create_landscape_grass_type', family: F,
    summary: 'Create a landscape grass type asset.',
    whenToUse: ['A grass type asset is needed for landscape grass rendering.'],
    whenNotToUse: ['Foliage instances should be placed manually.'],
    inputProps: { action: P.action, name: P.name, meshPath: P.meshPath, staticMesh: P.staticMesh, path: P.path },
    required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'create_landscape_grass_type', dispatchMode: 'action',
    exampleInput: { action: 'create_landscape_grass_type', name: 'GT_Grass', meshPath: '/Game/Meshes/SM_Grass' },
    exampleOutput: { success: true, message: 'Grass type created' },
  }),
  buildRecord({
    id: 'build_environment.generate_lods', action: 'generate_lods', family: F,
    summary: 'Generate LODs for landscape or foliage assets.',
    whenToUse: ['LODs must be generated for one or more assets.'],
    whenNotToUse: ['LODs have already been generated.'],
    inputProps: { action: P.action, assetPaths: P.assetPaths, assets: P.assets, path: P.path, numLODs: P.numLODs },
    required: ['action'],
    effect: 'write', latency: 'long-running', resources: 'high',
    behavior: { longRunning: true },
    exampleInput: { action: 'generate_lods', assetPaths: ['/Game/Meshes/SM_Rock'], numLODs: 3 },
    exampleOutput: { success: true, message: 'LODs generated' },
  }),
];
