/**
 * Shared JSON Schema property fragments for build_environment records.
 *
 * Each property is a Draft-2020-12 schema fragment. Records reference these
 * via the P map so input schemas declare only the params the implementation
 * body actually consumes - never the full parent-tool union.
 */
import type { JsonObject } from '../../index.js';

const str = (d: string): JsonObject => ({ type: 'string', description: d });
const num = (d: string): JsonObject => ({ type: 'number', description: d });
const int = (d: string): JsonObject => ({ type: 'integer', description: d });
const bool = (d: string): JsonObject => ({ type: 'boolean', description: d });
const arr = (d: string, item: JsonObject): JsonObject => ({ type: 'array', items: item, description: d });
const vec3 = (d: string): JsonObject => ({
  type: 'object', description: d,
  properties: { x: num('X'), y: num('Y'), z: num('Z') },
  additionalProperties: false,
});
const rot = (d: string): JsonObject => ({
  type: 'object', description: d,
  properties: { pitch: num('Pitch'), yaw: num('Yaw'), roll: num('Roll') },
  additionalProperties: false,
});

export const P = {
  action: str('The build_environment action to execute.'),
  name: str('Name for the new actor, asset, or volume.'),
  landscapeName: str('Target landscape actor name.'),
  landscapePath: str('Canonical /Game landscape asset path.'),
  landscapeActorPath: str('Landscape actor path in the level.'),
  materialPath: str('Canonical /Game material asset path.'),
  material: str('Canonical /Game material asset path.'),
  meshPath: str('Canonical /Game static mesh asset path.'),
  staticMesh: str('Canonical /Game static mesh asset path.'),
  foliageType: str('Foliage type name or path.'),
  foliageTypePath: str('Canonical /Game foliage type asset path.'),
  actorName: str('Actor name in the current level.'),
  actorPath: str('Actor path in the level.'),
  targetActor: str('Target actor name for the operation.'),
  location: vec3('World-space location {x, y, z}.'),
  rotation: rot('Rotation {pitch, yaw, roll}.'),
  scale: vec3('Scale {x, y, z}.'),
  position: vec3('Position {x, y, z}.'),
  radius: num('Brush radius in world units.'),
  strength: num('Brush strength (0-1).'),
  falloff: num('Brush falloff (0-1).'),
  tool: str('Sculpt tool name (e.g. Raise, Lower, Smooth).'),
  layerName: str('Landscape layer name.'),
  operation: str('Heightmap operation: set, add, subtract, smooth.'),
  heightData: arr('Heightmap values.', num('Height value.')),
  minX: num('Region min X.'), minY: num('Region min Y.'),
  maxX: num('Region max X.'), maxY: num('Region max Y.'),
  updateNormals: bool('Recompute normals after modification.'),
  skipFlush: bool('Skip flushing rendering after the operation.'),
  sizeX: num('Landscape size in quads (X).'),
  sizeY: num('Landscape size in quads (Y).'),
  sectionSize: num('Section size in quads.'),
  sectionsPerComponent: num('Sections per component.'),
  componentCount: vec3('Component count {x, y}.'),
  quadsPerSection: num('Quads per section.'),
  seed: int('Random seed for procedural generation.'),
  heightScale: num('Height scale multiplier.'),
  subdivisions: int('Mesh subdivision count.'),
  density: num('Foliage density.'),
  minScale: num('Minimum foliage scale.'),
  maxScale: num('Maximum foliage scale.'),
  cullDistance: num('Cull distance in world units.'),
  alignToNormal: bool('Align instance to surface normal.'),
  randomYaw: bool('Apply random yaw rotation.'),
  locations: arr('Instance locations.', vec3('Location.')),
  transforms: arr('Instance transforms.', {
    type: 'object', description: 'Transform with location, rotation, scale.',
    properties: { location: vec3('Location.'), rotation: rot('Rotation.'), scale: vec3('Scale.') },
    additionalProperties: false,
  }),
  removeAll: bool('Remove all foliage instances.'),
  quality: str('Lightmap bake quality (Preview, Medium, High, Production).'),
  filename: str('File name for snapshot export/import.'),
  path: str('Canonical /Game asset or directory path.'),
  numLODs: int('Number of LODs to generate.'),
  assetPaths: arr('Asset paths for LOD generation.', str('Asset path.')),
  assets: arr('Asset paths for LOD generation.', str('Asset path.')),
  names: arr('Actor names to delete.', str('Actor name.')),
  time: num('Time of day in hours (0-24).'),
  hour: num('Hour of day (0-23).'),
  intensity: num('Light intensity.'),
  skyLightIntensity: num('Sky light intensity.'),
  lightType: str('Light type string.'),
  lightClass: str('Light class string.'),
  cubemapPath: str('Canonical /Game cubemap asset path.'),
  directionalLightActorPath: str('Directional light actor path. As input, selects the light to snapshot; the first directional light in the level is used when omitted. As output, the resolved actor path.'),
  skyLightActorPath: str('Sky light actor path. As input, selects the light to snapshot; the first sky light in the level is used when omitted. As output, the resolved actor path.'),
  curvePath: str('Canonical /Game curve asset path.'),
  particleSystemPath: str('Canonical /Game particle system asset path.'),
  waterBodyName: str('Water body actor name.'),
  waveHeight: num('Wave height.'), waveLength: num('Wave length.'),
  amplitude: num('Wave amplitude.'), steepness: num('Wave steepness.'),
  speed: num('Animation or wave speed.'),
  direction: rot('Direction rotation.'),
  azimuth: num('Sun azimuth in degrees.'), elevation: num('Sun elevation in degrees.'),
  pointIndex: int('Spline point index.'),
  pointRotation: rot('Spline point rotation.'), pointScale: vec3('Spline point scale.'),
  pointType: str('Spline point type (Linear, Curve, Constant, etc.).'),
  arriveTangent: vec3('Arrive tangent.'), leaveTangent: vec3('Leave tangent.'),
  splineType: str('Spline point type.'),
  bClosedLoop: bool('Whether the spline is a closed loop.'),
  forwardAxis: str('Spline mesh forward axis (X, Y, Z).'),
  componentName: str('Component name.'),
  blueprintPath: str('Canonical /Game blueprint path.'),
  spacing: num('Mesh spacing along the spline.'),
  width: num('Spline width.'),
  alignToSpline: bool('Align meshes to spline direction.'),
  randomizeRotation: bool('Randomize mesh rotation.'),
  randomizeScale: bool('Randomize mesh scale.'),
  randomOffsetRange: num('Random offset range.'),
  settings: {
    type: 'object', description: 'Action-specific settings key-value pairs.',
    additionalProperties: true, 'x-unreal-reflection-boundary': true,
  } as JsonObject,
  region: {
    type: 'object', description: 'Rectangular region {minX, minY, maxX, maxY}.',
    properties: { minX: num('Min X.'), minY: num('Min Y.'), maxX: num('Max X.'), maxY: num('Max Y.') },
    additionalProperties: false,
  } as JsonObject,
  bounds: {
    type: 'object', description: 'Procedural foliage bounds {location, size}.',
    properties: { location: vec3('Bounds location.'), size: vec3('Bounds size.') },
    additionalProperties: false,
  } as JsonObject,
  foliageTypes: arr('Foliage type specs.', {
    type: 'object', description: 'Foliage type with mesh and density.',
    properties: { meshPath: str('Mesh path.'), density: num('Density.') },
    additionalProperties: false,
  }),
  points: arr('Spline points.', {
    type: 'object', description: 'Spline point with position and tangent.',
    properties: {
      position: vec3('Position.'), arriveTangent: vec3('Arrive tangent.'),
      leaveTangent: vec3('Leave tangent.'), rotation: rot('Rotation.'), scale: vec3('Scale.'),
    },
    additionalProperties: false,
  }),
  tileSize: num('Procedural foliage tile size.'),
  volumeName: str('Volume actor name.'),
  physicalMaterialPath: str('Canonical /Game physical material path.'),
  layerInfoPath: str('Canonical /Game landscape layer info asset path.'),
  renderTargetPath: str('Render target path string.'),
  lutPath: str('Canonical /Game LUT texture path.'),
  captureOffset: vec3('Capture offset.'),
  aperture: num('Camera aperture (f-stop).'),
  distance: num('Focus distance.'),
  blendWeight: num('Blend weight (0-1).'),
  screenPercentage: num('Screen percentage (0-100).'),
  amount: num('Effect amount.'), threshold: num('Effect threshold.'),
  minBrightness: num('Minimum brightness.'), maxBrightness: num('Maximum brightness.'),
  propertyName: str('Property name.'), propertyValue: str('Property value as string.'),
  enabled: bool('Whether the feature is enabled.'),
  method: str('Method string.'), materialIndex: int('Material index.'),
  compensationValue: num('Exposure compensation value.'),
  infiniteUnbound: bool('Whether the volume is infinite and unbound.'),
  collisionEnabled: bool('Whether collision is enabled.'),
  save: bool('Whether to save after the operation.'),
  propertyValueNumber: num('Numeric property value.'),
  outputPath: str('Filesystem path the heightmap is written to.'),
  count: int('Number of instances to generate when locations are derived from location+radius.'),
  hardness: num('Landscape layer hardness (0-1).'),
  noWeightBlend: bool('Disable weight blending for the landscape layer.'),
  channels: arr('Lighting channel indices (0, 1, or 2).', int('Lighting channel index.')),
  rotationRange: num('Random rotation range in degrees.'),
  useRandomOffset: bool('Apply a random offset to scattered meshes.'),
  initialPoints: arr('Initial spline points (alias of points).', {
    type: 'object', description: 'Spline point with a world location.',
    properties: { location: vec3('Point location.') },
    additionalProperties: false,
  }),
  success: bool('Whether the action succeeded.'),
  message: str('Human-readable result message.'),
};

export type PropertyMap = JsonObject;
