/**
 * Spline family records (22 actions).
 *
 * Grounded in spline-handlers.ts which dispatches to manage_splines bridge
 * actions. create_spline_actor, add_spline_point, remove_spline_point,
 * set_spline_point_position, set_spline_point_tangents,
 * set_spline_point_rotation, set_spline_point_scale, set_spline_type,
 * create_spline_mesh_component, set_spline_mesh_asset,
 * configure_spline_mesh_axis, set_spline_mesh_material,
 * scatter_meshes_along_spline, configure_mesh_spacing,
 * configure_mesh_randomization, create_road_spline, create_river_spline,
 * create_fence_spline, create_wall_spline, create_cable_spline,
 * create_pipe_spline, get_splines_info.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildRecord } from './helpers.js';
import { P } from './properties.js';

const F = 'spline';
const WU = ['A spline actor or spline mesh must be created or modified.'];

export const SPLINE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'build_environment.create_spline_actor', action: 'create_spline_actor', family: F,
    summary: 'Create a spline actor in the level.',
    whenToUse: WU, whenNotToUse: ['A static mesh path should be used instead.'],
    inputProps: { initialPoints: P.initialPoints, action: P.action, name: P.name, location: P.location, rotation: P.rotation, points: P.points, bClosedLoop: P.bClosedLoop },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_spline_actor', name: 'Spline_1', location: { x: 0, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Spline actor created' },
  }),
  buildRecord({
    id: 'build_environment.add_spline_point', action: 'add_spline_point', family: F,
    summary: 'Add a point to an existing spline.',
    whenToUse: WU, whenNotToUse: ['The spline should be recreated with all points.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, position: P.position,
      arriveTangent: P.arriveTangent, leaveTangent: P.leaveTangent, pointType: P.pointType },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'add_spline_point', actorName: 'Spline_1', position: { x: 100, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Spline point added' },
  }),
  buildRecord({
    id: 'build_environment.remove_spline_point', action: 'remove_spline_point', family: F,
    summary: 'Remove a point from a spline by index.',
    whenToUse: WU, whenNotToUse: ['The spline should be recreated without the point.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex },
    required: ['action'], effect: 'destructive', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'remove_spline_point', actorName: 'Spline_1', pointIndex: 2 },
    exampleOutput: { success: true, message: 'Spline point removed' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_point_position', action: 'set_spline_point_position', family: F,
    summary: 'Set the position of a spline point by index.',
    whenToUse: WU, whenNotToUse: ['The point should be moved interactively.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex, position: P.position },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_point_position', actorName: 'Spline_1', pointIndex: 0, position: { x: 0, y: 0, z: 100 } },
    exampleOutput: { success: true, message: 'Spline point position set' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_point_tangents', action: 'set_spline_point_tangents', family: F,
    summary: 'Set the arrive and leave tangents of a spline point.',
    whenToUse: WU, whenNotToUse: ['Default tangents are sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex,
      arriveTangent: P.arriveTangent, leaveTangent: P.leaveTangent },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_point_tangents', actorName: 'Spline_1', pointIndex: 0, arriveTangent: { x: 50, y: 0, z: 0 } },
    exampleOutput: { success: true, message: 'Tangents set' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_point_rotation', action: 'set_spline_point_rotation', family: F,
    summary: 'Set the rotation of a spline point.',
    whenToUse: WU, whenNotToUse: ['Default rotation is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex, pointRotation: P.pointRotation },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_point_rotation', actorName: 'Spline_1', pointIndex: 0, pointRotation: { pitch: 0, yaw: 45, roll: 0 } },
    exampleOutput: { success: true, message: 'Rotation set' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_point_scale', action: 'set_spline_point_scale', family: F,
    summary: 'Set the scale of a spline point.',
    whenToUse: WU, whenNotToUse: ['Default scale is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex, pointScale: P.pointScale },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_point_scale', actorName: 'Spline_1', pointIndex: 0, pointScale: { x: 1, y: 1, z: 1 } },
    exampleOutput: { success: true, message: 'Scale set' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_type', action: 'set_spline_type', family: F,
    summary: 'Set the spline point type (Linear, Curve, Constant, etc.).',
    whenToUse: WU, whenNotToUse: ['Default curve type is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, pointIndex: P.pointIndex, splineType: P.splineType },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_type', actorName: 'Spline_1', pointIndex: 0, splineType: 'Curve' },
    exampleOutput: { success: true, message: 'Spline type set' },
  }),
  buildRecord({
    id: 'build_environment.create_spline_mesh_component', action: 'create_spline_mesh_component', family: F,
    summary: 'Create a spline mesh component on an actor.',
    whenToUse: WU, whenNotToUse: ['A static mesh should be used instead.'],
    inputProps: { blueprintPath: P.blueprintPath, save: P.save, action: P.action, actorName: P.actorName, actorPath: P.actorPath, componentName: P.componentName, meshPath: P.meshPath, forwardAxis: P.forwardAxis },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_spline_mesh_component', actorName: 'Spline_1', meshPath: '/Game/Meshes/SM_Road' },
    exampleOutput: { success: true, message: 'Spline mesh component created' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_mesh_asset', action: 'set_spline_mesh_asset', family: F,
    summary: 'Set the static mesh asset for a spline mesh component.',
    whenToUse: WU, whenNotToUse: ['The mesh should be recreated.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, componentName: P.componentName, meshPath: P.meshPath },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_mesh_asset', actorName: 'Spline_1', meshPath: '/Game/Meshes/SM_Road_v2' },
    exampleOutput: { success: true, message: 'Mesh asset set' },
  }),
  buildRecord({
    id: 'build_environment.configure_spline_mesh_axis', action: 'configure_spline_mesh_axis', family: F,
    summary: 'Set the forward axis of a spline mesh component.',
    whenToUse: WU, whenNotToUse: ['Default axis is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, componentName: P.componentName, forwardAxis: P.forwardAxis },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_spline_mesh_axis', actorName: 'Spline_1', forwardAxis: 'X' },
    exampleOutput: { success: true, message: 'Mesh axis configured' },
  }),
  buildRecord({
    id: 'build_environment.set_spline_mesh_material', action: 'set_spline_mesh_material', family: F,
    summary: 'Set the material on a spline mesh component.',
    whenToUse: WU, whenNotToUse: ['Default material is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, componentName: P.componentName, materialPath: P.materialPath, materialIndex: P.materialIndex },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'set_spline_mesh_material', actorName: 'Spline_1', materialPath: '/Game/Materials/M_Road' },
    exampleOutput: { success: true, message: 'Mesh material set' },
  }),
  buildRecord({
    id: 'build_environment.scatter_meshes_along_spline', action: 'scatter_meshes_along_spline', family: F,
    summary: 'Scatter static meshes along a spline path.',
    whenToUse: WU, whenNotToUse: ['Manual placement is sufficient.'],
    inputProps: { action: P.action, actorName: P.actorName, actorPath: P.actorPath, meshPath: P.meshPath,
      spacing: P.spacing, alignToSpline: P.alignToSpline, randomizeRotation: P.randomizeRotation, randomizeScale: P.randomizeScale },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'medium',
    exampleInput: { action: 'scatter_meshes_along_spline', actorName: 'Spline_1', meshPath: '/Game/Meshes/SM_Tree', spacing: 200 },
    exampleOutput: { success: true, message: 'Meshes scattered' },
  }),
  buildRecord({
    id: 'build_environment.configure_mesh_spacing', action: 'configure_mesh_spacing', family: F,
    summary: 'Configure mesh spacing along a spline.',
    whenToUse: WU, whenNotToUse: ['Default spacing is sufficient.'],
    inputProps: { useRandomOffset: P.useRandomOffset, action: P.action, actorName: P.actorName, actorPath: P.actorPath, spacing: P.spacing },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_mesh_spacing', actorName: 'Spline_1', spacing: 150 },
    exampleOutput: { success: true, message: 'Mesh spacing configured' },
  }),
  buildRecord({
    id: 'build_environment.configure_mesh_randomization', action: 'configure_mesh_randomization', family: F,
    summary: 'Configure randomization for meshes scattered along a spline.',
    whenToUse: WU, whenNotToUse: ['Uniform placement is desired.'],
    inputProps: { rotationRange: P.rotationRange, action: P.action, actorName: P.actorName, actorPath: P.actorPath,
      randomizeRotation: P.randomizeRotation, randomizeScale: P.randomizeScale, randomOffsetRange: P.randomOffsetRange },
    required: ['action'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_mesh_randomization', actorName: 'Spline_1', randomizeRotation: true },
    exampleOutput: { success: true, message: 'Randomization configured' },
  }),
  buildRecord({
    id: 'build_environment.create_road_spline', action: 'create_road_spline', family: F,
    summary: 'Create a road spline with mesh and width.',
    whenToUse: WU, whenNotToUse: ['A generic spline should be used.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, materialPath: P.materialPath, width: P.width, points: P.points, closedLoop: P.closedLoop },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_road_spline', name: 'Road_1', meshPath: '/Game/Meshes/SM_Road', materialPath: '/Game/Materials/M_Road', width: 500, closedLoop: true },
    exampleOutput: { success: true, message: 'Road spline created' },
  }),
  buildRecord({
    id: 'build_environment.create_river_spline', action: 'create_river_spline', family: F,
    summary: 'Create a river spline with mesh and width.',
    whenToUse: WU, whenNotToUse: ['A water body actor should be used instead.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, width: P.width, points: P.points },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_river_spline', name: 'River_1', width: 800 },
    exampleOutput: { success: true, message: 'River spline created' },
  }),
  buildRecord({
    id: 'build_environment.create_fence_spline', action: 'create_fence_spline', family: F,
    summary: 'Create a fence spline with mesh and post spacing.',
    whenToUse: WU, whenNotToUse: ['Manual fence placement is sufficient.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, spacing: P.spacing, points: P.points },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_fence_spline', name: 'Fence_1', meshPath: '/Game/Meshes/SM_FencePost', spacing: 200 },
    exampleOutput: { success: true, message: 'Fence spline created' },
  }),
  buildRecord({
    id: 'build_environment.create_wall_spline', action: 'create_wall_spline', family: F,
    summary: 'Create a wall spline with mesh and height.',
    whenToUse: WU, whenNotToUse: ['Manual wall placement is sufficient.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, width: P.width, points: P.points },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_wall_spline', name: 'Wall_1', meshPath: '/Game/Meshes/SM_Wall', width: 300 },
    exampleOutput: { success: true, message: 'Wall spline created' },
  }),
  buildRecord({
    id: 'build_environment.create_cable_spline', action: 'create_cable_spline', family: F,
    summary: 'Create a cable spline between two points.',
    whenToUse: WU, whenNotToUse: ['A physics cable component should be used.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, points: P.points },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_cable_spline', name: 'Cable_1' },
    exampleOutput: { success: true, message: 'Cable spline created' },
  }),
  buildRecord({
    id: 'build_environment.create_pipe_spline', action: 'create_pipe_spline', family: F,
    summary: 'Create a pipe spline with mesh and radius.',
    whenToUse: WU, whenNotToUse: ['Manual pipe placement is sufficient.'],
    inputProps: { action: P.action, name: P.name, location: P.location, meshPath: P.meshPath, width: P.width, points: P.points },
    required: ['action'], effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_pipe_spline', name: 'Pipe_1', meshPath: '/Game/Meshes/SM_Pipe', width: 50 },
    exampleOutput: { success: true, message: 'Pipe spline created' },
  }),
  buildRecord({
    id: 'build_environment.get_splines_info', action: 'get_splines_info', family: F,
    summary: 'Retrieve spline actor information in the level.',
    whenToUse: ['Spline actors must be enumerated.'],
    whenNotToUse: ['A specific spline path is already known.'],
    inputProps: { action: P.action, actorName: P.actorName },
    required: ['action'],
    outputProps: { splines: { type: 'array', description: 'Spline info.', items: { type: 'object', description: 'Spline actor info.', additionalProperties: true, 'x-unreal-reflection-boundary': true } } },
    outputRequired: ['splines'],
    effect: 'read', latency: 'instant', resources: 'low',
    exampleInput: { action: 'get_splines_info' },
    exampleOutput: { success: true, splines: [] },
  }),
];
