// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_AnimationPhysics : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("animation_physics"); }
	FString GetDescription() const override { return TEXT("Author animation and physics assets: Animation Blueprints, blend spaces, montages, Control Rig/IK, skeletons, sockets, physics assets, cloth, ragdolls, and vehicles."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Bool(TEXT("activate"), TEXT("Whether to activate the target."));
			Schema.String(TEXT("actorName"), TEXT("Target actor name in the current level."));
			Schema.Bool(TEXT("addMissing"), TEXT("Whether to add the morph target when the component does not already carry it."));
			Schema.String(TEXT("additiveAnimType"), TEXT("String parameter."));
			Schema.Number(TEXT("angularDamping"), TEXT("Angular damping value."));
			Schema.String(TEXT("animationPath"), TEXT("Canonical /Game Animation asset path."));
			Schema.Array(TEXT("animations"), TEXT("Animation asset paths to play in this state; one Sequence Player is created per entry and the first drives the state Result pose. Without it the state is created empty and the character holds its reference pose."), TEXT("string"));
			Schema.Array(TEXT("artifacts"), TEXT("Canonical /Game asset paths to delete during cleanup."), TEXT("string"));
			Schema.Number(TEXT("assetLodIndex"), TEXT("Clothing asset LOD to use (default 0)."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.Array(TEXT("assets"), TEXT("Canonical /Game animation asset paths to retarget."), TEXT("string"));
			Schema.Bool(TEXT("assignToMesh"), TEXT("Assign the new asset to the skeletal mesh."));
			Schema.String(TEXT("attachBoneName"), TEXT("Bone the socket attaches to."));
			Schema.Bool(TEXT("automaticRule"), TEXT("Fire the transition when the source state's sequence player reaches the end of its animation instead of testing a condition. Left alone when omitted."));
			Schema.String(TEXT("axis"), TEXT("Mirror or blend axis (X, Y, Z)."));
			Schema.String(TEXT("axisName"), TEXT("Axis name."));
			Schema.Number(TEXT("basePoseFrame"), TEXT("Frame used as the additive base pose."));
			Schema.String(TEXT("basePoseType"), TEXT("Additive base pose type (RefPose, AnimScaled, AnimFrame)."));
			Schema.Bool(TEXT("bidirectional"), TEXT("Whether the transition also applies from toState back to fromState. Left alone when omitted."));
			Schema.Number(TEXT("blendTime"), TEXT("Blend duration in seconds."));
			Schema.String(TEXT("blendType"), TEXT("Blend node type (TwoWayBlend, BlendListByBool, BlendListByInt)."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.String(TEXT("bodyA"), TEXT("First physics body."));
			Schema.String(TEXT("bodyB"), TEXT("Second physics body."));
			Schema.Bool(TEXT("bodyForAll"), TEXT("Create a body for every bone regardless of size."));
			Schema.String(TEXT("bodyType"), TEXT("Physics body primitive type (Sphere, Box, Capsule)."));
			Schema.String(TEXT("boneName"), TEXT("Target bone name."));
			Schema.ArrayOfObjects(TEXT("boneTracks"), TEXT("Bone tracks to key: [{ boneName, frames: [{ frame, rotationDelta?: {pitch,yaw,roll}, rotation?: {pitch,yaw,roll}|{x,y,z,w}, location?: {x,y,z}, scale?: {x,y,z} }] }]. Channels left out keep the reference pose of that bone, so a rotation-only track poses without collapsing the skeleton. Prefer rotationDelta, which bends the bone relative to its rest orientation; plain rotation replaces the local rotation outright and needs the rest orientation to already be known."));
			Schema.String(TEXT("cacheName"), TEXT("Cached pose name."));
			Schema.Array(TEXT("center"), TEXT("Physics body centre offset relative to its bone as [x, y, z]."), TEXT("number"));
			Schema.String(TEXT("clothAssetName"), TEXT("Name of a clothing asset already registered on the mesh."));
			Schema.String(TEXT("clothAssetPath"), TEXT("Clothing asset to load and register before binding."));
			Schema.StringEnum(TEXT("clothOp"), { TEXT("bind"), TEXT("assign") }, TEXT("Which bind cloth to skeletal mesh variant to run; omit for 'bind'."));
			Schema.Bool(TEXT("collisionEnabled"), TEXT("Whether collision is enabled."));
			Schema.Bool(TEXT("compileReferencers"), TEXT("Whether referring assets are compiled."));
			Schema.String(TEXT("conditionComparison"), TEXT("How conditionVariable is tested: greater (default), less, greater_equal, less_equal for a numeric variable; true or false for a bool."));
			Schema.Number(TEXT("conditionValue"), TEXT("Right-hand value for a numeric conditionComparison (default 0). Ignored for true/false."));
			Schema.String(TEXT("conditionVariable"), TEXT("Animation Blueprint variable the transition rule tests, e.g. Speed or bFalling. Without it the rule graph is left unconnected, which reads as false forever and the state machine never leaves its entry state."));
			Schema.Bool(TEXT("connectToOutput"), TEXT("Wire the blend node into the AnimGraph output pose (default true)."));
			Schema.String(TEXT("constraintName"), TEXT("Name of the created physics constraint."));
			Schema.Bool(TEXT("createConstraints"), TEXT("Create joint constraints between bodies."));
			Schema.Number(TEXT("crossfadeDuration"), TEXT("Transition blend duration in seconds. blendTime is accepted as an alias."));
			Schema.String(TEXT("curveName"), TEXT("Animation curve name."));
			Schema.ArrayOfObjects(TEXT("deltas"), TEXT("Per-vertex morph target position deltas."));
			Schema.Number(TEXT("dragCoefficient"), TEXT("Drag coefficient."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_blend_node"), TEXT("add_cached_pose"), TEXT("add_slot_node"), TEXT("create_state_machine"), TEXT("add_state_machine"), TEXT("add_state"), TEXT("add_transition"), TEXT("set_transition_rules"), TEXT("delete_transition"), TEXT("create_blend_tree"), TEXT("add_bone"), TEXT("rename_bone"), TEXT("set_bone_parent"), TEXT("set_bone_transform"), TEXT("create_virtual_bone"), TEXT("add_bone_track"), TEXT("set_bone_key"), TEXT("set_curve_key"), TEXT("add_notify"), TEXT("add_notify_state"), TEXT("add_sync_marker"), TEXT("set_additive_settings"), TEXT("set_root_motion_settings"), TEXT("set_sequence_length"), TEXT("add_aim_offset_sample"), TEXT("add_layered_blend_per_bone"), TEXT("set_value"), TEXT("add_montage_notify"), TEXT("add_montage_section"), TEXT("add_montage_slot"), TEXT("link_sections"), TEXT("set_blend_in"), TEXT("set_blend_out"), TEXT("set_section_timing"), TEXT("add_sample"), TEXT("set_axis_settings"), TEXT("set_interpolation_settings"), TEXT("rebuild"), TEXT("auto"), TEXT("copy"), TEXT("mirror"), TEXT("normalize"), TEXT("prune"), TEXT("set"), TEXT("create"), TEXT("add_body"), TEXT("configure_body"), TEXT("modify_body"), TEXT("add_constraint"), TEXT("set_constraint"), TEXT("configure_constraint_limits"), TEXT("assign"), TEXT("set_deltas") }, TEXT("Which configure anim graph node variant to run."));
			Schema.StringEnum(TEXT("element"), { TEXT("bone"), TEXT("socket"), TEXT("physics_body") }, TEXT("Which remove skeleton element variant to run."));
			Schema.Bool(TEXT("enableRootMotion"), TEXT("Boolean parameter."));
			Schema.Number(TEXT("endFrame"), TEXT("Last frame of the notify state range."));
			Schema.Bool(TEXT("forceRootLock"), TEXT("Whether root motion is force-locked to the reference pose."));
			Schema.Number(TEXT("frame"), TEXT("Frame index."));
			Schema.Number(TEXT("frameRate"), TEXT("Frames per second."));
			Schema.String(TEXT("fromSection"), TEXT("Source montage section."));
			Schema.String(TEXT("fromState"), TEXT("Source state name."));
			Schema.String(TEXT("geomType"), TEXT("Body primitive: Sphyl, Box, Sphere, TaperedCapsule, MultiConvexHull or SingleConvexHull."));
			Schema.StringEnum(TEXT("info"), { TEXT("skeleton"), TEXT("bones"), TEXT("sockets"), TEXT("virtual_bones"), TEXT("bone_transform"), TEXT("morph_targets"), TEXT("physics_asset"), TEXT("physics_bodies") }, TEXT("Which get skeleton info variant to run; omit for 'skeleton'."));
			Schema.String(TEXT("interpolationType"), TEXT("Interpolation mode."));
			Schema.StringEnum(TEXT("kind"), { TEXT("asset"), TEXT("sequence"), TEXT("montage"), TEXT("blend_space"), TEXT("blend_space_1d"), TEXT("blend_space_2d"), TEXT("aim_offset"), TEXT("pose_library"), TEXT("procedural"), TEXT("setup"), TEXT("rig"), TEXT("retargeter") }, TEXT("Which create animation asset variant to run; omit for 'asset'."));
			Schema.ArrayOfObjects(TEXT("layerSetup"), TEXT("Layered blend-per-bone branch filter descriptors."));
			Schema.Number(TEXT("length"), TEXT("Sequence length."));
			Schema.FreeformObject(TEXT("limits"), TEXT("Key-value property map."));
			Schema.Number(TEXT("linearDamping"), TEXT("Linear damping value."));
			Schema.Array(TEXT("location"), TEXT("World or relative location as [x, y, z]."), TEXT("number"));
			Schema.Number(TEXT("lodIndex"), TEXT("Skeletal mesh LOD index."));
			Schema.String(TEXT("machineName"), TEXT("State machine name."));
			Schema.String(TEXT("markerName"), TEXT("Animation sync marker name."));
			Schema.Number(TEXT("mass"), TEXT("Mass value."));
			Schema.Number(TEXT("maxValue"), TEXT("Maximum numeric value."));
			Schema.Number(TEXT("meshLodIndex"), TEXT("Mesh LOD to bind (default 0)."));
			Schema.String(TEXT("meshPath"), TEXT("Canonical /Game mesh asset path."));
			Schema.Number(TEXT("minBoneSize"), TEXT("Bones smaller than this get no body."));
			Schema.Number(TEXT("minValue"), TEXT("Minimum numeric value."));
			Schema.String(TEXT("montagePath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("morphTargetName"), TEXT("Morph target name."));
			Schema.String(TEXT("morphTargetPath"), TEXT("Canonical /Game asset the morph targets are imported from."));
			Schema.String(TEXT("name"), TEXT("Asset name (alternative to outputPath)."));
			Schema.String(TEXT("newBoneName"), TEXT("Replacement bone name."));
			Schema.String(TEXT("nodeName"), TEXT("Graph node name."));
			Schema.String(TEXT("notifyClass"), TEXT("AnimNotify (or AnimNotifyState) class name; prefixed with AnimNotify_/AnimNotifyState_ automatically when missing."));
			Schema.String(TEXT("notifyName"), TEXT("Animation notify name."));
			Schema.Number(TEXT("numFrames"), TEXT("Numeric parameter."));
			Schema.String(TEXT("outputPath"), TEXT("Canonical /Game path for the SkeletalMesh this writes."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite an existing asset with the same name."));
			Schema.String(TEXT("parentBoneName"), TEXT("Parent bone name."));
			Schema.String(TEXT("parentClass"), TEXT("String parameter."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.String(TEXT("physicsAssetName"), TEXT("Name of the generated Physics Asset."));
			Schema.String(TEXT("physicsAssetPath"), TEXT("Canonical /Game PhysicsAsset path."));
			Schema.Number(TEXT("pitch"), TEXT("Aim offset pitch in degrees."));
			Schema.Number(TEXT("playRate"), TEXT("Playback rate."));
			Schema.Number(TEXT("priorityOrder"), TEXT("Evaluation order when several transitions out of one state can fire on the same frame; the lowest wins."));
			Schema.String(TEXT("profileName"), TEXT("Skin weight profile name."));
			Schema.String(TEXT("propertyName"), TEXT("Property name."));
			Schema.Number(TEXT("radius"), TEXT("Radius in world units."));
			Schema.StringEnum(TEXT("ragdoll"), { TEXT("setup"), TEXT("activate") }, TEXT("Which setup ragdoll variant to run; omit for 'setup'."));
			Schema.Bool(TEXT("rebuildBlendParameters"), TEXT("Whether blend parameters are rebuilt."));
			Schema.Array(TEXT("relativeLocation"), TEXT("Socket location relative to its attach bone as [x, y, z]."), TEXT("number"));
			Schema.Array(TEXT("relativeRotation"), TEXT("Socket rotation relative to its attach bone as [pitch, yaw, roll]."), TEXT("number"));
			Schema.Array(TEXT("relativeScale"), TEXT("Socket scale relative to its attach bone as [x, y, z]."), TEXT("number"));
			Schema.Bool(TEXT("removeChildren"), TEXT("Whether child bones are removed with the target bone."));
			Schema.String(TEXT("retargeterPath"), TEXT("An existing IK Retargeter to bake through. Omit to auto-build one by characterizing both skeletons and mapping their chains."));
			Schema.String(TEXT("rootBoneName"), TEXT("Root bone name for the created skeleton."));
			Schema.String(TEXT("rootMotionRootLock"), TEXT("String parameter."));
			Schema.Array(TEXT("rotation"), TEXT("Rotation as [pitch, yaw, roll] in degrees."), TEXT("number"));
			Schema.Number(TEXT("sampleValue"), TEXT("Blend sample coordinate."));
			Schema.Bool(TEXT("save"), TEXT("Persist the created/modified asset to disk."));
			Schema.String(TEXT("savePath"), TEXT("Canonical /Game directory for generated assets."));
			Schema.AnyValue(TEXT("scale"), TEXT("Uniform scale factor, or non-uniform scale as [x, y, z]."));
			Schema.Number(TEXT("sectionIndex"), TEXT("Mesh section to bind (default 0)."));
			Schema.String(TEXT("sectionName"), TEXT("Montage section name."));
			Schema.Bool(TEXT("simulatePhysics"), TEXT("Whether physics simulation is enabled."));
			Schema.String(TEXT("skeletalMeshPath"), TEXT("Canonical /Game SkeletalMesh asset path."));
			Schema.String(TEXT("skeletonPath"), TEXT("Canonical /Game Skeleton asset path."));
			Schema.String(TEXT("slotName"), TEXT("Slot name."));
			Schema.String(TEXT("socketName"), TEXT("Target socket name."));
			Schema.StringEnum(TEXT("socketOp"), { TEXT("configure"), TEXT("add"), TEXT("create"), TEXT("modify") }, TEXT("Which configure socket variant to run; omit for 'configure'."));
			Schema.String(TEXT("sourceBoneName"), TEXT("Source bone name."));
			Schema.String(TEXT("sourceChain"), TEXT("Source retarget chain."));
			Schema.String(TEXT("sourceIKRigPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("sourceMesh"), TEXT("SkeletalMesh giving the source proportions. Defaults to the skeleton preview mesh, then any mesh in the project built on it."));
			Schema.String(TEXT("sourceMeshPath"), TEXT("Canonical /Game mesh asset path."));
			Schema.String(TEXT("sourceSkeletalMesh"), TEXT("An already-skinned mesh on the same skeleton to copy weights from, such as the body the garment is worn over. Beats computing weights fresh wherever the garment hugs the body. Falls back to smooth binding when omitted."));
			Schema.String(TEXT("sourceSkeleton"), TEXT("Canonical /Game Skeleton asset path."));
			Schema.Number(TEXT("startFrame"), TEXT("First frame of the notify state range."));
			Schema.Number(TEXT("startTime"), TEXT("Start time in seconds."));
			Schema.String(TEXT("stateMachineName"), TEXT("Target state machine name inside the Animation Blueprint."));
			Schema.String(TEXT("stateName"), TEXT("State name."));
			Schema.String(TEXT("staticMeshPath"), TEXT("StaticMesh to skin, e.g. a coat downloaded as a rigid mesh."));
			Schema.String(TEXT("suffix"), TEXT("Suffix appended to each retargeted asset name."));
			Schema.String(TEXT("targetBoneName"), TEXT("Target bone name."));
			Schema.String(TEXT("targetChain"), TEXT("Target retarget chain."));
			Schema.String(TEXT("targetIKRigPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("targetMesh"), TEXT("SkeletalMesh to retarget onto. Defaults the same way as sourceMesh."));
			Schema.String(TEXT("targetMeshPath"), TEXT("Canonical /Game skeletal mesh receiving the copied weights."));
			Schema.String(TEXT("targetSkeleton"), TEXT("Canonical /Game Skeleton asset path."));
			Schema.Number(TEXT("threshold"), TEXT("Numeric threshold."));
			Schema.Number(TEXT("time"), TEXT("Time in seconds."));
			Schema.String(TEXT("toSection"), TEXT("Target montage section."));
			Schema.String(TEXT("toState"), TEXT("Target state name."));
			Schema.Number(TEXT("trackIndex"), TEXT("Notify track index within the animation sequence."));
			Schema.String(TEXT("treeName"), TEXT("Comment/name for the blend node (alias of name)."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value (any type)."));
			Schema.String(TEXT("vehicleType"), TEXT("Vehicle type."));
			Schema.ArrayOfObjects(TEXT("weights"), TEXT("Per-vertex skin weight descriptors with bone influences."));
			Schema.Number(TEXT("yaw"), TEXT("Aim offset yaw in degrees."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_animation_blueprint"), TEXT("create_animation_asset"), TEXT("edit_anim_graph"), TEXT("edit_animation"), TEXT("create_control_rig"), TEXT("setup_ik"), TEXT("edit_montage"), TEXT("play_montage"), TEXT("setup_ragdoll"), TEXT("configure_vehicle"), TEXT("setup_physics_simulation"), TEXT("edit_blend_space"), TEXT("setup_retargeting"), TEXT("skin_mesh_to_skeleton"), TEXT("configure_anim_graph_node"), TEXT("set_retarget_chain_mapping"), TEXT("get_animation_info"), TEXT("cleanup"), TEXT("create_skeleton"), TEXT("edit_skeleton"), TEXT("remove_skeleton_element"), TEXT("configure_socket"), TEXT("edit_skin_weights"), TEXT("edit_physics_asset"), TEXT("bind_cloth_to_skeletal_mesh"), TEXT("edit_morph_target"), TEXT("import_morph_targets"), TEXT("get_skeleton_info") }, TEXT("Action to invoke on animation_physics."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedGameplay_AnimCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_AnimationPhysics());

}
