// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageAudio : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_audio"); }
	FString GetDescription() const override { return TEXT("Play/stop sounds, add audio components, configure mixes, attenuation, spatial audio, and author Sound Cues/MetaSounds."); }
	FString GetCategory() const override { return TEXT("utility"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("actorName"));
			Schema.String(TEXT("analysisType"), TEXT("analysisType"));
			Schema.String(TEXT("assetPath"), TEXT("assetPath"));
			Schema.String(TEXT("attachPointName"), TEXT("attachPointName"));
			Schema.String(TEXT("attenuationPath"), TEXT("attenuationPath"));
			Schema.String(TEXT("attenuationShape"), TEXT("attenuationShape"));
			Schema.Bool(TEXT("autoPlay"), TEXT("autoPlay"));
			Schema.String(TEXT("componentName"), TEXT("componentName"));
			Schema.String(TEXT("concurrencyPath"), TEXT("concurrencyPath"));
			Schema.String(TEXT("defaultValue"), TEXT("defaultValue"));
			Schema.Number(TEXT("dopplerIntensity"), TEXT("dopplerIntensity"));
			Schema.String(TEXT("effectType"), TEXT("effectType"));
			Schema.Bool(TEXT("enable"), TEXT("enable"));
			Schema.String(TEXT("enableReverbSend"), TEXT("enableReverbSend"));
			Schema.Bool(TEXT("enabled"), TEXT("enabled"));
			Schema.Number(TEXT("fadeInTime"), TEXT("fadeInTime"));
			Schema.Number(TEXT("fadeOutTime"), TEXT("fadeOutTime"));
			Schema.Number(TEXT("fadeTime"), TEXT("fadeTime"));
			Schema.String(TEXT("fadeType"), TEXT("fadeType"));
			Schema.Number(TEXT("falloffDistance"), TEXT("falloffDistance"));
			Schema.String(TEXT("falloffMode"), TEXT("falloffMode"));
			Schema.Number(TEXT("innerRadius"), TEXT("innerRadius"));
			Schema.String(TEXT("inputName"), TEXT("inputName"));
			Schema.String(TEXT("inputType"), TEXT("inputType"));
			Schema.FreeformObject(TEXT("location"), TEXT("location"));
			Schema.Bool(TEXT("looping"), TEXT("looping"));
			Schema.Number(TEXT("lowPassFilterFrequency"), TEXT("lowPassFilterFrequency"));
			Schema.String(TEXT("mixName"), TEXT("mixName"));
			Schema.String(TEXT("name"), TEXT("Name of the asset or mapping to create or remove."));
			Schema.String(TEXT("nodeClassName"), TEXT("nodeClassName"));
			Schema.String(TEXT("nodeType"), TEXT("nodeType"));
			Schema.Number(TEXT("occlusionFilterScale"), TEXT("occlusionFilterScale"));
			Schema.Number(TEXT("occlusionInterpolationTime"), TEXT("occlusionInterpolationTime"));
			Schema.Number(TEXT("occlusionVolumeScale"), TEXT("occlusionVolumeScale"));
			Schema.String(TEXT("outputName"), TEXT("outputName"));
			Schema.String(TEXT("outputType"), TEXT("outputType"));
			Schema.String(TEXT("parentClass"), TEXT("parentClass"));
			Schema.String(TEXT("path"), TEXT("path"));
			Schema.Number(TEXT("pitch"), TEXT("pitch"));
			Schema.FreeformObject(TEXT("properties"), TEXT("properties"));
			Schema.String(TEXT("reverbDistanceMax"), TEXT("reverbDistanceMax"));
			Schema.String(TEXT("reverbDistanceMin"), TEXT("reverbDistanceMin"));
			Schema.String(TEXT("reverbEffect"), TEXT("reverbEffect"));
			Schema.String(TEXT("reverbWetLevelMax"), TEXT("reverbWetLevelMax"));
			Schema.String(TEXT("reverbWetLevelMin"), TEXT("reverbWetLevelMin"));
			Schema.FreeformObject(TEXT("rotation"), TEXT("rotation"));
			Schema.Bool(TEXT("save"), TEXT("save"));
			Schema.FreeformObject(TEXT("size"), TEXT("size"));
			Schema.String(TEXT("soundClassName"), TEXT("soundClassName"));
			Schema.String(TEXT("soundClassPath"), TEXT("soundClassPath"));
			Schema.String(TEXT("soundName"), TEXT("soundName"));
			Schema.String(TEXT("soundPath"), TEXT("soundPath"));
			Schema.String(TEXT("sourceNode"), TEXT("sourceNode"));
			Schema.String(TEXT("sourceNodeId"), TEXT("sourceNodeId"));
			Schema.String(TEXT("sourceOutputName"), TEXT("sourceOutputName"));
			Schema.String(TEXT("sourcePin"), TEXT("sourcePin"));
			Schema.String(TEXT("spatialization"), TEXT("spatialization"));
			Schema.String(TEXT("speakerPath"), TEXT("speakerPath"));
			Schema.Number(TEXT("startTime"), TEXT("startTime"));
			Schema.String(TEXT("targetInputName"), TEXT("targetInputName"));
			Schema.String(TEXT("targetNode"), TEXT("targetNode"));
			Schema.String(TEXT("targetNodeId"), TEXT("targetNodeId"));
			Schema.String(TEXT("targetPin"), TEXT("targetPin"));
			Schema.Number(TEXT("targetVolume"), TEXT("targetVolume"));
			Schema.Number(TEXT("velocityScale"), TEXT("velocityScale"));
			Schema.Number(TEXT("volume"), TEXT("volume"));
			Schema.String(TEXT("volumeAdjuster"), TEXT("volumeAdjuster"));
			Schema.String(TEXT("wavePath"), TEXT("wavePath"));
			Schema.Number(TEXT("windowSize"), TEXT("windowSize"));
			Schema.StringEnum(TEXT("action"), { TEXT("add_cue_node"), TEXT("add_metasound_input"), TEXT("add_metasound_node"), TEXT("add_metasound_output"), TEXT("add_mix_modifier"), TEXT("add_source_effect"), TEXT("clear_sound_mix_class_override"), TEXT("configure_distance_attenuation"), TEXT("configure_mix_eq"), TEXT("configure_occlusion"), TEXT("configure_reverb_send"), TEXT("configure_spatialization"), TEXT("connect_cue_nodes"), TEXT("connect_metasound_nodes"), TEXT("create_ambient_sound"), TEXT("create_attenuation_settings"), TEXT("create_audio_component"), TEXT("create_dialogue_voice"), TEXT("create_dialogue_wave"), TEXT("create_metasound"), TEXT("create_reverb_effect"), TEXT("create_reverb_zone"), TEXT("create_sound_class"), TEXT("create_sound_cue"), TEXT("create_sound_mix"), TEXT("create_source_effect_chain"), TEXT("create_submix_effect"), TEXT("enable_audio_analysis"), TEXT("fade_sound"), TEXT("fade_sound_in"), TEXT("fade_sound_out"), TEXT("get_audio_info"), TEXT("play_sound_2d"), TEXT("play_sound_at_location"), TEXT("play_sound_attached"), TEXT("pop_sound_mix"), TEXT("prime_sound"), TEXT("push_sound_mix"), TEXT("set_audio_occlusion"), TEXT("set_base_sound_mix"), TEXT("set_class_parent"), TEXT("set_class_properties"), TEXT("set_cue_attenuation"), TEXT("set_cue_concurrency"), TEXT("set_dialogue_context"), TEXT("set_doppler_effect"), TEXT("set_metasound_default"), TEXT("set_sound_attenuation"), TEXT("set_sound_mix_class_override"), TEXT("spawn_sound_at_location") }, TEXT("Action to invoke on manage_audio."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedUtility_AudioCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageAudio());

}
