// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageCharacter : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_character"); }
	FString GetDescription() const override { return TEXT("Create Character Blueprints with movement, locomotion, and animation state machines."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.StringEnum(TEXT("ability"), { TEXT("movement"), TEXT("climbing"), TEXT("mantling"), TEXT("vaulting"), TEXT("sliding"), TEXT("wall_running"), TEXT("grappling"), TEXT("footstep_system") }, TEXT("Which setup character ability variant to run."));
			Schema.Number(TEXT("acceleration"), TEXT("Maximum acceleration."));
			Schema.Number(TEXT("airControl"), TEXT("Air control fraction (0-1)."));
			Schema.String(TEXT("animBlueprintPath"), TEXT("Canonical /Game Animation Blueprint asset path."));
			Schema.Bool(TEXT("applyAsOverrides"), TEXT("Apply exported materials back onto the character as overrides. Default true."));
			Schema.Bool(TEXT("avoidanceEnabled"), TEXT("Whether RVO avoidance is enabled."));
			Schema.Bool(TEXT("blocking"), TEXT("Wait for auto-rigging to finish before answering. Default false: the request is queued on the Epic cloud service and metahuman_status reports canBuild once it lands. True parks the editor until the service answers."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.Bool(TEXT("bodyMesh"), TEXT("Export the body skeletal mesh. Default true."));
			Schema.Number(TEXT("brakingDeceleration"), TEXT("Braking deceleration while walking."));
			Schema.String(TEXT("buildPath"), TEXT("Content folder for the assembled assets. Defaults to the palette setting."));
			Schema.Bool(TEXT("cameraUsePawnControlRotation"), TEXT("Whether the spring arm follows the controller look rotation. The camera under it is always arm-relative."));
			Schema.Bool(TEXT("canCrouch"), TEXT("Whether the character is allowed to crouch."));
			Schema.Number(TEXT("capsuleHalfHeight"), TEXT("Capsule collision half-height in world units."));
			Schema.Number(TEXT("capsuleRadius"), TEXT("Capsule collision radius in world units."));
			Schema.String(TEXT("characterPath"), TEXT("Canonical /Game path of a MetaHuman Character asset."));
			Schema.Number(TEXT("climbSpeed"), TEXT("Climb speed."));
			Schema.String(TEXT("climbableTag"), TEXT("Actor tag marking climbable surfaces."));
			Schema.String(TEXT("commonFolderPath"), TEXT("Content folder for shared MetaHuman assets."));
			Schema.Number(TEXT("crouchSpeed"), TEXT("Maximum walk speed while crouched."));
			Schema.Number(TEXT("crouchedHalfHeight"), TEXT("Capsule half-height while crouched."));
			Schema.Number(TEXT("customSpeed"), TEXT("Movement speed for the custom mode."));
			Schema.Number(TEXT("deceleration"), TEXT("Walking deceleration."));
			Schema.Bool(TEXT("dnaBody"), TEXT("Export body DNA. Default true."));
			Schema.Bool(TEXT("dnaHead"), TEXT("Export head DNA. Default true."));
			Schema.StringEnum(TEXT("exportType"), { TEXT("geometry"), TEXT("materials"), TEXT("dna") }, TEXT("Which artifact to export: skeletal meshes, material instances, or DNA."));
			Schema.String(TEXT("externalPath"), TEXT("Folder on disk for exported .dna files. DNA export only."));
			Schema.Number(TEXT("fallingLateralFriction"), TEXT("Lateral friction while falling."));
			Schema.Number(TEXT("flySpeed"), TEXT("Maximum fly speed."));
			Schema.Bool(TEXT("footstepEnabled"), TEXT("Whether the footstep system is enabled."));
			Schema.String(TEXT("footstepSocketLeft"), TEXT("Left foot socket name."));
			Schema.String(TEXT("footstepSocketRight"), TEXT("Right foot socket name."));
			Schema.Number(TEXT("footstepTraceDistance"), TEXT("Footstep ground-trace distance."));
			Schema.Bool(TEXT("fullBodyMesh"), TEXT("Export a combined full-body skeletal mesh. Default false."));
			Schema.Number(TEXT("grappleRange"), TEXT("Maximum grapple range in world units."));
			Schema.Number(TEXT("grappleSpeed"), TEXT("Grapple pull speed."));
			Schema.String(TEXT("grappleTargetTag"), TEXT("Actor tag marking valid grapple targets."));
			Schema.Number(TEXT("gravityScale"), TEXT("Gravity scale multiplier."));
			Schema.Number(TEXT("groundFriction"), TEXT("Ground friction."));
			Schema.Bool(TEXT("headMesh"), TEXT("Export the head skeletal mesh. Default true."));
			Schema.Number(TEXT("jumpHeight"), TEXT("Jump z-velocity."));
			Schema.Number(TEXT("jumpHoldTime"), TEXT("Maximum jump hold time in seconds."));
			Schema.Number(TEXT("mantleHeight"), TEXT("Maximum mantle height in world units."));
			Schema.Number(TEXT("mantleReachDistance"), TEXT("Maximum mantle reach distance."));
			Schema.Number(TEXT("maxJumpCount"), TEXT("Maximum number of jumps."));
			Schema.Object(TEXT("meshOffset"), TEXT("Mesh relative location offset."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Object(TEXT("meshRotation"), TEXT("Mesh relative rotation in degrees."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT(""));
				  S.Number(TEXT("yaw"), TEXT(""));
				  S.Number(TEXT("roll"), TEXT(""));
			});
			Schema.Number(TEXT("modeId"), TEXT("Custom movement mode identifier."));
			Schema.String(TEXT("modeName"), TEXT("Custom movement mode name."));
			Schema.StringEnum(TEXT("movementProperty"), { TEXT("walk_speed"), TEXT("jump_height"), TEXT("gravity_scale"), TEXT("ground_friction"), TEXT("braking_deceleration") }, TEXT("Which set movement property variant to run."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("nameOverride"), TEXT("Folder name for the assembled character instead of the asset name."));
			Schema.Number(TEXT("navAgentHeight"), TEXT("Nav agent height."));
			Schema.Number(TEXT("navAgentRadius"), TEXT("Nav agent radius."));
			Schema.Bool(TEXT("orientToMovement"), TEXT("Whether the character orients rotation to movement."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite existing assets instead of creating uniquely-named ones. Default true."));
			Schema.String(TEXT("parentClass"), TEXT("String parameter."));
			Schema.Number(TEXT("particleScale"), TEXT("Footstep particle scale multiplier."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.StringEnum(TEXT("pipelineQuality"), { TEXT("Low"), TEXT("Medium"), TEXT("High"), TEXT("Cinematic") }, TEXT("Quality level. Only meaningful when pipelineType is Optimized or UEFN."));
			Schema.StringEnum(TEXT("pipelineType"), { TEXT("Cinematic"), TEXT("Optimized"), TEXT("UEFN") }, TEXT("Assembly pipeline. Cinematic is the film-quality path; Optimized and UEFN trade fidelity for runtime cost."));
			Schema.String(TEXT("projectPath"), TEXT("Content folder receiving the exported assets."));
			Schema.Bool(TEXT("reportProgress"), TEXT("Emit editor progress notifications during auto-rigging. Default false."));
			Schema.StringEnum(TEXT("rigType"), { TEXT("JointsOnly"), TEXT("JointsAndBlendShapes") }, TEXT("Face rig detail to request. JointsAndBlendShapes is required for facial animation."));
			Schema.Number(TEXT("rotationRate"), TEXT("Rotation rate in degrees per second."));
			Schema.Number(TEXT("runSpeed"), TEXT("Run speed; ignored when walkSpeed is also supplied."));
			Schema.StringEnum(TEXT("setting"), { TEXT("movement_speeds"), TEXT("jump"), TEXT("crouch"), TEXT("sprint"), TEXT("rotation"), TEXT("capsule_component"), TEXT("mesh_component"), TEXT("camera_component"), TEXT("nav_movement"), TEXT("footstep_fx"), TEXT("custom_movement_mode"), TEXT("surface_sound") }, TEXT("Which configure character variant to run."));
			Schema.String(TEXT("skeletalMeshPath"), TEXT("Canonical /Game SkeletalMesh asset path."));
			Schema.Number(TEXT("slideCooldown"), TEXT("Slide cooldown in seconds."));
			Schema.Number(TEXT("slideDuration"), TEXT("Slide duration in seconds."));
			Schema.Number(TEXT("slideSpeed"), TEXT("Slide speed."));
			Schema.Bool(TEXT("springArmLagEnabled"), TEXT("Whether spring-arm camera lag is enabled."));
			Schema.Number(TEXT("springArmLagSpeed"), TEXT("Spring-arm camera lag speed."));
			Schema.Number(TEXT("springArmLength"), TEXT("Spring-arm target arm length."));
			Schema.Number(TEXT("sprintSpeed"), TEXT("Sprint speed."));
			Schema.String(TEXT("surfaceType"), TEXT("String parameter."));
			Schema.Number(TEXT("swimSpeed"), TEXT("Maximum swim speed."));
			Schema.Bool(TEXT("useControllerRotationPitch"), TEXT("Whether controller pitch drives actor rotation."));
			Schema.Bool(TEXT("useControllerRotationRoll"), TEXT("Whether controller roll drives actor rotation."));
			Schema.Bool(TEXT("useControllerRotationYaw"), TEXT("Whether controller yaw drives actor rotation."));
			Schema.Number(TEXT("vaultDepth"), TEXT("Maximum vault depth in world units."));
			Schema.Number(TEXT("vaultHeight"), TEXT("Maximum vault height in world units."));
			Schema.Number(TEXT("volumeMultiplier"), TEXT("Footstep audio volume multiplier."));
			Schema.Number(TEXT("walkSpeed"), TEXT("Maximum walk speed."));
			Schema.Number(TEXT("wallRunDuration"), TEXT("Wall-run duration in seconds."));
			Schema.Number(TEXT("wallRunGravityScale"), TEXT("Gravity scale applied while wall running."));
			Schema.Number(TEXT("wallRunSpeed"), TEXT("Wall-run speed."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_character_blueprint"), TEXT("configure_character"), TEXT("setup_character_ability"), TEXT("set_movement_property"), TEXT("get_character_info"), TEXT("metahuman_status"), TEXT("create_metahuman"), TEXT("rig_metahuman"), TEXT("build_metahuman"), TEXT("export_metahuman") }, TEXT("Action to invoke on manage_character."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedGameplay_CharacterCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageCharacter());

}
