// scripts/gateway-manifest/emit.ts
// Output formatters: pretty JSON, compact JSON, and the C++ header template.
// All three are pure functions of the manifest data - no I/O.

import type { ToolDefinition } from '../../src/tools/definitions/shared/tool-definition.js';
import { buildGatewayManifest } from './build.js';

export const prettyManifest = (defs: readonly ToolDefinition[]): string =>
  JSON.stringify(buildGatewayManifest(defs), null, 2);

export const compactManifest = (defs: readonly ToolDefinition[]): string =>
  JSON.stringify(buildGatewayManifest(defs));

// allow: SIZE_OK - C++ header template literal (pure data, no logic)
export const MANIFEST_H = (compact: string): string =>
`// GENERATED by scripts/generate-gateway-manifest.ts -- do not edit.
// Mirrors src/gateway/gateway-manifest.generated.json for native MCP consumption.
// Self-contained: pulls McpNativeGatewayCatalog.h so GatewayError/GatewayStringArray
// (the SetArrayField JSON-value helper -> TArray<TSharedPtr<FJsonValue>>) resolve
// regardless of include order in any translation unit that includes this header.
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "MCP/Gateway/McpNativeGatewayCatalog.h"

class FMcpDynamicToolManager;

struct FGatewayManifestTool
{
	FString Name;
	FString Category;
	FString Description;
	TArray<FString> Actions;
	TArray<FString> ParameterNames;
	TSharedPtr<FJsonObject> InputSchema;
};

inline bool TryLoadGatewayManifest(TArray<FGatewayManifestTool>& OutTools)
{
	static constexpr const TCHAR* GatewayManifestJson = TEXT(R"MCPGWMANIFEST(
${compact}
)MCPGWMANIFEST");
	OutTools.Reset();
	const FString Json(GatewayManifestJson);
	TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Json);
	TSharedPtr<FJsonObject> Root;
	if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid()) return false;
	const TArray<TSharedPtr<FJsonValue>>* Tools = nullptr;
	if (!Root->TryGetArrayField(TEXT("tools"), Tools) || !Tools) return false;
	for (const TSharedPtr<FJsonValue>& V : *Tools)
	{
		const TSharedPtr<FJsonObject>* Obj = nullptr;
		if (!V->TryGetObject(Obj) || !Obj || !(*Obj).IsValid()) return false;
		const TSharedPtr<FJsonObject>& T = *Obj;
		FGatewayManifestTool M;
		T->TryGetStringField(TEXT("name"), M.Name);
		FString Cat;
		if (T->TryGetStringField(TEXT("category"), Cat)) M.Category = Cat;
		T->TryGetStringField(TEXT("description"), M.Description);
		const TArray<TSharedPtr<FJsonValue>>* A = nullptr;
		if (T->TryGetArrayField(TEXT("actions"), A) && A)
			for (const TSharedPtr<FJsonValue>& E : *A) { FString S; if (E->TryGetString(S)) M.Actions.AddUnique(S); }
		const TArray<TSharedPtr<FJsonValue>>* P = nullptr;
		if (T->TryGetArrayField(TEXT("parameterNames"), P) && P)
			for (const TSharedPtr<FJsonValue>& E : *P) { FString S; if (E->TryGetString(S)) M.ParameterNames.AddUnique(S); }
		const TSharedPtr<FJsonObject>* Sch = nullptr;
		if (T->TryGetObjectField(TEXT("inputSchema"), Sch) && Sch) M.InputSchema = *Sch;
		OutTools.Add(MoveTemp(M));
	}
	return OutTools.Num() > 0;
}

// Closest-match suggestion + nextCall helpers (GatewayClosestMatches, GatewayBuildNextCall,
// GatewayLevenshtein) are declared in McpNativeGatewayCatalog.h and defined in its .cpp so the
// generated manifest stays compact. GatewaySearchFromManifest / GatewayDescribeFromManifest below
// call them.

// Catalog (search) sourced from the neutral manifest; null -> caller falls back to registry.
// Compact: tool summary + action names only. No inputSchema or parameter-name bodies.
inline TSharedPtr<FJsonObject> GatewaySearchFromManifest(
	const FString& Query, int32 Limit, int32 Offset, const FMcpDynamicToolManager& ToolManager)
{
	TArray<FGatewayManifestTool> Tools;
	if (!TryLoadGatewayManifest(Tools)) return nullptr;
	const FString Q = Query.ToLower();
	TArray<TSharedPtr<FJsonObject>> Matches;
	for (const FGatewayManifestTool& M : Tools)
	{
		if (!Q.IsEmpty())
		{
			FString S = M.Name + TEXT(" ") + M.Category + TEXT(" ") + M.Description;
			for (const FString& A : M.Actions) S += TEXT(" ") + A;
			if (!S.ToLower().Contains(Q)) continue;
		}
		auto D = MakeShared<FJsonObject>();
		D->SetStringField(TEXT("name"), M.Name);
		D->SetStringField(TEXT("category"), M.Category);
		D->SetStringField(TEXT("description"), M.Description);
		D->SetArrayField(TEXT("actions"), GatewayStringArray(M.Actions));
		D->SetBoolField(TEXT("enabled"), ToolManager.IsToolEnabled(M.Name));
		Matches.Add(D);
	}
	const int32 Total = Matches.Num();
	TArray<TSharedPtr<FJsonObject>> Results;
	for (int32 i = Offset; i < Total && Results.Num() < Limit; ++i) Results.Add(Matches[i]);
	auto Out = MakeShared<FJsonObject>();
	Out->SetBoolField(TEXT("success"), true);
	Out->SetStringField(TEXT("operation"), TEXT("search"));
	Out->SetStringField(TEXT("query"), Query);
	TArray<TSharedPtr<FJsonValue>> RV;
	for (const TSharedPtr<FJsonObject>& R : Results) RV.Add(MakeShared<FJsonValueObject>(R));
	Out->SetArrayField(TEXT("results"), RV);
	Out->SetNumberField(TEXT("total"), Total);
	Out->SetNumberField(TEXT("offset"), Offset);
	Out->SetNumberField(TEXT("limit"), Limit);
	Out->SetBoolField(TEXT("hasMore"), Offset + Results.Num() < Total);
	Out->SetStringField(TEXT("message"),
		TEXT("Search results are compact. Call describe with an exact tool and action before execute."));
	return Out;
}

// Definition (describe) sourced from the neutral manifest; null -> caller falls back to registry.
// Progressive drill-down: tool summary -> action parameter catalog -> single param schema.
// No response dumps every tool schema or the full inputSchema for a described tool.
inline TSharedPtr<FJsonObject> GatewayDescribeFromManifest(
	const FString& ToolName, const FString& Action, const FMcpDynamicToolManager& ToolManager,
	const FString& Param = FString(), const FString& Query = FString(),
	int32 Limit = 20, int32 Offset = 0)
{
	TArray<FGatewayManifestTool> Tools;
	if (!TryLoadGatewayManifest(Tools)) return nullptr;
	const FGatewayManifestTool* M = Tools.FindByPredicate(
		[&](const FGatewayManifestTool& X) { return X.Name == ToolName; });
	if (!M) return nullptr;
	const TArray<FString>& Actions = M->Actions;
	if (!Action.IsEmpty() && !Actions.Contains(Action))
	{
		TArray<FString> Suggestions = GatewayClosestMatches(Action, Actions, 3);
		TSharedPtr<FJsonObject> Err = GatewayError(TEXT("describe"), TEXT("UNKNOWN_ACTION"),
			FString::Printf(TEXT("Unknown action '%s' for %s."), *Action, *ToolName));
		Err->SetStringField(TEXT("tool"), ToolName);
		Err->SetArrayField(TEXT("availableActions"), GatewayStringArray(Actions));
		Err->SetArrayField(TEXT("suggestions"), GatewayStringArray(Suggestions));
		Err->SetObjectField(TEXT("nextCall"), GatewayBuildNextCall(TEXT("describe"), ToolName, Suggestions.Num() > 0 ? Suggestions[0] : FString(), FString()));
		return Err;
	}
	const TArray<FString>& ParamNames = M->ParameterNames;
	if (!Param.IsEmpty())
	{
		if (!ParamNames.Contains(Param))
		{
			TArray<FString> Suggestions = GatewayClosestMatches(Param, ParamNames, 3);
			TSharedPtr<FJsonObject> Err = GatewayError(TEXT("describe"), TEXT("UNKNOWN_PARAM"),
				FString::Printf(TEXT("Unknown parameter '%s' for %s."), *Param, *ToolName));
			Err->SetStringField(TEXT("tool"), ToolName);
			if (!Action.IsEmpty()) Err->SetStringField(TEXT("action"), Action);
			Err->SetArrayField(TEXT("availableParameters"), GatewayStringArray(ParamNames));
			Err->SetArrayField(TEXT("suggestions"), GatewayStringArray(Suggestions));
			Err->SetObjectField(TEXT("nextCall"), GatewayBuildNextCall(TEXT("describe"), ToolName, Action, Suggestions.Num() > 0 ? Suggestions[0] : FString()));
			return Err;
		}
		const TSharedPtr<FJsonObject>* Props = nullptr;
		TSharedPtr<FJsonObject> ParamSchema = MakeShared<FJsonObject>();
		if (M->InputSchema.IsValid() && M->InputSchema->TryGetObjectField(TEXT("properties"), Props) && Props)
		{
			const TSharedPtr<FJsonObject>* P = nullptr;
			if ((*Props)->TryGetObjectField(Param, P) && P) ParamSchema = *P;
		}
		const TArray<TSharedPtr<FJsonValue>>* Required = nullptr;
		bool bRequired = false;
		if (M->InputSchema.IsValid() && M->InputSchema->TryGetArrayField(TEXT("required"), Required) && Required)
		{
			for (const TSharedPtr<FJsonValue>& V : *Required)
			{
				FString S; if (V->TryGetString(S) && S == Param) { bRequired = true; break; }
			}
		}
		auto Out = MakeShared<FJsonObject>();
		Out->SetBoolField(TEXT("success"), true);
		Out->SetStringField(TEXT("operation"), TEXT("describe"));
		Out->SetStringField(TEXT("tool"), ToolName);
		if (!Action.IsEmpty()) Out->SetStringField(TEXT("action"), Action);
		Out->SetStringField(TEXT("param"), Param);
		Out->SetBoolField(TEXT("required"), bRequired);
		Out->SetObjectField(TEXT("schema"), ParamSchema);
		Out->SetStringField(TEXT("scope"), TEXT("union"));
		Out->SetBoolField(TEXT("perActionSchemas"), false);
		Out->SetStringField(TEXT("message"),
			TEXT("This parameter belongs to the tool-union catalog (per-action parameter mappings do not exist). Pass it only when relevant to the selected action, using the exact casing shown."));
		return Out;
	}
	const FString Q = Query.ToLower();
	if (Action.IsEmpty())
	{
		TArray<FString> Filtered = Actions;
		if (!Q.IsEmpty()) { Filtered.Empty(); for (const FString& A : Actions) if (A.ToLower().Contains(Q)) Filtered.Add(A); }
		const int32 Total = Filtered.Num();
		TArray<FString> Paged;
		for (int32 i = Offset; i < Total && Paged.Num() < Limit; ++i) Paged.Add(Filtered[i]);
		auto Out = MakeShared<FJsonObject>();
		Out->SetBoolField(TEXT("success"), true);
		Out->SetStringField(TEXT("operation"), TEXT("describe"));
		Out->SetStringField(TEXT("tool"), ToolName);
		Out->SetStringField(TEXT("category"), M->Category);
		Out->SetStringField(TEXT("description"), M->Description);
		Out->SetBoolField(TEXT("enabled"), ToolManager.IsToolEnabled(ToolName));
		Out->SetArrayField(TEXT("actions"), GatewayStringArray(Paged));
		Out->SetNumberField(TEXT("actionCount"), Total);
		Out->SetNumberField(TEXT("actionOffset"), Offset);
		Out->SetNumberField(TEXT("actionLimit"), Limit);
		Out->SetBoolField(TEXT("actionHasMore"), Offset + Paged.Num() < Total);
		Out->SetStringField(TEXT("scope"), TEXT("tool"));
		Out->SetBoolField(TEXT("perActionSchemas"), false);
		Out->SetObjectField(TEXT("drillDown"), GatewayBuildNextCall(TEXT("describe"), ToolName, Paged.Num() > 0 ? Paged[0] : (Actions.Num() > 0 ? Actions[0] : FString()), FString()));
		Out->SetStringField(TEXT("message"),
			TEXT("Tool summary. Drill into an action (drillDown) to list its parameter catalog - parameters are the tool-union, not action-specific."));
		return Out;
	}
	TArray<FString> Filtered = ParamNames;
	if (!Q.IsEmpty()) { Filtered.Empty(); for (const FString& N : ParamNames) if (N.ToLower().Contains(Q)) Filtered.Add(N); }
	const int32 Total = Filtered.Num();
	TArray<TSharedPtr<FJsonValue>> Params;
	for (int32 i = Offset; i < Total && Params.Num() < Limit; ++i)
	{
		const FString& N = Filtered[i];
		const TSharedPtr<FJsonObject>* Props = nullptr;
		TSharedPtr<FJsonObject> Schema = MakeShared<FJsonObject>();
		if (M->InputSchema.IsValid() && M->InputSchema->TryGetObjectField(TEXT("properties"), Props) && Props)
		{
			const TSharedPtr<FJsonObject>* P = nullptr;
			if ((*Props)->TryGetObjectField(N, P) && P) Schema = *P;
		}
		auto Sum = MakeShared<FJsonObject>();
		Sum->SetStringField(TEXT("name"), N);
		FString Type; if (Schema->TryGetStringField(TEXT("type"), Type)) Sum->SetStringField(TEXT("type"), Type); else Sum->SetStringField(TEXT("type"), TEXT("unknown"));
		FString Desc; if (Schema->TryGetStringField(TEXT("description"), Desc)) Sum->SetStringField(TEXT("description"), Desc);
		Params.Add(MakeShared<FJsonValueObject>(Sum));
	}
	auto Out = MakeShared<FJsonObject>();
	Out->SetBoolField(TEXT("success"), true);
	Out->SetStringField(TEXT("operation"), TEXT("describe"));
	Out->SetStringField(TEXT("tool"), ToolName);
	Out->SetStringField(TEXT("action"), Action);
	Out->SetStringField(TEXT("category"), M->Category);
	Out->SetStringField(TEXT("description"), M->Description);
	Out->SetBoolField(TEXT("enabled"), ToolManager.IsToolEnabled(ToolName));
	Out->SetArrayField(TEXT("actions"), GatewayStringArray(TArray<FString>{ Action }));
	Out->SetArrayField(TEXT("parameters"), Params);
	Out->SetNumberField(TEXT("parameterCount"), Total);
	Out->SetNumberField(TEXT("parameterOffset"), Offset);
	Out->SetNumberField(TEXT("parameterLimit"), Limit);
	Out->SetBoolField(TEXT("parameterHasMore"), Offset + Params.Num() < Total);
	Out->SetStringField(TEXT("scope"), TEXT("union"));
	Out->SetBoolField(TEXT("perActionSchemas"), false);
	Out->SetObjectField(TEXT("drillDown"), GatewayBuildNextCall(TEXT("describe"), ToolName, Action, Filtered.Num() > 0 ? Filtered[0] : (ParamNames.Num() > 0 ? ParamNames[0] : FString())));
	Out->SetStringField(TEXT("message"),
		TEXT("parameterNames is the union catalog for this parent tool (per-action schemas do not exist). Drill into a single param (drillDown) for its full schema."));
	return Out;
}
`;
