/**
 * Attachment and advanced records: attach/attach_actor, detach/detach_actor,
 * set_blueprint_variables, create_snapshot, set_actor_collision,
 * call_actor_function.
 *
 * Grounded in actor-basic-handlers.ts (attach, detach) and the fallback
 * dispatch path for set_blueprint_variables and create_snapshot, plus
 * actor-component-handlers.ts (set_collision, call_function), and native
 * ControlActor dispatch (attach/attach_actor -> HandleControlActorAttach,
 * detach/detach_actor -> HandleControlActorDetach,
 * set_blueprint_variables -> HandleControlActorSetBlueprintVariables,
 * create_snapshot -> HandleControlActorCreateSnapshot,
 * set_collision/set_actor_collision -> HandleControlActorSetCollision,
 * call_function/call_actor_function -> HandleControlActorCallFunction).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { actorAlias, CANONICAL_NR, DOMAIN, internalDispatchNr, P } from './properties.js';

const FAMILY_ATTACH = 'attachment';
const FAMILY_BLUEPRINT = 'blueprint';
const FAMILY_SNAPSHOT = 'snapshot';
const FAMILY_COLLISION = 'collision';
const FAMILY_FUNCTION = 'function';

export const ADVANCED_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'attach',
    domain: DOMAIN,
    family: FAMILY_ATTACH,
    topics: ['attach actor', 'parent actor', 'attach to actor', 'child actor', 'attach to socket'],
    summary: 'Attach a child actor to a parent actor in the scene hierarchy.',
    whenToUse: ['An actor must follow another actor transform.'],
    whenNotToUse: ['The actor should remain independent (use detach).'],
    inputProps: { childActor: P.childActor, parentActor: P.parentActor },
    required: ['childActor', 'parentActor'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'attach', childActor: 'Sword', parentActor: 'Knight' },
    exampleOutput: { success: true, message: 'Attached Sword to Knight' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'attach_actor',
    domain: DOMAIN,
    family: FAMILY_ATTACH,
    summary: 'Alias of attach; normalizeActorAction maps attach_actor to attach.',
    whenToUse: ['Preferred when callers use the explicit attach_actor verb.'],
    whenNotToUse: ['Use attach to avoid alias normalization.'],
    inputProps: { childActor: P.childActor, parentActor: P.parentActor },
    required: ['childActor', 'parentActor'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    ...actorAlias('attach'),
    exampleInput: { action: 'attach_actor', childActor: 'Sword', parentActor: 'Knight' },
    exampleOutput: { success: true, message: 'Attached Sword to Knight' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'detach',
    domain: DOMAIN,
    family: FAMILY_ATTACH,
    summary: 'Detach a child actor from its current parent.',
    whenToUse: ['An actor must be released from attachment.'],
    whenNotToUse: ['The actor is not attached (no-op).'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'detach', actorName: 'Sword' },
    exampleOutput: { success: true, message: 'Detached Sword' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'detach_actor',
    domain: DOMAIN,
    family: FAMILY_ATTACH,
    summary: 'Alias of detach; normalizeActorAction maps detach_actor to detach.',
    whenToUse: ['Preferred when callers use the explicit detach_actor verb.'],
    whenNotToUse: ['Use detach to avoid alias normalization.'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'interactive',
    costResources: 'low',
    ...actorAlias('detach'),
    exampleInput: { action: 'detach_actor', actorName: 'Sword' },
    exampleOutput: { success: true, message: 'Detached Sword' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_blueprint_variables',
    domain: DOMAIN,
    family: FAMILY_BLUEPRINT,
    summary: 'Set one or more Blueprint instance variables on a spawned actor.',
    whenToUse: ['Instance variables on a Blueprint actor must be configured.'],
    whenNotToUse: ['The actor is not a Blueprint instance (variables are undefined).'],
    inputProps: { actorName: P.actorName, variables: P.variables },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'set_blueprint_variables', actorName: 'Lamp1', variables: { Brightness: 2.0 } },
    exampleOutput: { success: true, message: 'Set variables on Lamp1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'create_snapshot',
    domain: DOMAIN,
    family: FAMILY_SNAPSHOT,
    summary: 'Capture a named snapshot of actor state for later comparison.',
    whenToUse: ['Actor state must be recorded before a mutation.'],
    whenNotToUse: ['No later comparison or restore is planned.'],
    inputProps: { actorName: P.actorName, snapshotName: P.snapshotName },
    required: ['actorName', 'snapshotName'],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'create_snapshot', actorName: 'Cube1', snapshotName: 'before_move' },
    exampleOutput: { success: true, message: 'Snapshot before_move created for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_collision',
    domain: DOMAIN,
    family: FAMILY_COLLISION,
    summary: 'Enable or disable collision on an actor; normalizes to set_collision.',
    whenToUse: ['Actor collision must be toggled.'],
    whenNotToUse: ['Per-component collision is required (use set_component_property).'],
    inputProps: { actorName: P.actorName, collisionEnabled: P.collisionEnabled },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: internalDispatchNr('set_actor_collision', 'set_collision'),
    exampleInput: { action: 'set_actor_collision', actorName: 'Cube1', collisionEnabled: true },
    exampleOutput: { success: true, message: 'Collision enabled for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'call_actor_function',
    domain: DOMAIN,
    family: FAMILY_FUNCTION,
    summary: 'Call a named function on an actor with optional arguments; normalizes to call_function.',
    whenToUse: ['A Blueprint or native function on an actor must be invoked.'],
    whenNotToUse: ['The function has side effects that cannot be undone.'],
    inputProps: { actorName: P.actorName, functionName: P.functionName, arguments: P.arguments },
    required: ['actorName', 'functionName'],
    outputProps: { value: P.value },
    outputRequired: [],
    effect: 'destructive',
    policyOverride: { consent: 'elevated' },
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: internalDispatchNr('call_actor_function', 'call_function'),
    exampleInput: { action: 'call_actor_function', actorName: 'Lamp1', functionName: 'ToggleLight' },
    exampleOutput: { success: true, message: 'Called ToggleLight on Lamp1', value: true },
  }),
];
