/**
 * Component and material records: add_component, remove_component,
 * set_component_properties/set_component_property, get_component_property,
 * set_material/set_actor_material/apply_material.
 *
 * Grounded in actor-component-handlers.ts (set_component_property, set_material,
 * remove_component, get_component_property, find_by_class, set_collision,
 * call_function, get_bounding_box) and the fallback path for add_component,
 * plus native ControlActor dispatch (add_component -> HandleControlActorAddComponent,
 * set_component_properties/property -> HandleControlActorSetComponentProperties,
 * get_component_property -> HandleControlActorGetComponentProperty,
 * set_material+aliases -> HandleControlActorSetMaterial,
 * remove_component -> HandleControlActorRemoveComponent).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { actorAlias, CANONICAL_NR, DOMAIN, P } from './properties.js';

const FAMILY_COMPONENT = 'component';
const FAMILY_MATERIAL = 'material';

export const COMPONENT_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'add_component',
    domain: DOMAIN,
    family: FAMILY_COMPONENT,
    topics: ['add component to actor', 'actor component', 'attach component to actor'],
    summary: 'Add a new component of a given type to an actor.',
    whenToUse: ['A component must be attached to an existing actor.'],
    whenNotToUse: ['An existing component should be configured (use set_component_property).'],
    inputProps: { actorName: P.actorName, componentType: P.componentType, componentName: P.componentName, properties: P.properties },
    required: ['actorName', 'componentType'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'add_component', actorName: 'Cube1', componentType: 'PointLightComponent', componentName: 'Light1' },
    exampleOutput: { success: true, message: 'Added component Light1 to Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'remove_component',
    domain: DOMAIN,
    family: FAMILY_COMPONENT,
    summary: 'Remove a named component from an actor.',
    whenToUse: ['A component must be permanently detached and removed from an actor.'],
    whenNotToUse: ['The component should only be reconfigured (use set_component_property).'],
    inputProps: { actorName: P.actorName, componentName: P.componentName },
    required: ['actorName', 'componentName'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'remove_component', actorName: 'Cube1', componentName: 'Light1' },
    exampleOutput: { success: true, message: 'Removed component Light1 from Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_component_property',
    domain: DOMAIN,
    family: FAMILY_COMPONENT,
    summary: 'Set one or more properties on a named actor component. For RelativeScale3D/RelativeLocation, note that a child inherits its parent\'s scale: Unreal multiplies parent and child scale COMPONENT-WISE in the child\'s own local axes, and rotation does NOT permute which axis each factor lands on. World size = ParentScale * ChildScale * MeshExtent per local axis, and world offset = ParentScale * RelativeLocation. Under a parent scaled non-uniformly, divide the offset you want by the parent scale on that axis.',
    whenToUse: ['Component properties must be changed via a properties object or propertyName/value pair.'],
    whenNotToUse: ['The property should only be read (use get_component_property).'],
    inputProps: { actorName: P.actorName, componentName: P.componentName, properties: P.properties, propertyName: P.propertyName, value: P.value },
    required: ['actorName', 'componentName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'set_component_property', actorName: 'Cube1', componentName: 'Light1', properties: { Intensity: 5.0 } },
    exampleOutput: { success: true, message: 'Set properties on Light1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_component_properties',
    domain: DOMAIN,
    family: FAMILY_COMPONENT,
    summary: 'Alias of set_component_property; normalizeActorAction maps set_component_properties to set_component_property.',
    whenToUse: ['Preferred when callers use the plural set_component_properties verb.'],
    whenNotToUse: ['Use set_component_property to avoid alias normalization.'],
    inputProps: { actorName: P.actorName, componentName: P.componentName, properties: P.properties, propertyName: P.propertyName, value: P.value },
    required: ['actorName', 'componentName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_component_property'),
    exampleInput: { action: 'set_component_properties', actorName: 'Cube1', componentName: 'Light1', properties: { Intensity: 5.0 } },
    exampleOutput: { success: true, message: 'Set properties on Light1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_component_property',
    domain: DOMAIN,
    family: FAMILY_COMPONENT,
    summary: 'Read a single property value from a named actor component.',
    whenToUse: ['A component property value must be inspected.'],
    whenNotToUse: ['The property should be changed (use set_component_property).'],
    inputProps: { actorName: P.actorName, componentName: P.componentName, propertyName: P.propertyName },
    required: ['actorName', 'componentName', 'propertyName'],
    outputProps: { value: P.value },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'get_component_property', actorName: 'Cube1', componentName: 'Light1', propertyName: 'Intensity' },
    exampleOutput: { success: true, message: 'Intensity = 5.0', value: 5.0 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_material',
    domain: DOMAIN,
    family: FAMILY_MATERIAL,
    summary: 'Apply a material asset to a mesh component on an actor, optionally per slot.',
    whenToUse: ['A material must be assigned to an actor mesh component.'],
    whenNotToUse: ['The mesh has no material slots (the assignment is a no-op).'],
    inputProps: { actorName: P.actorName, materialPath: P.materialPath, componentName: P.componentName, materialSlot: P.materialSlot, materialIndex: P.materialIndex, allComponents: P.allComponents },
    required: ['actorName', 'materialPath'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'set_material', actorName: 'Cube1', materialPath: '/Game/Materials/M_Glow', materialSlot: 0 },
    exampleOutput: { success: true, message: 'Set material on Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_material',
    domain: DOMAIN,
    family: FAMILY_MATERIAL,
    summary: 'Alias of set_material; normalizeActorAction maps set_actor_material to set_material.',
    whenToUse: ['Preferred when callers use the explicit set_actor_material verb.'],
    whenNotToUse: ['Use set_material to avoid alias normalization.'],
    inputProps: { actorName: P.actorName, materialPath: P.materialPath, componentName: P.componentName, materialSlot: P.materialSlot, materialIndex: P.materialIndex, allComponents: P.allComponents },
    required: ['actorName', 'materialPath'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_material'),
    exampleInput: { action: 'set_actor_material', actorName: 'Cube1', materialPath: '/Game/Materials/M_Glow' },
    exampleOutput: { success: true, message: 'Set material on Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'apply_material',
    domain: DOMAIN,
    family: FAMILY_MATERIAL,
    summary: 'Alias of set_material; normalizeActorAction maps apply_material to set_material.',
    whenToUse: ['Preferred when callers use the apply_material verb.'],
    whenNotToUse: ['Use set_material to avoid alias normalization.'],
    inputProps: { actorName: P.actorName, materialPath: P.materialPath, componentName: P.componentName, materialSlot: P.materialSlot, materialIndex: P.materialIndex, allComponents: P.allComponents },
    required: ['actorName', 'materialPath'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_material'),
    exampleInput: { action: 'apply_material', actorName: 'Cube1', materialPath: '/Game/Materials/M_Glow' },
    exampleOutput: { success: true, message: 'Set material on Cube1' },
  }),
];
