/**
 * Transform and physics records: set_transform and its five aliases
 * (teleport_actor, set_actor_location, set_actor_rotation, set_actor_scale,
 * set_actor_transform), get_transform and its alias (get_actor_transform),
 * and apply_force.
 *
 * Grounded in actor-basic-handlers.ts (set_transform, get_transform) and
 * actor-physics-handler.ts (apply_force), plus native ControlActor dispatch
 * (set_transform+aliases -> HandleControlActorSetTransform, get_transform+
 * alias -> HandleControlActorGetTransform, apply_force ->
 * HandleControlActorApplyForce).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { actorAlias, CANONICAL_NR, DOMAIN, P } from './properties.js';

const FAMILY_TRANSFORM = 'transform';
const FAMILY_PHYSICS = 'physics';

const TRANSFORM_INPUT = {
  actorName: P.actorName,
  location: P.location,
  rotation: P.rotation,
  scale: P.scale,
};

export const TRANSFORM_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_transform',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    topics: ['move actor', 'set actor location', 'set position', 'rotate actor', 'set rotation', 'scale actor', 'teleport actor', 'translate'],
    aliases: ['control_actor.move', 'control_actor.move_actor'],
    summary: 'Move, rotate or scale an actor by setting its world transform (location, rotation, scale).',
    whenToUse: ['An actor must be moved, rotated, or rescaled in one call.'],
    whenNotToUse: ['Only the transform needs to be read (use get_transform).'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'set_transform', actorName: 'Cube1', location: [10, 20, 30], rotation: [0, 90, 0], scale: [1, 1, 1] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'teleport_actor',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of set_transform; normalizeActorAction maps teleport_actor to set_transform.',
    whenToUse: ['Preferred when callers use the teleport_actor verb.'],
    whenNotToUse: ['Use set_transform to avoid alias normalization.'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_transform'),
    exampleInput: { action: 'teleport_actor', actorName: 'Cube1', location: [5, 5, 5] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_location',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of set_transform (location-only intent); normalizes to set_transform.',
    whenToUse: ['An actor must be moved to a new location.'],
    whenNotToUse: ['Use set_transform for the full transform verb.'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_transform'),
    exampleInput: { action: 'set_actor_location', actorName: 'Cube1', location: [100, 0, 0] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_rotation',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of set_transform (rotation-only intent); normalizes to set_transform.',
    whenToUse: ['An actor must be rotated.'],
    whenNotToUse: ['Use set_transform for the full transform verb.'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_transform'),
    exampleInput: { action: 'set_actor_rotation', actorName: 'Cube1', rotation: [0, 45, 0] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_scale',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of set_transform (scale-only intent); normalizes to set_transform.',
    whenToUse: ['An actor must be rescaled.'],
    whenNotToUse: ['Use set_transform for the full transform verb.'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_transform'),
    exampleInput: { action: 'set_actor_scale', actorName: 'Cube1', scale: [2, 2, 2] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_transform',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of set_transform; normalizeActorAction maps set_actor_transform to set_transform.',
    whenToUse: ['Preferred when callers use the explicit set_actor_transform verb.'],
    whenNotToUse: ['Use set_transform to avoid alias normalization.'],
    inputProps: TRANSFORM_INPUT,
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('set_transform'),
    exampleInput: { action: 'set_actor_transform', actorName: 'Cube1', location: [1, 2, 3] },
    exampleOutput: { success: true, message: 'Transform set for Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_transform',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    topics: ['actor location', 'actor position', 'actor rotation', 'where is the actor'],
    summary: 'Read the world transform (location, rotation, scale) of an actor.',
    whenToUse: ['The current transform of an actor must be inspected.'],
    whenNotToUse: ['The transform should be changed (use set_transform).'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    outputProps: { location: P.location, rotation: P.rotation, scale: P.scale },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'get_transform', actorName: 'Cube1' },
    exampleOutput: { success: true, message: 'Transform for Cube1', location: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_actor_transform',
    domain: DOMAIN,
    family: FAMILY_TRANSFORM,
    summary: 'Alias of get_transform; normalizeActorAction maps get_actor_transform to get_transform.',
    whenToUse: ['Preferred when callers use the explicit get_actor_transform verb.'],
    whenNotToUse: ['Use get_transform to avoid alias normalization.'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    outputProps: { location: P.location, rotation: P.rotation, scale: P.scale },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('get_transform'),
    exampleInput: { action: 'get_actor_transform', actorName: 'Cube1' },
    exampleOutput: { success: true, message: 'Transform for Cube1', location: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'apply_force',
    domain: DOMAIN,
    family: FAMILY_PHYSICS,
    summary: 'Apply a physics force vector to an actor, auto-enabling simulation on failure.',
    whenToUse: ['A physical impulse must be applied to a simulated actor.'],
    whenNotToUse: ['The actor is not physics-enabled and physics cannot be auto-enabled.'],
    inputProps: { actorName: P.actorName, force: P.force },
    required: ['actorName', 'force'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'apply_force', actorName: 'Cube1', force: [0, 0, 500] },
    exampleOutput: { success: true, message: 'Force applied to Cube1' },
  }),
];
