import { commonSchemas } from '../../catalog/tool-definition-utils.js';
import type { ToolDefinition } from '../shared/tool-definition.js';
import { MATERIAL_AUTHORING_ACTIONS, TEXTURE_ACTIONS } from '../shared/action-sets.js';

export const manageAssetToolDefinition: ToolDefinition = {
    name: 'manage_asset',
    category: 'core',
    description: 'Create/import/manage assets, material graphs, material instances, procedural textures, render targets, and dependency analysis.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'list', 'import', 'duplicate', 'duplicate_asset', 'rename', 'rename_asset', 'move', 'move_asset', 'delete', 'delete_asset', 'delete_assets', 'create_folder', 'search_assets',
            'get_dependencies', 'get_source_control_state', 'analyze_graph', 'get_asset_graph', 'create_thumbnail', 'set_tags', 'get_metadata', 'set_metadata', 'validate', 'fixup_redirectors', 'find_by_tag', 'generate_report',
            'create_render_target', 'generate_lods', 'add_material_parameter', 'list_instances', 'reset_instance_parameters', 'exists', 'get_material_stats',
            'nanite_rebuild_mesh', 'bulk_rename', 'bulk_delete', 'source_control_checkout', 'source_control_submit',
            // Struct authoring (first-class Blueprint Struct support, issue #510)
            'create_struct', 'get_struct', 'read_struct', 'list_struct_members',
            'add_struct_member', 'remove_struct_member', 'rename_struct_member',
            'set_struct_member_type', 'reorder_struct_members', 'set_struct_member_default',
            'set_struct_member_metadata', 'compare_structs', 'search_struct_usage', 'recompile_struct',
            'rename_struct', 'duplicate_struct', 'delete_struct', 'refresh_struct_dependencies',
            'list_structs', 'export_struct', 'import_struct',
            // Struct ecosystem — DataTable (issue #struct-ecosystem)
            'create_data_table', 'set_data_table_row_struct', 'create_row_struct', 'get_row_struct',
            'set_struct_as_row_struct', 'add_data_table_row', 'get_data_table_row',
            'update_data_table_row', 'delete_data_table_row', 'list_data_table_rows',
            'import_data_table_rows', 'clear_data_table_rows',
            // Struct ecosystem — Enum
            'create_enum', 'delete_enum', 'get_enum', 'add_enum_value', 'remove_enum_value',
            'rename_enum_value', 'reorder_enum_values', 'set_enum_value_metadata', 'split_enum',
            // Struct ecosystem — FInstancedStruct
            'get_instanced_struct_property', 'set_instanced_struct_property',
            ...MATERIAL_AUTHORING_ACTIONS, ...TEXTURE_ACTIONS],
          description: 'Action to perform'
        },
        assetPath: commonSchemas.assetPath,
        directory: commonSchemas.directoryPath,
        classNames: commonSchemas.arrayOfStrings,
        packagePaths: commonSchemas.arrayOfStrings,
        recursivePaths: commonSchemas.booleanProp,
        recursiveClasses: commonSchemas.booleanProp,
        limit: commonSchemas.numberProp,
        offset: commonSchemas.numberProp,
        sourcePath: commonSchemas.sourcePath,
        destinationPath: commonSchemas.destinationPath,
        assetPaths: commonSchemas.arrayOfStrings,
        lodCount: commonSchemas.numberProp,
        posX: commonSchemas.numberProp,
        posY: commonSchemas.numberProp,
        newName: commonSchemas.newName,
        overwrite: commonSchemas.overwrite,
        save: commonSchemas.save,
        fixupRedirectors: commonSchemas.booleanProp,
        directoryPath: commonSchemas.directoryPath,
        name: commonSchemas.name,
        path: commonSchemas.directoryPath,
        parentMaterial: commonSchemas.materialPath,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        depth: commonSchemas.numberProp,
        format: commonSchemas.stringProp,
        meshPath: commonSchemas.meshPath,
        tag: commonSchemas.tagName,
        metadata: commonSchemas.objectProp,
        nodeType: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        sourceNodeId: commonSchemas.sourceNodeId,
        targetNodeId: commonSchemas.targetNodeId,
        inputName: commonSchemas.pinName,
        parameterName: commonSchemas.parameterName,
        value: commonSchemas.value,
        x: commonSchemas.numberProp,
        y: commonSchemas.numberProp,
        maxDepth: commonSchemas.numberProp,
        // Bulk operations (C++ TryGetStringField)
        prefix: commonSchemas.stringProp,
        suffix: commonSchemas.stringProp,
        searchText: commonSchemas.stringProp,
        replaceText: commonSchemas.stringProp,
        paths: commonSchemas.arrayOfStrings,
        // Source control (C++ TryGetStringField)
        description: commonSchemas.stringProp,
        checkoutFiles: commonSchemas.booleanProp,
        // Bulk delete
        showConfirmation: commonSchemas.booleanProp,
        // Material graph operations
        pinName: commonSchemas.pinName,
        materialPath: commonSchemas.materialPath,
        texturePath: commonSchemas.texturePath,
        coordinateIndex: commonSchemas.numberProp,
        parameterType: commonSchemas.stringProp,
        tags: commonSchemas.arrayOfStrings,
        // Handler aliases (alternative parameter names accepted by handler)
        folderPath: commonSchemas.directoryPath,
        type: commonSchemas.stringProp,
        defaultValue: commonSchemas.value,
        force: commonSchemas.booleanProp,
        recursive: commonSchemas.booleanProp,
        reportType: commonSchemas.stringProp,
        pattern: commonSchemas.stringProp,
        replacement: commonSchemas.stringProp,
        materialDomain: commonSchemas.stringProp,
        blendMode: commonSchemas.stringProp,
        shadingModel: commonSchemas.stringProp,
        domain: commonSchemas.stringProp,
        twoSided: commonSchemas.booleanProp,
        uTiling: commonSchemas.numberProp,
        vTiling: commonSchemas.numberProp,
        operation: commonSchemas.stringProp,
        constA: commonSchemas.numberProp,
        constB: commonSchemas.numberProp,
        code: commonSchemas.stringProp,
        outputType: commonSchemas.stringProp,
        inputs: commonSchemas.arrayOfObjects,
        additionalOutputs: commonSchemas.arrayOfObjects,
        group: commonSchemas.stringProp,
        sourcePin: commonSchemas.sourcePin,
        targetPin: commonSchemas.targetPin,
        direction: commonSchemas.stringProp,
        downstream: commonSchemas.booleanProp,
        startNodeId: commonSchemas.nodeId,
        endPin: commonSchemas.pinName,
        orphansOnly: commonSchemas.booleanProp,
        functionPath: commonSchemas.assetPath,
        inputType: commonSchemas.stringProp,
        instancePath: commonSchemas.assetPath,
        layerName: commonSchemas.stringProp,
        blendType: commonSchemas.stringProp,
        layers: commonSchemas.arrayOfObjects,
        nodeIds: commonSchemas.arrayOfStrings,
        sourceTexture: commonSchemas.texturePath,
        strength: commonSchemas.numberProp,
        scale: commonSchemas.numberProp,
        octaves: commonSchemas.numberProp,
        samples: commonSchemas.numberProp,
        newWidth: commonSchemas.numberProp,
        newHeight: commonSchemas.numberProp,
        filterMethod: commonSchemas.stringProp,
        inBlack: commonSchemas.numberProp,
        inWhite: commonSchemas.numberProp,
        gamma: commonSchemas.numberProp,
        curvePoints: commonSchemas.arrayOfObjects,
        amount: commonSchemas.numberProp,
        radius: commonSchemas.numberProp,
        channel: commonSchemas.stringProp,
        redTexture: commonSchemas.texturePath,
        greenTexture: commonSchemas.texturePath,
        blueTexture: commonSchemas.texturePath,
        baseTexture: commonSchemas.texturePath,
        blendTexture: commonSchemas.texturePath,
        opacity: commonSchemas.numberProp,
        compressionSettings: commonSchemas.stringProp,
        textureGroup: commonSchemas.stringProp,
        lodBias: commonSchemas.numberProp,
        virtualTextureStreaming: commonSchemas.booleanProp,
        neverStream: commonSchemas.booleanProp,
        streamingPriority: commonSchemas.numberProp,
        speed: commonSchemas.numberProp,
        speedX: commonSchemas.numberProp,
        speedY: commonSchemas.numberProp,
        levels: commonSchemas.numberProp,
        // Struct authoring (first-class Blueprint Struct support, issue #510)
        structPath: { type: 'string', description: 'Asset path of the Blueprint Struct (e.g. /Game/Structs/S_MyStruct).' },
        otherStructPath: { type: 'string', description: 'Second struct path for compare_structs.' },
        memberName: { type: 'string', description: 'Member (variable) name to add/rename/remove.' },
        newMemberName: { type: 'string', description: 'New member name (rename_struct_member).' },
        memberType: { type: 'string', description: 'Unreal property type for the member: Bool, Int, Float, String, Name, Text, Vector, Rotator, Transform, Object, SoftObject, Class, SoftClass, Enum:<Name>, Struct:<Path>, or with container prefix Array:..., Set:..., Map:<K>,<V>:' },
        varGuid: { type: 'string', description: 'Stable member GUID (from list_struct_members) identifying the member.' },
        tooltip: { type: 'string', description: 'Member tooltip (set_struct_member_metadata).' },
        position: { type: 'string', enum: ['first', 'last', 'before', 'after'], description: 'Reorder anchor position (reorder_struct_members).' },
        relativeTo: { type: 'string', description: 'Target member GUID/name to reorder relative to (reorder_struct_members position before/after).' },
        searchScope: { type: 'string', description: 'Optional path scope for search_struct_usage.' },
        destinationName: { type: 'string', description: 'New asset name for duplicate_struct (without path).' },
        members: {
          type: 'array', description: 'Member definitions for import_struct / create_struct. Each entry accepts either the short form { name, type, default?, tooltip?, metadata? } or the add_struct_member form { memberName, memberType, defaultValue?, tooltip?, metadata? }. type/memberType use the same grammar as memberType (Struct:<Path> for nested structs, Array:/Set:/Map: containers). Invalid members cause the whole request to be rejected before any change is made.',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Member name (short form). Alias: memberName.' },
              memberName: { type: 'string', description: 'Member name (add_struct_member form). Alias: name.' },
              type: { type: 'string', description: 'Unreal property type (same grammar as memberType, including Struct:<Path> for nested structs). Alias: memberType.' },
              memberType: { type: 'string', description: 'Unreal property type (add_struct_member form). Alias: type.' },
              defaultValue: { type: 'string', description: 'Optional default value as a string (same format as add_struct_member defaultValue). Alias: default.' },
              default: { type: 'string', description: 'Optional default value as a string (short form). Alias: defaultValue.' },
              tooltip: { type: 'string', description: 'Optional member tooltip.' },
              metadata: { type: 'object', description: 'Optional metadata key/value pairs.' }
            },
            required: []
          }
        },
      // Struct ecosystem — DataTable / Enum / FInstancedStruct (issue #struct-ecosystem)
      dataTablePath: { type: 'string', description: 'Asset path of the DataTable (e.g. /Game/DataTables/DT_MyTable).' },
      rowStructPath: { type: 'string', description: 'Asset path of the row UScriptStruct bound to a DataTable.' },
      rowName: { type: 'string', description: 'Name of the row to add/get/update/delete in a DataTable.' },
      rowData: commonSchemas.objectProp,
      rows: commonSchemas.arrayOfObjects,
      clearExisting: commonSchemas.booleanProp,
      enumPath: { type: 'string', description: 'Asset path of the UserDefinedEnum (e.g. /Game/Enums/E_MyEnum).' },
      valueName: { type: 'string', description: 'Enum value (entry) name.' },
      newValueName: { type: 'string', description: 'New enum value name (rename_enum_value).' },
      newEnumName: { type: 'string', description: 'Name for the new enum produced by split_enum.' },
      order: commonSchemas.arrayOfStrings,
      index: commonSchemas.numberProp,
      key: { type: 'string', description: 'Metadata key for set_enum_value_metadata.' },
      values: commonSchemas.arrayOfStrings,
      propertyName: commonSchemas.propertyName,
      structType: { type: 'string', description: 'Asset path of the inner UScriptStruct for an FInstancedStruct property (set_instanced_struct_property).' },
      structValues: { type: 'object', additionalProperties: true, description: 'Field-name to value map applied to the inner UScriptStruct when setting an FInstancedStruct property (set_instanced_struct_property).' },
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        assets: commonSchemas.arrayOfObjects,
        paths: commonSchemas.arrayOfStrings,
        path: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        details: commonSchemas.objectProp,
        totalCount: commonSchemas.numberProp,
        offset: commonSchemas.numberProp,
        limit: commonSchemas.numberProp
      }
    }
  };
