/**
 * AI (C30 / O30) and GAS (C19 / O22) route dispositions.
 * Every row cites a concrete .cpp file (v2 source-derived).
 */
import { type RawRouteDisposition, ROUTE_EVIDENCE_PATHS } from './routedispositions-paths.js';

const { AI_HANDLERS, AI_PERCEPTION, AI_NAVIGATION, GAS_SETS, GAS_GRANT, GAS_POLICY } = ROUTE_EVIDENCE_PATHS;

export const AI_GAS_ROUTE_DISPOSITIONS: readonly RawRouteDisposition[] = [
  {
    key: 'route:ai:create_nav_modifier',
    route: 'create_nav_modifier',
    domain: 'ai',
    status: 'hidden',
    owner: 'AI',
    evidenceSource: AI_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("create_nav_modifier")',
    evidenceTool: 'manage_ai',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_ai:create_nav_modifier',
    rationale: 'C30/O30: concrete native manage_ai route absent from canonical discovery; promote.',
  },
  {
    key: 'route:ai:set_ai_movement',
    route: 'set_ai_movement',
    domain: 'ai',
    status: 'hidden',
    owner: 'AI',
    evidenceSource: AI_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("set_ai_movement")',
    evidenceTool: 'manage_ai',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_ai:set_ai_movement',
    rationale: 'C30/O30: concrete native manage_ai route absent from canonical discovery; promote.',
  },
  {
    key: 'route:ai:set_ai_perception',
    route: 'set_ai_perception',
    domain: 'ai',
    status: 'hidden',
    owner: 'AI',
    evidenceSource: AI_PERCEPTION,
    evidenceSymbol: 'SubAction == TEXT("set_ai_perception")',
    evidenceTool: 'manage_ai',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_ai:set_ai_perception',
    rationale: 'C30/O30: concrete native manage_ai route absent from canonical discovery; promote.',
  },
  {
    key: 'route:ai:create_nav_link_proxy',
    route: 'create_nav_link_proxy',
    domain: 'ai',
    status: 'hidden',
    owner: 'AI',
    evidenceSource: AI_NAVIGATION,
    evidenceSymbol: 'SubAction == TEXT("create_nav_link_proxy")',
    evidenceTool: 'manage_navigation',
    disposition: 'map',
    targetCanonicalId: 'cap:manage_navigation:create_nav_link_proxy',
    rationale:
      'C30/O30: canonical and live through navigation pre-routing; its AI-local branches are shadowed. Map to the live navigation id.',
  },
  {
    key: 'route:gas:create_ability_set',
    route: 'create_ability_set',
    domain: 'gas',
    status: 'hidden',
    owner: 'GAS',
    evidenceSource: GAS_SETS,
    evidenceSymbol: 'SubAction == TEXT("create_ability_set")',
    evidenceTool: 'manage_gas',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_gas:create_ability_set',
    rationale: 'C19/O22: hidden native GAS leaf absent from TS/native action enum; promote.',
  },
  {
    key: 'route:gas:add_ability',
    route: 'add_ability',
    domain: 'gas',
    status: 'hidden',
    owner: 'GAS',
    evidenceSource: GAS_SETS,
    evidenceSymbol: 'SubAction == TEXT("add_ability")',
    evidenceTool: 'manage_gas',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_gas:add_ability',
    rationale: 'C19/O22: hidden native GAS leaf absent from TS/native action enum; promote.',
  },
  {
    key: 'route:gas:grant_ability',
    route: 'grant_ability',
    domain: 'gas',
    status: 'hidden',
    owner: 'GAS',
    evidenceSource: GAS_GRANT,
    evidenceSymbol: 'SubAction == TEXT("grant_ability")',
    evidenceTool: 'manage_gas',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_gas:grant_ability',
    rationale: 'C19/O22: hidden native GAS leaf absent from TS/native action enum; promote.',
  },
  {
    key: 'route:gas:create_execution_calculation',
    route: 'create_execution_calculation',
    domain: 'gas',
    status: 'hidden',
    owner: 'GAS',
    evidenceSource: GAS_GRANT,
    evidenceSymbol: 'SubAction == TEXT("create_execution_calculation")',
    evidenceTool: 'manage_gas',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_gas:create_execution_calculation',
    rationale: 'C19/O22: hidden native GAS leaf absent from TS/native action enum; promote.',
  },
  {
    key: 'route:gas:set_activation_policy',
    route: 'set_activation_policy',
    domain: 'gas',
    status: 'raw',
    owner: 'GAS',
    evidenceSource: GAS_POLICY,
    evidenceSymbol: 'SubAction == TEXT("set_activation_policy")',
    evidenceTool: 'manage_gas',
    disposition: 'map',
    targetCanonicalId: 'cap:manage_gas:set_activation_policy',
    rationale:
      'C19/O22: native reads BOTH the raw activationPolicy field and the normalized policy; map to canonical id with raw-field handling documented.',
  },
];
