/**
 * Geometry (C25 / C26) route dispositions.
 * Every row cites the concrete GeometryHandlers.cpp file (v2 source-derived).
 */
import { type RawRouteDisposition, ROUTE_EVIDENCE_PATHS } from './routedispositions-paths.js';

const { GEOMETRY_HANDLERS } = ROUTE_EVIDENCE_PATHS;

export const GEOMETRY_ROUTE_DISPOSITIONS: readonly RawRouteDisposition[] = [
  {
    key: 'route:geometry:difference',
    route: 'difference',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("difference") -> HandleBooleanSubtract',
    evidenceTool: 'manage_geometry',
    disposition: 'map',
    targetCanonicalId: 'cap:manage_geometry:difference',
    rationale:
      'C25/O29: twelve raw-only Geometry actions; difference is an exact boolean_subtract alias. Map to canonical id.',
  },
  {
    key: 'route:geometry:bridge',
    route: 'bridge',
    domain: 'geometry',
    status: 'hidden',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("bridge") -> HandleBridge',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:bridge',
    rationale: 'C26/O29: pre-5.5 bridge fills holes and ignores subdivisions; version-dependent partial; promote with version gate.',
  },
  {
    key: 'route:geometry:loft',
    route: 'loft',
    domain: 'geometry',
    status: 'hidden',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("loft") -> HandleLoft',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:loft',
    rationale: 'C26/O29: no-profile loft appends no geometry; version-dependent partial; promote with profile requirement.',
  },
  {
    key: 'route:geometry:create_procedural_mesh',
    route: 'create_procedural_mesh',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("create_procedural_mesh")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:create_procedural_mesh',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:append_triangle',
    route: 'append_triangle',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("append_triangle")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:append_triangle',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:append_vertex',
    route: 'append_vertex',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("append_vertex")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:append_vertex',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:set_uvs',
    route: 'set_uvs',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("set_uvs")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:set_uvs',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:set_vertex_color',
    route: 'set_vertex_color',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("set_vertex_color")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:set_vertex_color',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:split_normals',
    route: 'split_normals',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("split_normals")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:split_normals',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:delete_vertex',
    route: 'delete_vertex',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("delete_vertex")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:delete_vertex',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:delete_triangle',
    route: 'delete_triangle',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("delete_triangle")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:delete_triangle',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:get_vertex_position',
    route: 'get_vertex_position',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("get_vertex_position")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:get_vertex_position',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:set_vertex_position',
    route: 'set_vertex_position',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("set_vertex_position")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:set_vertex_position',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
  {
    key: 'route:geometry:translate_mesh',
    route: 'translate_mesh',
    domain: 'geometry',
    status: 'raw',
    owner: 'Geometry',
    evidenceSource: GEOMETRY_HANDLERS,
    evidenceSymbol: 'SubAction == TEXT("translate_mesh")',
    evidenceTool: 'manage_geometry',
    disposition: 'promote',
    targetCanonicalId: 'cap:manage_geometry:translate_mesh',
    rationale: 'C25/O29: raw-only DynamicMesh behavior (absent from every canonical parent); promote to manage_geometry.',
  },
];
