/**
 * Shared JSON-schema property fragments for gameplay capability records.
 *
 * Private to the gameplay domain. Plain JsonObject fragments consumed by
 * buildRecord input/output props; they do not touch the shared capability
 * model, schema, generator, or any aggregate code.
 */
import type { JsonObject } from '../../index.js';
import { bool, num, str, vec3 } from '../shared/schema-props.js';


export const P: PropertyMap = {
  action: str('The action to execute on the parent tool.'),
  name: str('Name for the created asset or actor.'),
  path: str('Canonical /Game output path for the created asset.'),
  assetPath: str('Canonical /Game asset path.'),
  blueprintPath: str('Canonical /Game Blueprint asset path.'),
  skeletalMeshPath: str('Canonical /Game SkeletalMesh asset path.'),
  physicsAssetPath: str('Canonical /Game PhysicsAsset path.'),
  skeletonPath: str('Canonical /Game Skeleton asset path.'),
  animationPath: str('Canonical /Game Animation asset path.'),
  actorName: str('Target actor name in the current level.'),
  boneName: str('Target bone name.'),
  socketName: str('Target socket name.'),
  meshPath: str('Canonical /Game mesh asset path.'),
  location: vec3('World or relative location as [x, y, z].'),
  rotation: vec3('Rotation as [pitch, yaw, roll] in degrees.'),
  value: { description: 'Property value (any type).' },
  num_: num('Numeric parameter.'),
  bool_: bool('Boolean parameter.'),
  string_: str('String parameter.'),
  arrayOfStrings: {
    type: 'array',
    items: { type: 'string' },
    description: 'List of string values.',
  },
  effectPath: str('Canonical /Game gameplay effect asset path.'),
  abilityPath: str('Canonical /Game gameplay ability asset path.'),
  attributeSetPath: str('Canonical /Game attribute set asset path.'),
  cuePath: str('Canonical /Game gameplay cue asset path.'),
  weaponBlueprintPath: str('Canonical /Game weapon Blueprint asset path.'),
  damageTypePath: str('Canonical /Game damage type asset path.'),
  projectileBlueprintPath: str('Canonical /Game projectile Blueprint asset path.'),
  controllerPath: str('Canonical /Game AI controller asset path.'),
  behaviorTreePath: str('Canonical /Game Behavior Tree asset path.'),
  blackboardPath: str('Canonical /Game Blackboard asset path.'),
  stateTreePath: str('Canonical /Game State Tree asset path.'),
  smartObjectPath: str('Canonical /Game Smart Object asset path.'),
  navMeshPath: str('Canonical /Game NavMesh settings asset path.'),
  inventoryPath: str('Canonical /Game inventory asset path.'),
  itemPath: str('Canonical /Game item definition asset path.'),
  lootTablePath: str('Canonical /Game loot table asset path.'),
  interactablePath: str('Canonical /Game interactable asset path.'),
  save: bool('Persist the created/modified asset to disk.'),
  overwrite: bool('Overwrite an existing asset with the same name.'),
  amount: num('Amount to apply (damage, heal, armor, shield).'),
  magnitude: num('Magnitude of the modifier or effect.'),
  duration: num('Duration in seconds.'),
  time: num('Time in seconds.'),
  startTime: num('Start time in seconds.'),
  endTime: num('End time in seconds.'),
  blendTime: num('Blend duration in seconds.'),
  frame: num('Frame index.'),
  length: num('Sequence length.'),
  frameRate: num('Frames per second.'),
  minValue: num('Minimum numeric value.'),
  maxValue: num('Maximum numeric value.'),
  sampleValue: num('Blend sample coordinate.'),
  threshold: num('Numeric threshold.'),
  rate: num('Rate value.'),
  count: num('Count value.'),
  mass: num('Mass value.'),
  playRate: num('Playback rate.'),
  linearDamping: num('Linear damping value.'),
  angularDamping: num('Angular damping value.'),
  dragCoefficient: num('Drag coefficient.'),
  tag: str('Gameplay tag string.'),
  attributeName: str('Target attribute name.'),
  modifierOp: str('Modifier operation (Add, Multiply, Override, ...).'),
  damage: num('Damage amount to apply.'),
  heal: num('Health amount to restore.'),
  shield: num('Shield amount to grant.'),
  armor: num('Armor value to modify.'),
  radius: num('Radius in world units.'),
  speed: num('Speed value.'),
  nodeName: str('Graph node name.'),
  propertyName: str('Property name.'),
  machineName: str('State machine name.'),
  stateName: str('State name.'),
  fromState: str('Source state name.'),
  toState: str('Target state name.'),
  cacheName: str('Cached pose name.'),
  slotName: str('Slot name.'),
  sectionName: str('Montage section name.'),
  fromSection: str('Source montage section.'),
  toSection: str('Target montage section.'),
  notifyName: str('Animation notify name.'),
  markerName: str('Animation sync marker name.'),
  curveName: str('Animation curve name.'),
  axisName: str('Axis name.'),
  interpolationType: str('Interpolation mode.'),
  sourceChain: str('Source retarget chain.'),
  targetChain: str('Target retarget chain.'),
  parentBoneName: str('Parent bone name.'),
  newBoneName: str('Replacement bone name.'),
  sourceBoneName: str('Source bone name.'),
  targetBoneName: str('Target bone name.'),
  morphTargetName: str('Morph target name.'),
  virtualBoneName: str('Virtual bone name.'),
  addMissing: bool('Whether to add the morph target when the component does not already carry it.'),
  vehicleType: str('Vehicle type.'),
  bodyA: str('First physics body.'),
  bodyB: str('Second physics body.'),
  activate: bool('Whether to activate the target.'),
  simulatePhysics: bool('Whether physics simulation is enabled.'),
  collisionEnabled: bool('Whether collision is enabled.'),
  compileReferencers: bool('Whether referring assets are compiled.'),
  rebuildBlendParameters: bool('Whether blend parameters are rebuilt.'),
  weights: { type: 'array', items: { type: 'number' }, description: 'Numeric weights.' },
  deltas: { type: 'array', items: { type: 'object' }, description: 'Morph target deltas.' },
  limits: { type: 'object', additionalProperties: true, description: 'Constraint limits.' },
  settings: { description: 'Structured settings object (any type).', additionalProperties: true, type: 'object' },
  properties: {
    type: 'object',
    description: 'Key-value property map.',
    additionalProperties: true,
    'x-unreal-reflection-boundary': true,
  },
};

export type PropertyMap = Record<string, JsonObject>;
