/**
 * Console/cvar/display records: show_fps, profile, set_quality,
 * execute_command, console_command, set_cvar, set_resolution, set_fullscreen.
 *
 * All eight route through local TS handlers that dispatch to the
 * `console_command` bridge action (dispatchMode 'local'). Console command
 * strings are enforced by CommandValidator before dispatch. Grounded in
 * system-display-handlers.ts and system-console-handlers.ts.
 *
 * Per normalization-inventory.json: console_command and execute_command are
 * true duplicates (cap:shared:console_command, cap:shared:execute_command)
 * shared with control_editor; system_control is the alias occurrence
 * (class A, disposition alias). The remaining six are distinct system_control
 * targets (class C, retain).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;
const NR = 'Distinct system_control console/cvar target with a unique CVar or display command.';
const A_DUPLICATE = 'A_TRUE_DUPLICATE' as const;
const CMD_ALIAS_NR =
  'True duplicate (cap:shared:console_command) shared with control_editor; system_control is the alias occurrence per the normalization inventory. Console command path enforced by CommandValidator: blocks dangerous commands, Python, shell chaining, and injection tokens before dispatch to the console_command bridge action.';
const EXEC_ALIAS_NR =
  'True duplicate (cap:shared:execute_command) shared with control_editor; system_control is the alias occurrence per the normalization inventory. Console command path enforced by CommandValidator: blocks dangerous commands, Python, shell chaining, and injection tokens before dispatch to the console_command bridge action.';

export const CONSOLE_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'show_fps',
    domain: 'console',
    family: 'console',
    summary: 'Toggle the FPS HUD overlay via the stat fps console command.',
    whenToUse: ['The frames-per-second counter should be shown or hidden.'],
    whenNotToUse: ['Detailed per-category stats are needed (use show_stats).'],
    inputProps: { enabled: { type: 'boolean', description: 'Show (true) or hide (false) the FPS overlay.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'show_fps', enabled: true },
    exampleOutput: { success: true, message: 'FPS display enabled' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'profile',
    domain: 'console',
    family: 'console',
    summary: 'Toggle a profiling stat display (CPU, GPU, memory, render/game thread) via console command.',
    whenToUse: ['A specific engine profiling stat overlay must be enabled.'],
    whenNotToUse: ['A structured profiling capture is needed (use start_profiling).'],
    inputProps: {
      profileType: { type: 'string', enum: ['CPU', 'GPU', 'Memory', 'RenderThread', 'GameThread', 'All'], description: 'Profiling domain to display.' },
      enabled: { type: 'boolean', description: 'Enable (true) or disable (false) the display.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'profile', profileType: 'GPU' },
    exampleOutput: { success: true, message: 'Profiling enabled (GPU)' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_quality',
    domain: 'console',
    family: 'console',
    summary: 'Set an engine scalability quality CVar (sg.*Quality) for a category and level.',
    whenToUse: ['A scalability quality group must be changed at runtime.'],
    whenNotToUse: ['Full scalability state must be set atomically (use set_scalability).'],
    inputProps: {
      category: { type: 'string', description: 'Scalability category (shadow, texture, effect, postprocess, foliage, shading, viewdistance, ...).' },
      level: { type: 'number', description: 'Quality level 0-4 (low to cinematic).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'set_quality', category: 'shadow', level: 3 },
    exampleOutput: { success: true, message: 'shadow quality set to 3 via sg.ShadowQuality' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'execute_command',
    domain: 'console',
    family: 'console',
    summary: 'Execute a single validated console command string on the engine.',
    whenToUse: ['An arbitrary console command must be run and its result returned.'],
    whenNotToUse: ['A dedicated system_control action exists for the operation.'],
    inputProps: { command: { type: 'string', description: 'The console command string to execute.' } },
    required: ['command'],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'execute_command', command: 'stat unit' },
    exampleOutput: { success: true, message: 'Command executed', command: 'stat unit', output: 'Stat: 0.5ms' },
    outputProps: { command: { type: 'string', description: 'The command that was executed.' }, output: { type: 'string', maxLength: 4096, description: 'Bounded console output captured from the command.' } },
    outputRequired: ['command'],
    normalizationClass: A_DUPLICATE,
    normalizationDisposition: 'alias',
    normalizationRationale: EXEC_ALIAS_NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'console_command',
    domain: 'console',
    family: 'console',
    summary: 'Execute a validated, non-empty console command (empty input is rejected).',
    whenToUse: ['A console command must be run with explicit empty-input rejection.'],
    whenNotToUse: ['The command is empty or whitespace-only.'],
    inputProps: { command: { type: 'string', description: 'The non-empty console command to execute.' } },
    required: ['command'],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'console_command', command: 'r.ScreenPercentage 100' },
    exampleOutput: { success: true, message: 'Command executed', command: 'r.ScreenPercentage 100', output: '' },
    outputProps: { command: { type: 'string', description: 'The command that was executed.' }, output: { type: 'string', maxLength: 4096, description: 'Bounded console output captured from the command.' } },
    outputRequired: ['command'],
    normalizationClass: A_DUPLICATE,
    normalizationDisposition: 'alias',
    normalizationRationale: CMD_ALIAS_NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_cvar',
    domain: 'console',
    family: 'console',
    topics: ['console variable', 'cvar', 'set console variable', 'engine setting', 'rendering setting'],
    summary: 'Set a console variable value, derived from name/cvar/key/command plus value.',
    whenToUse: ['A single CVar must be set to a value.'],
    whenNotToUse: ['The target is a scalability group (use set_quality) or a full command (use execute_command).'],
    inputProps: {
      name: { type: 'string', description: 'CVar name (alternatively cvar, key, or command).' },
      cvar: { type: 'string', description: 'Alternate CVar name field.' },
      key: { type: 'string', description: 'Alternate CVar name field.' },
      command: { type: 'string', description: 'Alternate CVar name field (parsed as name + value).' },
      value: { type: 'string', description: 'Value to assign to the CVar.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'set_cvar', name: 'r.VSync', value: '1' },
    exampleOutput: { success: true, message: 'CVar r.VSync set to 1' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_resolution',
    domain: 'console',
    family: 'console',
    summary: 'Set the screen resolution via the r.SetRes console command.',
    whenToUse: ['The editor window resolution must be changed.'],
    whenNotToUse: ['Only the render resolution scale is needed (use set_resolution_scale).'],
    inputProps: {
      resolution: { type: 'string', description: 'Resolution as WxH (e.g. 1920x1080).' },
      width: { type: 'number', description: 'Width in pixels.' },
      height: { type: 'number', description: 'Height in pixels.' },
      windowed: { type: 'boolean', description: 'Windowed (true) or fullscreen (false).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'set_resolution', width: 1920, height: 1080, windowed: true },
    exampleOutput: { success: true, message: 'Resolution set to 1920x1080 (windowed)' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_fullscreen',
    domain: 'console',
    family: 'console',
    summary: 'Toggle fullscreen mode via r.SetRes or r.FullScreenMode console command.',
    whenToUse: ['The editor must switch between windowed and fullscreen modes.'],
    whenNotToUse: ['A specific resolution is required without mode change (use set_resolution).'],
    inputProps: {
      resolution: { type: 'string', description: 'Resolution as WxH (e.g. 1920x1080).' },
      width: { type: 'number', description: 'Width in pixels.' },
      height: { type: 'number', description: 'Height in pixels.' },
      enabled: { type: 'boolean', description: 'Fullscreen (true) or windowed (false).' },
      windowed: { type: 'boolean', description: 'Force windowed (true) or fullscreen (false).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'console_command',
    dispatchMode: 'local',
    exampleInput: { action: 'set_fullscreen', enabled: true, width: 1920, height: 1080 },
    exampleOutput: { success: true, message: 'Fullscreen mode set to 1920x1080 (fullscreen)' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
];
