/**
 * Insights/trace records (10): start_session, start_unreal_insights,
 * capture_insights_trace, get_trace_status, pause_session, resume_session,
 * stop_session, write_snapshot, send_snapshot, analyze_trace.
 *
 * All route through the orchestrator's insights branch, which validates
 * trace channel characters then dispatches to the manage_insights bridge
 * action (dispatchMode 'local'). Network traces are restricted to loopback
 * hosts by the bridge. Grounded in consolidated-handler-registration.ts
 * and the native HandleInsightsAction path.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const DOM = 'insights';
const FAM = 'insights';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;
const NR = 'Distinct system_control insights/trace lifecycle operation with a unique session or snapshot target. Channel characters are validated before dispatch to manage_insights.';

export const INSIGHTS_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'start_session',
    domain: DOM,
    family: FAM,
    summary: 'Start an Unreal Insights trace session.',
    whenToUse: ['A new trace session must be started.'],
    whenNotToUse: ['A session is already running (use pause/resume/stop).'],
    inputProps: {
      channels: { type: 'string', description: 'Trace channels (validated: letters, digits, underscore, comma, space, hyphen).' },
      connectionType: { type: 'string', enum: ['file', 'network'], description: 'Trace connection type; network is restricted to loopback.' },
      host: { type: 'string', description: 'Trace host (loopback for network).' },
      port: { type: 'number', description: 'Trace port.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'start_session', connectionType: 'file' },
    exampleOutput: { success: true, message: 'Trace session started' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'start_unreal_insights',
    domain: DOM,
    family: FAM,
    summary: 'Start an Unreal Insights trace session; pass launchViewer to also open the Unreal Insights application on it.',
    whenToUse: ['The Insights GUI must be launched for trace analysis.'],
    whenNotToUse: ['Only a trace session is needed (use start_session).'],
    inputProps: {
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
      launchViewer: { type: 'boolean', description: 'Also open the Unreal Insights application on the new trace (default false).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'start_unreal_insights' },
    exampleOutput: { success: true, message: 'Unreal Insights launched' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'capture_insights_trace',
    domain: DOM,
    family: FAM,
    summary: 'Capture an Unreal Insights trace to a file or network endpoint.',
    whenToUse: ['A trace must be captured for later analysis.'],
    whenNotToUse: ['A live session without capture is sufficient (use start_session).'],
    inputProps: {
      traceFile: { type: 'string', description: 'Output trace file path.' },
      tracePath: { type: 'string', description: 'Output trace directory path.' },
      connectionType: { type: 'string', enum: ['file', 'network'], description: 'Trace connection type; network is restricted to loopback.' },
      channels: { type: 'string', description: 'Trace channels (validated).' },
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'capture_insights_trace', connectionType: 'file', traceFile: '/Game/Trace/cap.utrace' },
    exampleOutput: { success: true, message: 'Trace captured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'get_trace_status',
    domain: DOM,
    family: FAM,
    summary: 'Query the current trace session status.',
    whenToUse: ['The active trace session status must be read.'],
    whenNotToUse: ['A new session must be started (use start_session).'],
    inputProps: {},
    required: [],
    // Native HandleGetTraceStatus (InsightsTraceState.cpp:118-131) emits the
    // AddTraceStatus block (InsightsRequests.cpp:176-235): connected, destination,
    // sessionGuid/traceGuid (when connected), activeChannels, connectionType,
    // traceSystemStatus, paused, statusQuerySupported. Declared exactly — the
    // empty schema previously made a real status response look like a bare ack.
    outputProps: {
      connected: { type: 'boolean', description: 'Whether a trace consumer is connected.' },
      destination: { type: 'string', description: 'Trace destination string.' },
      sessionGuid: { type: 'string', description: 'Session guid (when connected).' },
      traceGuid: { type: 'string', description: 'Trace guid (when connected).' },
      activeChannels: { type: 'string', description: 'Active trace channels.' },
      connectionType: { type: 'string', description: 'Connection type: none, file, network, relay, or secure_network.' },
      traceSystemStatus: { type: 'string', description: 'Trace system status (e.g. available, tracing_to_file).' },
      paused: { type: 'boolean', description: 'Whether tracing is paused.' },
      statusQuerySupported: { type: 'boolean', description: 'Whether this engine version supports status queries.' },
    },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'get_trace_status' },
    exampleOutput: { success: true, message: 'Trace status retrieved' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'pause_session',
    domain: DOM,
    family: FAM,
    summary: 'Pause the active trace session.',
    whenToUse: ['Trace capture must be temporarily suspended.'],
    whenNotToUse: ['The session should be stopped entirely (use stop_session).'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'pause_session' },
    exampleOutput: { success: true, message: 'Session paused' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'resume_session',
    domain: DOM,
    family: FAM,
    summary: 'Resume a paused trace session.',
    whenToUse: ['A paused trace session must continue capturing.'],
    whenNotToUse: ['No session is paused.'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'resume_session' },
    exampleOutput: { success: true, message: 'Session resumed' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'stop_session',
    domain: DOM,
    family: FAM,
    summary: 'Stop the active trace session.',
    whenToUse: ['The trace session must be terminated.'],
    whenNotToUse: ['The session should only be paused (use pause_session).'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'stop_session' },
    exampleOutput: { success: true, message: 'Session stopped' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'write_snapshot',
    domain: DOM,
    family: FAM,
    summary: 'Write a trace snapshot to a snapshot path.',
    whenToUse: ['A point-in-time trace snapshot must be written to disk.'],
    whenNotToUse: ['The snapshot should be sent to a running trace (use send_snapshot).'],
    inputProps: {
      snapshotPath: { type: 'string', description: 'Output snapshot path.' },
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'write_snapshot', snapshotPath: '/Game/Trace/snap.utrace' },
    exampleOutput: { success: true, message: 'Snapshot written' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'send_snapshot',
    domain: DOM,
    family: FAM,
    summary: 'Send a trace snapshot to a running trace session.',
    whenToUse: ['A snapshot must be forwarded to an active trace session.'],
    whenNotToUse: ['The snapshot should be persisted to disk (use write_snapshot).'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'send_snapshot' },
    exampleOutput: { success: true, message: 'Snapshot sent' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'analyze_trace',
    domain: DOM,
    family: FAM,
    summary: 'Analyze a captured trace and return summarized timing/counters.',
    whenToUse: ['A captured trace must be analyzed for timing or counter data.'],
    whenNotToUse: ['A live session status is needed (use get_trace_status).'],
    inputProps: { traceFile: { type: 'string', description: 'Trace file to analyze.' } },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_insights',
    dispatchMode: 'local',
    exampleInput: { action: 'analyze_trace', traceFile: '/Game/Trace/cap.utrace' },
    exampleOutput: { success: true, message: 'Trace analyzed' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
];
