/**
 * Performance records (part B, 9 of 19): configure_texture_streaming,
 * configure_lod, apply_baseline_settings, optimize_draw_calls, merge_actors,
 * configure_occlusion_culling, optimize_shaders, configure_nanite,
 * configure_world_partition.
 *
 * All route through the local handlePerformanceTools TS handler
 * (dispatchMode 'local'); each dispatches to its own bridge action name.
 * Grounded in performance/performance-handlers.ts. merge_actors requires an
 * actors array of at least two names and optimize_draw_calls falls back when
 * mergeActors is not requested.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const DOM = 'performance';
const FAM = 'performance';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;
const NR = 'Distinct system_control performance target with a unique CVar, optimization, or partition setting.';

export const PERFORMANCE_B_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'configure_texture_streaming',
    domain: DOM,
    family: FAM,
    summary: 'Configure texture streaming pool size and boost behavior via the configure_texture_streaming bridge action.',
    whenToUse: ['Texture streaming pool size or player-location boost must be tuned.'],
    whenNotToUse: ['A one-off texture import is the goal (use manage_asset).'],
    inputProps: {
      enabled: { type: 'boolean', description: 'Enable (true) or disable (false) streaming.' },
      poolSize: { type: 'number', description: 'Streaming pool size in MB.' },
      boostPlayerLocation: { type: 'boolean', description: 'Prioritize streaming around the player.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'configure_texture_streaming',
    dispatchMode: 'local',
    exampleInput: { action: 'configure_texture_streaming', enabled: true, poolSize: 4096 },
    exampleOutput: { success: true, message: 'Texture streaming configured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'configure_lod',
    domain: DOM,
    family: FAM,
    summary: 'Configure forced LOD and LOD bias via the configure_lod bridge action.',
    whenToUse: ['A forced LOD level or LOD bias must be applied.'],
    whenNotToUse: ['Per-actor LOD is the goal (use control_actor).'],
    inputProps: {
      forceLOD: { type: 'number', description: 'Forced LOD level.' },
      lodBias: { type: 'number', description: 'Additional LOD bias.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'configure_lod',
    dispatchMode: 'local',
    exampleInput: { action: 'configure_lod', lodBias: 1 },
    exampleOutput: { success: true, message: 'LOD configured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'apply_baseline_settings',
    domain: DOM,
    family: FAM,
    summary: 'Apply a named baseline performance profile via the apply_baseline_settings bridge action.',
    whenToUse: ['A predefined performance baseline profile must be applied.'],
    whenNotToUse: ['Individual CVars must be tuned (use set_cvar or set_scalability).'],
    inputProps: { profile: { type: 'string', description: 'Baseline profile name (default balanced).' } },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'apply_baseline_settings',
    dispatchMode: 'local',
    exampleInput: { action: 'apply_baseline_settings', profile: 'balanced' },
    exampleOutput: { success: true, message: 'Baseline settings applied' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'optimize_draw_calls',
    domain: DOM,
    family: FAM,
    summary: 'Optimize draw calls via instancing/batching unless merge_actors is requested.',
    whenToUse: ['Draw-call count must be reduced through instancing or batching.'],
    whenNotToUse: ['Actors should be merged into a single mesh (use merge_actors).'],
    inputProps: {
      enabled: { type: 'boolean', description: 'Enable optimization.' },
      enableBatching: { type: 'boolean', description: 'Enable batching.' },
      enableInstancing: { type: 'boolean', description: 'Enable instancing.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'optimize_draw_calls',
    dispatchMode: 'local',
    exampleInput: { action: 'optimize_draw_calls', enableInstancing: true },
    exampleOutput: { success: true, message: 'Draw calls optimized' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'merge_actors',
    domain: DOM,
    family: FAM,
    summary: 'Merge a set of actors into a single mesh (requires >=2 actor names) via the merge_actors bridge action.',
    whenToUse: ['Two or more actors must be merged into one mesh asset.'],
    whenNotToUse: ['Fewer than two actors are provided, or only instancing is needed (use optimize_draw_calls).'],
    inputProps: {
      actors: { type: 'array', items: { type: 'string' }, description: 'Actor names to merge (>=2 required).' },
      mergeActors: { type: 'boolean', description: 'Whether to merge source actors; forced true by the merge_actors action.' },
      enableInstancing: { type: 'boolean', description: 'Enable instancing on the merged mesh.' },
      replaceSourceActors: { type: 'boolean', description: 'Replace source actors in the level.' },
      packageName: { type: 'string', description: 'Package name for the merged asset.' },
      outputPath: { type: 'string', description: 'Output /Game folder for the merged asset.' },
    },
    required: ['actors'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'merge_actors',
    dispatchMode: 'local',
    exampleInput: { action: 'merge_actors', actors: ['Cube1', 'Cube2'], packageName: 'MergedCube' },
    exampleOutput: { success: true, message: 'Actors merged' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'configure_occlusion_culling',
    domain: DOM,
    family: FAM,
    summary: 'Configure occlusion culling via the configure_occlusion_culling bridge action.',
    whenToUse: ['Occlusion culling must be enabled or its parameters tuned.'],
    whenNotToUse: ['The scene is too small to benefit from occlusion culling.'],
    inputProps: {
      enabled: { type: 'boolean', description: 'Enable (true) or disable (false) occlusion culling.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'configure_occlusion_culling',
    dispatchMode: 'local',
    exampleInput: { action: 'configure_occlusion_culling', enabled: true },
    exampleOutput: { success: true, message: 'Occlusion culling configured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'optimize_shaders',
    domain: DOM,
    family: FAM,
    summary: 'Optimize shader compilation via the optimize_shaders bridge action.',
    whenToUse: ['Shader compilation must be optimized or force-recompiled.'],
    whenNotToUse: ['A full material recompile is needed (use manage_asset compile_material).'],
    inputProps: {
      mode: { type: 'string', description: 'Optimization mode.' },
      forceRecompile: { type: 'boolean', description: 'Force a shader recompile.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'optimize_shaders',
    dispatchMode: 'local',
    exampleInput: { action: 'optimize_shaders', forceRecompile: false },
    exampleOutput: { success: true, message: 'Shaders optimized' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'configure_nanite',
    domain: DOM,
    family: FAM,
    summary: 'Configure Nanite settings (enabled, max pixels per edge, streaming pool) via the configure_nanite bridge action.',
    whenToUse: ['Nanite must be enabled or its runtime parameters tuned.'],
    whenNotToUse: ['The target mesh is not Nanite-compatible.'],
    inputProps: {
      enabled: { type: 'boolean', description: 'Enable (true) or disable (false) Nanite.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'configure_nanite',
    dispatchMode: 'local',
    exampleInput: { action: 'configure_nanite', enabled: true },
    exampleOutput: { success: true, message: 'Nanite configured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'configure_world_partition',
    domain: DOM,
    family: FAM,
    summary: 'Configure world partition (enabled, cell size, loading range) via the configure_world_partition bridge action.',
    whenToUse: ['World Partition runtime settings must be tuned.'],
    whenNotToUse: ['Level streaming is managed per-sublevel (use manage_level).'],
    inputProps: {
      enabled: { type: 'boolean', description: 'Enable (true) or disable (false) world partition.' },
      cellSize: { type: 'number', description: 'Partition cell size.' },
      streamingDistance: { type: 'number', description: 'Loading/streaming range.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'configure_world_partition',
    dispatchMode: 'local',
    exampleInput: { action: 'configure_world_partition', enabled: true, cellSize: 65536 },
    exampleOutput: { success: true, message: 'World partition configured' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
];
