/**
 * Performance records (part A, 10 of 19): start_profiling, stop_profiling,
 * run_benchmark, show_stats, generate_memory_report, set_scalability,
 * set_resolution_scale, set_vsync, set_frame_rate_limit, enable_gpu_timing.
 *
 * All route through the local handlePerformanceTools TS handler
 * (dispatchMode 'local'); each dispatches to its own bridge action name
 * except enable_gpu_timing which dispatches to manage_performance.
 * Grounded in performance/performance-handlers.ts. run_benchmark is the
 * only long-running member of this shard.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const DOM = 'performance';
const FAM = 'performance';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;
const NR = 'Distinct system_control performance target with a unique CVar, metric, or scalability setting.';

export const PERFORMANCE_A_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'start_profiling',
    domain: DOM,
    family: FAM,
    summary: 'Start a structured profiling capture for a profiling type with an optional duration.',
    whenToUse: ['A named profiling capture must begin for CPU, GPU, memory, or thread analysis.'],
    whenNotToUse: ['Only an HUD stat overlay is needed (use profile or show_stats).'],
    inputProps: {
      type: { type: 'string', enum: ['CPU', 'GPU', 'Memory', 'RenderThread', 'GameThread', 'All', 'fps'], description: 'Profiling domain to capture.' },
      duration: { type: 'number', description: 'Optional capture duration in seconds.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'start_profiling',
    dispatchMode: 'local',
    exampleInput: { action: 'start_profiling', type: 'CPU', duration: 10 },
    exampleOutput: { success: true, message: 'Profiling started' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'stop_profiling',
    domain: DOM,
    family: FAM,
    summary: 'Stop the active structured profiling capture.',
    whenToUse: ['A profiling capture started by start_profiling must be stopped.'],
    whenNotToUse: ['No profiling capture is running.'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'stop_profiling',
    dispatchMode: 'local',
    exampleInput: { action: 'stop_profiling' },
    exampleOutput: { success: true, message: 'Profiling stopped' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'run_benchmark',
    domain: DOM,
    family: FAM,
    summary: 'Run an engine benchmark for a duration and return measured metrics.',
    whenToUse: ['A timed benchmark must be executed and its metrics collected.'],
    whenNotToUse: ['A continuous profiling capture is needed (use start_profiling).'],
    inputProps: {
      duration: { type: 'number', description: 'Benchmark duration in seconds (default 60).' },
      type: { type: 'string', description: 'Optional benchmark type.' },
    },
    required: [],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'medium',
    dispatchAction: 'run_benchmark',
    dispatchMode: 'local',
    exampleInput: { action: 'run_benchmark', duration: 30 },
    exampleOutput: { success: true, message: 'Benchmark complete' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'show_stats',
    domain: DOM,
    family: FAM,
    summary: 'Toggle a stat category HUD overlay (e.g. Unit, GPU) via the show_stats bridge action.',
    whenToUse: ['A specific stat category overlay must be shown or hidden.'],
    whenNotToUse: ['Only the FPS counter is needed (use show_fps).'],
    inputProps: {
      category: { type: 'string', description: 'Stat category to display (e.g. Unit, GPU).' },
      type: { type: 'string', description: 'Alternate category selector.' },
      enabled: { type: 'boolean', description: 'Show (true) or hide (false) the overlay.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'show_stats',
    dispatchMode: 'local',
    exampleInput: { action: 'show_stats', category: 'Unit', enabled: true },
    exampleOutput: { success: true, message: 'Stats display enabled for category: Unit' },
    normalizationClass: 'A_TRUE_DUPLICATE',
    normalizationDisposition: 'alias',
    normalizationRationale: 'True duplicate (cap:shared:show_stats) shared with control_editor; system_control is the alias occurrence per the normalization inventory.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'generate_memory_report',
    domain: DOM,
    family: FAM,
    summary: 'Generate an engine memory report, optionally detailed.',
    whenToUse: ['A snapshot of engine memory usage must be generated.'],
    whenNotToUse: ['Live HUD memory stats are sufficient (use show_stats with memory).'],
    inputProps: {
      detailed: { type: 'boolean', description: 'Produce a detailed report.' },
    },
    required: [],
    outputProps: {
      reportPath: { type: 'string', description: 'Absolute path to the generated .memreport file.' },
      reportDirectory: { type: 'string', description: 'Directory where memory reports are written.' },
    },
    outputRequired: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'generate_memory_report',
    dispatchMode: 'local',
    exampleInput: { action: 'generate_memory_report', detailed: true },
    exampleOutput: { success: true, message: 'Memory report generated', reportPath: 'Saved/Profiling/MemReports/Pid1234_12.34.56.memreport', reportDirectory: 'Saved/Profiling/MemReports' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_scalability',
    domain: DOM,
    family: FAM,
    summary: 'Set a scalability group level (0-4) for a category via the set_scalability bridge action.',
    whenToUse: ['A scalability group level must be changed atomically.'],
    whenNotToUse: ['A single CVar outside scalability groups is needed (use set_cvar).'],
    inputProps: {
      category: { type: 'string', description: 'Scalability category (default ViewDistance).' },
      level: { type: 'number', description: 'Level 0-4 (clamped).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'set_scalability',
    dispatchMode: 'local',
    exampleInput: { action: 'set_scalability', category: 'ViewDistance', level: 2 },
    exampleOutput: { success: true, message: 'Scalability set' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_resolution_scale',
    domain: DOM,
    family: FAM,
    summary: 'Set the render resolution scale (r.ScreenPercentage) via the set_resolution_scale bridge action.',
    whenToUse: ['The primary render resolution scale must be changed.'],
    whenNotToUse: ['The window resolution must change (use set_resolution).'],
    inputProps: { scale: { type: 'number', description: 'Resolution scale percentage.' } },
    required: ['scale'],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'set_resolution_scale',
    dispatchMode: 'local',
    exampleInput: { action: 'set_resolution_scale', scale: 100 },
    exampleOutput: { success: true, message: 'Resolution scale set' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_vsync',
    domain: DOM,
    family: FAM,
    summary: 'Enable or disable vertical sync via the set_vsync bridge action.',
    whenToUse: ['VSync must be toggled at runtime.'],
    whenNotToUse: ['A frame rate cap is the actual goal (use set_frame_rate_limit).'],
    inputProps: { enabled: { type: 'boolean', description: 'Enable (true) or disable (false) VSync.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'set_vsync',
    dispatchMode: 'local',
    exampleInput: { action: 'set_vsync', enabled: true },
    exampleOutput: { success: true, message: 'VSync enabled' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_frame_rate_limit',
    domain: DOM,
    family: FAM,
    summary: 'Set the engine frame rate cap via the set_frame_rate_limit bridge action.',
    whenToUse: ['A maximum FPS cap must be applied.'],
    whenNotToUse: ['VSync should be used instead for display-synced limiting.'],
    inputProps: { maxFPS: { type: 'number', description: 'Maximum frames per second.' } },
    required: ['maxFPS'],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'set_frame_rate_limit',
    dispatchMode: 'local',
    exampleInput: { action: 'set_frame_rate_limit', maxFPS: 60 },
    exampleOutput: { success: true, message: 'Frame rate limit set' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'enable_gpu_timing',
    domain: DOM,
    family: FAM,
    summary: 'Toggle GPU timing instrumentation via the manage_performance bridge action (subAction enable_gpu_timing).',
    whenToUse: ['Per-frame GPU timing instrumentation must be enabled or disabled.'],
    whenNotToUse: ['A full profiling capture is needed (use start_profiling).'],
    inputProps: { enabled: { type: 'boolean', description: 'Enable (true) or disable (false) GPU timing.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_performance',
    dispatchMode: 'local',
    exampleInput: { action: 'enable_gpu_timing', enabled: true },
    exampleOutput: { success: true, message: 'GPU timing enabled' },
    normalizationClass: NC,
    normalizationRationale: NR,
  }),
];
