/**
 * System operations records (12): run_ubt, package_project, package_status,
 * run_tests, subscribe, unsubscribe, spawn_category, execute_python,
 * set_project_setting, get_project_settings, validate_assets,
 * lumen_update_scene.
 *
 * Routing is mixed and grounded in consolidated-handler-registration.ts:
 * - run_ubt: local TS spawn with manage_pipeline bridge fallback (long-running).
 * - package_project/package_status: fallback tool dispatch to system_control ->
 *   native HandlePackageProject / HandlePackageStatus (async UAT job + poll).
 * - run_tests: local dispatch to manage_tests (long-running).
 * - subscribe/unsubscribe: local dispatch to manage_logs.
 * - spawn_category: local dispatch to manage_debug (categoryName validated).
 * - execute_python: fallback tool dispatch to system_control -> native
 *   HandleExecutePython (long-running, PythonScriptPlugin, 1 MB code limit).
 * - set_project_setting: fallback tool dispatch to system_control.
 * - get_project_settings/validate_assets: local system_control wrapper.
 * - lumen_update_scene: local dispatch to manage_render.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;

export const SYSTEM_OPS_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'run_ubt',
    domain: 'build',
    family: 'build',
    summary: 'Run UnrealBuildTool for a target/platform/configuration, spawning UBT locally with a manage_pipeline bridge fallback.',
    whenToUse: ['The project must be built via UnrealBuildTool.'],
    whenNotToUse: ['Only a console command or CVar is needed.'],
    inputProps: {
      target: { type: 'string', description: 'UBT target name (required).' },
      platform: { type: 'string', description: 'Platform (default Win64).' },
      configuration: { type: 'string', description: 'Build configuration (default Development).' },
      arguments: { type: 'string', description: 'Extra UBT arguments (validated).' },
    },
    required: ['target'],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'high',
    dispatchAction: 'manage_pipeline',
    dispatchMode: 'local',
    exampleInput: { action: 'run_ubt', target: 'MyProject', platform: 'Win64', configuration: 'Development' },
    exampleOutput: { success: true, message: 'UnrealBuildTool finished successfully' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct long-running build capability. TS spawns UBT directly via child_process and falls back to the manage_pipeline bridge action when no local UBT executable is found; target/platform/configuration are validated before dispatch.',
  }),
  // Packaging was the one build step with no capability at all, so a caller who
  // wanted a shippable build had to leave the tool and run RunUAT from a shell.
  // The native handler drives the same IUATHelperModule::CreateUatTask the
  // editor's Package Project menu uses. It cannot answer with the result the way
  // run_ubt does — a cook alone outlives any request timeout — so it hands back
  // a jobId and package_status reports on it.
  buildCoreRecord({
    parentTool: PT,
    action: 'package_project',
    domain: 'build',
    family: 'build',
    topics: ['package project', 'build game', 'cook and package', 'shipping build', 'archive build'],
    summary: 'Start a project package (cook, stage, pak, archive) and return a jobId to poll; the build runs asynchronously in the editor.',
    whenToUse: ['A cooked, staged, archived build of the project is needed.'],
    whenNotToUse: ['Only a code target must be compiled (use run_ubt).', 'The result of an already-started package is wanted (use package_status).'],
    inputProps: {
      platform: { type: 'string', description: 'Target platform (default Win64): Win64, Mac, Linux, LinuxArm64, Android, IOS.' },
      configuration: { type: 'string', description: 'Client configuration (default Development): Debug, DebugGame, Development, Test, Shipping.' },
      archiveDirectory: { type: 'string', description: 'Where the archived build lands (default <Project>/Packaged).' },
      maps: { type: 'array', items: { type: 'string', description: 'A /Game map package path.' }, description: 'Maps to cook. Pass these when a map is reached by NAME at runtime (OpenLevel) rather than by reference, or the cooker will not find it.' },
      pak: { type: 'boolean', description: 'Pak the staged content (default true).' },
      build: { type: 'boolean', description: 'Compile the game target first (default true).' },
    },
    outputProps: {
      jobId: { type: 'string', description: 'Pass to package_status. Jobs live in the editor session and do not survive a restart.' },
      status: { type: 'string', description: 'Always "running" here: the call returns as soon as UAT is launched.' },
      archiveDirectory: { type: 'string', description: 'Resolved absolute archive directory.' },
      commandLine: { type: 'string', description: 'The exact UAT command line that was launched.' },
      platform: { type: 'string', description: 'Resolved target platform.' },
      configuration: { type: 'string', description: 'Resolved client configuration.' },
    },
    required: [],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'high',
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'package_project', platform: 'Win64', configuration: 'Development', maps: ['/Game/Maps/L_Hub'] },
    exampleOutput: { success: true, jobId: '0F1E2D3C-4B5A-6978-8796-A5B4C3D2E1F0', status: 'running', archiveDirectory: 'D:/Proj/Packaged', commandLine: '-ScriptsForProject=... BuildCookRun ...', platform: 'Win64', configuration: 'Development' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct long-running packaging capability with no prior coverage. Routes via the system_control fallback dispatch to the native HandlePackageProject, which validates platform/configuration against allow-lists and refuses map paths outside /Game.',
    normalizationProvenance: 'post-migration',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'package_status',
    domain: 'build',
    family: 'build',
    topics: ['package status', 'packaging progress', 'build progress', 'is the package done'],
    summary: 'Report a packaging job started by package_project: running, succeeded or failed, with elapsed time and the log directory.',
    whenToUse: ['A package started by package_project must be checked for completion.'],
    whenNotToUse: ['A new package should be started (use package_project).'],
    inputProps: {
      jobId: { type: 'string', description: 'The jobId package_project returned. Omit to list the jobIds this editor session knows.' },
    },
    outputProps: {
      jobId: { type: 'string', description: 'Echoed job identifier.' },
      jobIds: { type: 'array', items: { type: 'string', description: 'A known jobId.' }, description: 'Every job this editor session started; returned when jobId is omitted.' },
      status: { type: 'string', description: 'running, succeeded or failed.' },
      uatResult: { type: 'string', description: "UAT's own result word once the task finished." },
      elapsedSeconds: { type: 'number', description: 'Seconds so far while running, total runtime once finished.' },
      archiveDirectory: { type: 'string', description: 'Where the archived build lands.' },
      commandLine: { type: 'string', description: 'The UAT command line this job launched.' },
      logDirectory: { type: 'string', description: 'Where to read the failure: a failed pack leaves nothing in the archive directory.' },
      platform: { type: 'string', description: 'Target platform of the job.' },
      configuration: { type: 'string', description: 'Client configuration of the job.' },
    },
    required: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'package_status', jobId: '0F1E2D3C-4B5A-6978-8796-A5B4C3D2E1F0' },
    exampleOutput: { success: true, jobId: '0F1E2D3C-4B5A-6978-8796-A5B4C3D2E1F0', status: 'succeeded', uatResult: 'Completed', elapsedSeconds: 401.2, archiveDirectory: 'D:/Proj/Packaged', commandLine: '-ScriptsForProject=... BuildCookRun ...', logDirectory: 'D:/Proj/Saved/Logs', platform: 'Win64', configuration: 'Development' },
    normalizationClass: NC,
    normalizationRationale: 'Read-side companion to package_project with no prior coverage. Routes via the system_control fallback dispatch to the native HandlePackageStatus, which reads an in-session job registry.',
    normalizationProvenance: 'post-migration',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'run_tests',
    domain: 'build',
    family: 'build',
    topics: ['automation tests', 'run tests', 'test suite', 'functional tests'],
    summary: 'Run the automation test suite via the manage_tests bridge action with an optional filter.',
    whenToUse: ['The project automation tests must be executed.'],
    whenNotToUse: ['A single ad-hoc console command is needed.'],
    inputProps: { filter: { type: 'string', description: 'Optional test name filter.' } },
    required: [],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'medium',
    dispatchAction: 'manage_tests',
    dispatchMode: 'local',
    exampleInput: { action: 'run_tests', filter: 'MyProject' },
    exampleOutput: { success: true, message: 'Tests completed' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct long-running test capability routed to the manage_tests bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'subscribe',
    domain: 'logs',
    family: 'logs',
    summary: 'Subscribe to a live log channel via the manage_logs bridge action.',
    whenToUse: ['A live log channel must be subscribed for streaming output.'],
    whenNotToUse: ['A one-shot historical log read is needed.'],
    inputProps: { channels: { type: 'string', description: 'Log channel(s) to subscribe to.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_logs',
    dispatchMode: 'local',
    exampleInput: { action: 'subscribe', channels: 'LogCore' },
    exampleOutput: { success: true, message: 'Subscribed to log channel' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct log subscription capability routed to the manage_logs bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'unsubscribe',
    domain: 'logs',
    family: 'logs',
    summary: 'Unsubscribe from a live log channel via the manage_logs bridge action.',
    whenToUse: ['A previously subscribed log channel must be unsubscribed.'],
    whenNotToUse: ['No subscription is active.'],
    inputProps: { channels: { type: 'string', description: 'Log channel(s) to unsubscribe from.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_logs',
    dispatchMode: 'local',
    exampleInput: { action: 'unsubscribe', channels: 'LogCore' },
    exampleOutput: { success: true, message: 'Unsubscribed from log channel' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct log unsubscription capability routed to the manage_logs bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'spawn_category',
    domain: 'logs',
    family: 'logs',
    summary: 'Spawn a debug log category via the manage_debug bridge action (categoryName validated).',
    whenToUse: ['A new debug log category must be registered at runtime.'],
    whenNotToUse: ['An existing engine category should be subscribed (use subscribe).'],
    inputProps: {
      categoryName: { type: 'string', description: 'Category name (letters, digits, underscore, hyphen only).' },
      category: { type: 'string', description: 'Alternate category name field.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_debug',
    dispatchMode: 'local',
    exampleInput: { action: 'spawn_category', categoryName: 'MyDebug' },
    exampleOutput: { success: true, message: 'Category spawned' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct debug-category spawn routed to the manage_debug bridge action; categoryName is regex-validated by the orchestrator before dispatch.',
  }),
  // execute_python XOR contract: the native handler
  // (plugins/McpAutomationBridge/.../Private/Domains/SystemControl/McpAutomationBridge_SystemControlHandlersPython.cpp)
  // rejects supplying BOTH code and file ("Provide either 'code' or 'file', not both").
  // The schema keyword is at-least-one, the handler is XOR, so a both-supplied
  // request passes gateway validation and fails at the handler with INVALID_ARGUMENT.
  buildCoreRecord({
    parentTool: PT,
    action: 'execute_python',
    domain: 'python',
    family: 'python',
    topics: ['python', 'run python', 'python script', 'execute script', 'py code'],
    summary: 'Execute inline Python code or a .py file in the editor via the native HandleExecutePython handler.',
    whenToUse: ['Editor-side Python automation must run inline or from a script file.'],
    whenNotToUse: ['Untrusted code without review; runs arbitrary editor-side code.'],
    inputProps: {
      code: { type: 'string', description: 'Python code to execute inline (1 MB max).', maxLength: 1048576 },
      file: { type: 'string', description: 'Path to a .py file to execute.', maxLength: 4096 },
    },
    // The handler already returns stdout and the interpreter traceback, but the
    // default {success, message} output schema is closed, so both were stripped
    // before reaching the caller. A failing script reported only "Python
    // execution failed" — no traceback on the receipt and none in the editor
    // log either, leaving the failure undiagnosable from either transport.
    outputProps: {
      output: { type: 'string', description: 'Captured stdout from the script.' },
      error: { type: 'string', description: 'Captured stderr and the interpreter traceback when the script raises.' },
      executionId: { type: 'string', description: 'Correlates the run with the temp wrapper under Saved/Temp/MCP_Python.' },
      codeSha256: { type: 'string', description: 'SHA-256 of the executed code, as logged.' },
    },
    required: [],
    requiredOneOf: ['code', 'file'],
    effect: 'write',
    // The one capability that can do anything at all was also the least gated:
    // creating a material needed a single-use explicit grant while running
    // arbitrary editor-side Python needed none. Requiring a grant here puts the
    // gate back where the blast radius actually is.
    policyOverride: { consent: 'explicit' },
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'medium',
    plugins: ['PythonScriptPlugin'],
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'execute_python', code: 'print("hello")' },
    exampleOutput: { success: true, message: 'Python executed' },
    normalizationClass: NC,
    normalizationRationale: 'Python execution runs arbitrary editor-side code. The native handler enforces a 1 MB code-size limit, writes a temp wrapper under Saved/Temp/MCP_Python with an FPythonTempFileCleanup scope guard, and resolves symlinks before execution. Routes via the system_control fallback to the native HandleExecutePython handler.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_project_setting',
    domain: 'project',
    family: 'project',
    summary: 'Set a project setting value for a section and key via the system_control fallback dispatch.',
    whenToUse: ['A single project setting value must be written.'],
    whenNotToUse: ['The full settings document must be read (use get_project_settings).'],
    inputProps: {
      section: { type: 'string', description: 'Settings section.' },
      key: { type: 'string', description: 'Setting key.' },
      value: { type: 'string', description: 'Setting value.' },
    },
    required: ['section', 'key'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'set_project_setting', section: '/Script/EngineSettings.GeneralProjectSettings', key: 'ProjectName', value: 'MyProject' },
    exampleOutput: { success: true, message: 'Project setting set' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct project-setting write capability. Routes via the system_control fallback dispatch; the native HandleSystemControlAction accept list does not include set_project_setting, so the action relies on a separate native project-settings handler.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'get_project_settings',
    domain: 'project',
    family: 'project',
    summary: 'Retrieve project settings for a section via the local system_control wrapper.',
    whenToUse: ['Project settings must be read for a section.'],
    whenNotToUse: ['A single setting must be written (use set_project_setting).'],
    inputProps: {
      key: { type: 'string', description: 'Single config property to read from the section; the reply then carries key and value.' },
      section: { type: 'string', description: 'Settings section.' },
      category: { type: 'string', description: 'Alternate section selector.' },
    },
    required: [],
    // The local TS wrapper re-dispatches to system_control; the native Ui
    // project-settings handler (UiHandlersProjectSettings.cpp:18-57) returns a
    // settings object with engine/project identity plus GameUserSettings values.
    outputProps: {
      settings: {
        type: 'object',
        'x-unreal-reflection-boundary': true,
        description: 'Config properties of the requested section (every CPF_Config property of the settings class as text), or the project snapshot (engineVersion, projectName, projectDir, maps, general) when no section is given.',
      },
      section: { type: 'string', description: 'Resolved settings class path.' },
      configName: { type: 'string', description: 'Config file family (Engine, Game, Input, ...).' },
      settingCount: { type: 'number', description: 'Number of config properties returned.' },
      key: { type: 'string', description: 'Requested key, when one was asked for.' },
      value: { type: 'string', description: 'Value of the requested key.' },
      hint: { type: 'string', description: 'How to get a full section dump.' },
    },
    outputRequired: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'local',
    exampleInput: { action: 'get_project_settings', section: '/Script/EngineSettings.GeneralProjectSettings' },
    exampleOutput: { success: true, message: 'Project settings retrieved' },
    normalizationClass: 'A_TRUE_DUPLICATE',
    normalizationDisposition: 'alias',
    normalizationRationale: 'True duplicate (cap:shared:get_project_settings) shared with inspect; system_control is the alias occurrence per the normalization inventory. The local TS wrapper re-dispatches to the system_control bridge action with a normalized section field.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'validate_assets',
    domain: 'project',
    family: 'project',
    summary: 'Validate one or more assets by path via the local system_control wrapper with a manage_asset exists fallback.',
    whenToUse: ['Asset references must be validated before use.'],
    whenNotToUse: ['A single asset must be imported or created (use manage_asset).'],
    inputProps: {
      paths: { type: 'array', items: { type: 'string' }, description: 'Asset paths to validate.' },
      assetPath: { type: 'string', description: 'Single asset path to validate.' },
      path: { type: 'string', description: 'Alternate single asset path field.' },
      recursive: { type: 'boolean', description: 'Validate recursively.' },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'local',
    exampleInput: { action: 'validate_assets', paths: ['/Game/Materials/M_Base'] },
    exampleOutput: { success: true, message: 'Asset validation completed' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct read-only asset-validation capability. The local TS wrapper dispatches to system_control and falls back to per-path manage_asset exists checks when the bridge does not return results.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'lumen_update_scene',
    domain: 'render',
    family: 'render',
    summary: 'Trigger a Lumen scene update via the manage_render bridge action.',
    whenToUse: ['Lumen GI must refresh the scene capture.'],
    whenNotToUse: ['A full lighting build is needed (use build_lighting via build_environment).'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_render',
    dispatchMode: 'local',
    exampleInput: { action: 'lumen_update_scene' },
    exampleOutput: { success: true, message: 'Lumen scene updated' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct Lumen scene-update capability routed to the manage_render bridge action by the orchestrator.',
  }),
];
