/**
 * System operations records (10): run_ubt, run_tests, subscribe, unsubscribe,
 * spawn_category, execute_python, set_project_setting, get_project_settings,
 * validate_assets, lumen_update_scene.
 *
 * Routing is mixed and grounded in consolidated-handler-registration.ts:
 * - run_ubt: local TS spawn with manage_pipeline bridge fallback (long-running).
 * - run_tests: local dispatch to manage_tests (long-running).
 * - subscribe/unsubscribe: local dispatch to manage_logs.
 * - spawn_category: local dispatch to manage_debug (categoryName validated).
 * - execute_python: fallback tool dispatch to system_control -> native
 *   HandleExecutePython (long-running, PythonScriptPlugin, 1 MB code limit).
 * - set_project_setting: fallback tool dispatch to system_control.
 * - get_project_settings/validate_assets: local system_control wrapper.
 * - lumen_update_scene: local dispatch to manage_render.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;

export const SYSTEM_OPS_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'run_ubt',
    domain: 'build',
    family: 'build',
    summary: 'Run UnrealBuildTool for a target/platform/configuration, spawning UBT locally with a manage_pipeline bridge fallback.',
    whenToUse: ['The project must be built via UnrealBuildTool.'],
    whenNotToUse: ['Only a console command or CVar is needed.'],
    inputProps: {
      target: { type: 'string', description: 'UBT target name (required).' },
      platform: { type: 'string', description: 'Platform (default Win64).' },
      configuration: { type: 'string', description: 'Build configuration (default Development).' },
      arguments: { type: 'string', description: 'Extra UBT arguments (validated).' },
    },
    required: ['target'],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'high',
    dispatchAction: 'manage_pipeline',
    dispatchMode: 'local',
    exampleInput: { action: 'run_ubt', target: 'MyProject', platform: 'Win64', configuration: 'Development' },
    exampleOutput: { success: true, message: 'UnrealBuildTool finished successfully' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct long-running build capability. TS spawns UBT directly via child_process and falls back to the manage_pipeline bridge action when no local UBT executable is found; target/platform/configuration are validated before dispatch.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'run_tests',
    domain: 'build',
    family: 'build',
    summary: 'Run the automation test suite via the manage_tests bridge action with an optional filter.',
    whenToUse: ['The project automation tests must be executed.'],
    whenNotToUse: ['A single ad-hoc console command is needed.'],
    inputProps: { filter: { type: 'string', description: 'Optional test name filter.' } },
    required: [],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'medium',
    dispatchAction: 'manage_tests',
    dispatchMode: 'local',
    exampleInput: { action: 'run_tests', filter: 'MyProject' },
    exampleOutput: { success: true, message: 'Tests completed' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct long-running test capability routed to the manage_tests bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'subscribe',
    domain: 'logs',
    family: 'logs',
    summary: 'Subscribe to a live log channel via the manage_logs bridge action.',
    whenToUse: ['A live log channel must be subscribed for streaming output.'],
    whenNotToUse: ['A one-shot historical log read is needed.'],
    inputProps: { channels: { type: 'string', description: 'Log channel(s) to subscribe to.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_logs',
    dispatchMode: 'local',
    exampleInput: { action: 'subscribe', channels: 'LogCore' },
    exampleOutput: { success: true, message: 'Subscribed to log channel' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct log subscription capability routed to the manage_logs bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'unsubscribe',
    domain: 'logs',
    family: 'logs',
    summary: 'Unsubscribe from a live log channel via the manage_logs bridge action.',
    whenToUse: ['A previously subscribed log channel must be unsubscribed.'],
    whenNotToUse: ['No subscription is active.'],
    inputProps: { channels: { type: 'string', description: 'Log channel(s) to unsubscribe from.' } },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_logs',
    dispatchMode: 'local',
    exampleInput: { action: 'unsubscribe', channels: 'LogCore' },
    exampleOutput: { success: true, message: 'Unsubscribed from log channel' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct log unsubscription capability routed to the manage_logs bridge action by the orchestrator.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'spawn_category',
    domain: 'logs',
    family: 'logs',
    summary: 'Spawn a debug log category via the manage_debug bridge action (categoryName validated).',
    whenToUse: ['A new debug log category must be registered at runtime.'],
    whenNotToUse: ['An existing engine category should be subscribed (use subscribe).'],
    inputProps: {
      categoryName: { type: 'string', description: 'Category name (letters, digits, underscore, hyphen only).' },
      category: { type: 'string', description: 'Alternate category name field.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_debug',
    dispatchMode: 'local',
    exampleInput: { action: 'spawn_category', categoryName: 'MyDebug' },
    exampleOutput: { success: true, message: 'Category spawned' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct debug-category spawn routed to the manage_debug bridge action; categoryName is regex-validated by the orchestrator before dispatch.',
  }),
  // execute_python XOR contract: the native handler
  // (plugins/McpAutomationBridge/.../Private/Domains/SystemControl/McpAutomationBridge_SystemControlHandlersPython.cpp)
  // rejects supplying BOTH code and file ("Provide either 'code' or 'file', not both").
  // The schema keyword is at-least-one, the handler is XOR, so a both-supplied
  // request passes gateway validation and fails at the handler with INVALID_ARGUMENT.
  buildCoreRecord({
    parentTool: PT,
    action: 'execute_python',
    domain: 'python',
    family: 'python',
    summary: 'Execute inline Python code or a .py file in the editor via the native HandleExecutePython handler.',
    whenToUse: ['Editor-side Python automation must run inline or from a script file.'],
    whenNotToUse: ['Untrusted code without review; runs arbitrary editor-side code.'],
    inputProps: {
      code: { type: 'string', description: 'Python code to execute inline (1 MB max).', maxLength: 1048576 },
      file: { type: 'string', description: 'Path to a .py file to execute.', maxLength: 4096 },
    },
    required: [],
    requiredOneOf: ['code', 'file'],
    effect: 'write',
    behavior: { longRunning: true },
    costLatency: 'long-running',
    costResources: 'medium',
    plugins: ['PythonScriptPlugin'],
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'execute_python', code: 'print("hello")' },
    exampleOutput: { success: true, message: 'Python executed' },
    normalizationClass: NC,
    normalizationRationale: 'Python execution runs arbitrary editor-side code. The native handler enforces a 1 MB code-size limit, writes a temp wrapper under Saved/Temp/MCP_Python with an FPythonTempFileCleanup scope guard, and resolves symlinks before execution. Routes via the system_control fallback to the native HandleExecutePython handler.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'set_project_setting',
    domain: 'project',
    family: 'project',
    summary: 'Set a project setting value for a section and key via the system_control fallback dispatch.',
    whenToUse: ['A single project setting value must be written.'],
    whenNotToUse: ['The full settings document must be read (use get_project_settings).'],
    inputProps: {
      section: { type: 'string', description: 'Settings section.' },
      key: { type: 'string', description: 'Setting key.' },
      value: { type: 'string', description: 'Setting value.' },
    },
    required: ['section', 'key'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'tool',
    exampleInput: { action: 'set_project_setting', section: '/Script/EngineSettings.GeneralProjectSettings', key: 'ProjectName', value: 'MyProject' },
    exampleOutput: { success: true, message: 'Project setting set' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct project-setting write capability. Routes via the system_control fallback dispatch; the native HandleSystemControlAction accept list does not include set_project_setting, so the action relies on a separate native project-settings handler.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'get_project_settings',
    domain: 'project',
    family: 'project',
    summary: 'Retrieve project settings for a section via the local system_control wrapper.',
    whenToUse: ['Project settings must be read for a section.'],
    whenNotToUse: ['A single setting must be written (use set_project_setting).'],
    inputProps: {
      section: { type: 'string', description: 'Settings section.' },
      category: { type: 'string', description: 'Alternate section selector.' },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'local',
    exampleInput: { action: 'get_project_settings', section: '/Script/EngineSettings.GeneralProjectSettings' },
    exampleOutput: { success: true, message: 'Project settings retrieved' },
    normalizationClass: 'A_TRUE_DUPLICATE',
    normalizationDisposition: 'alias',
    normalizationRationale: 'True duplicate (cap:shared:get_project_settings) shared with inspect; system_control is the alias occurrence per the normalization inventory. The local TS wrapper re-dispatches to the system_control bridge action with a normalized section field.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'validate_assets',
    domain: 'project',
    family: 'project',
    summary: 'Validate one or more assets by path via the local system_control wrapper with a manage_asset exists fallback.',
    whenToUse: ['Asset references must be validated before use.'],
    whenNotToUse: ['A single asset must be imported or created (use manage_asset).'],
    inputProps: {
      paths: { type: 'array', items: { type: 'string' }, description: 'Asset paths to validate.' },
      assetPath: { type: 'string', description: 'Single asset path to validate.' },
      path: { type: 'string', description: 'Alternate single asset path field.' },
      recursive: { type: 'boolean', description: 'Validate recursively.' },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'system_control',
    dispatchMode: 'local',
    exampleInput: { action: 'validate_assets', paths: ['/Game/Materials/M_Base'] },
    exampleOutput: { success: true, message: 'Asset validation completed' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct read-only asset-validation capability. The local TS wrapper dispatches to system_control and falls back to per-path manage_asset exists checks when the bridge does not return results.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'lumen_update_scene',
    domain: 'render',
    family: 'render',
    summary: 'Trigger a Lumen scene update via the manage_render bridge action.',
    whenToUse: ['Lumen GI must refresh the scene capture.'],
    whenNotToUse: ['A full lighting build is needed (use build_lighting via build_environment).'],
    inputProps: {},
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_render',
    dispatchMode: 'local',
    exampleInput: { action: 'lumen_update_scene' },
    exampleOutput: { success: true, message: 'Lumen scene updated' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct Lumen scene-update capability routed to the manage_render bridge action by the orchestrator.',
  }),
];
