/**
 * Widget/audio/viewport records (5): create_widget, show_widget,
 * add_widget_child, play_sound, screenshot.
 *
 * All route through local TS handlers (dispatchMode 'local'). Widget actions
 * dispatch to manage_widget_authoring, play_sound to play_sound_2d (with an
 * engine fallback sound), and screenshot to control_editor (game_viewport
 * mode re-dispatches to system_control). Grounded in system-widget-handlers,
 * system-audio-handlers, and system-viewport-handlers.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const NC = 'C_SAME_VERB_DIFFERENT_TARGET' as const;

export const WIDGET_AUDIO_VIEWPORT_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'create_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Create a widget asset via the manage_widget_authoring bridge action.',
    whenToUse: ['A new UMG widget asset must be created.'],
    whenNotToUse: ['An existing widget should be shown (use show_widget).'],
    inputProps: {
      name: { type: 'string', description: 'Widget name (derived from widgetPath if absent).' },
      widgetPath: { type: 'string', description: 'Full widget path; name and savePath are derived when name is absent.' },
      widgetType: { type: 'string', description: 'Widget type.' },
      savePath: { type: 'string', description: 'Destination /Game folder.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_widget_authoring',
    dispatchMode: 'local',
    exampleInput: { action: 'create_widget', name: 'WBP_Menu', savePath: '/Game/UI' },
    exampleOutput: { success: true, message: 'Widget created' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct widget-authoring capability re-dispatched to manage_widget_authoring by the local TS wrapper.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'show_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Show a widget by path or render a notification via the manage_widget_authoring bridge action.',
    whenToUse: ['An existing widget must be displayed or a notification shown.'],
    whenNotToUse: ['A new widget must be authored first (use create_widget).'],
    inputProps: {
      widgetId: { type: 'string', description: 'Widget id; "notification" renders a notification.' },
      widgetPath: { type: 'string', description: 'Widget path (or name) to show.' },
      name: { type: 'string', description: 'Alternate widget path selector.' },
      message: { type: 'string', description: 'Notification message text.' },
      duration: { type: 'number', description: 'Notification duration.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'manage_widget_authoring',
    dispatchMode: 'local',
    exampleInput: { action: 'show_widget', widgetId: 'notification', message: 'Saved' },
    exampleOutput: { success: true, message: 'Notification shown' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct widget-display capability re-dispatched to manage_widget_authoring; the notification sub-path is handled by a dedicated branch in the TS wrapper.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'add_widget_child',
    domain: 'widget',
    family: 'widget',
    summary: 'Add a child widget component to a parent widget via the manage_widget_authoring bridge action.',
    whenToUse: ['A child component must be added to an existing widget.'],
    whenNotToUse: ['A top-level widget must be created (use create_widget).'],
    inputProps: {
      widgetPath: { type: 'string', description: 'Parent widget path (required).' },
      childClass: { type: 'string', description: 'Child component class (required).' },
      parentName: { type: 'string', description: 'Optional parent panel name.' },
      name: { type: 'string', description: 'Optional component name.' },
      text: { type: 'string', description: 'Optional text for text-bearing components.' },
    },
    required: ['widgetPath', 'childClass'],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'manage_widget_authoring',
    dispatchMode: 'local',
    exampleInput: { action: 'add_widget_child', widgetPath: '/Game/UI/WBP_Menu', childClass: 'TextBlock' },
    exampleOutput: { success: true, message: 'Widget child added' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct widget-component capability re-dispatched to manage_widget_authoring as add_widget_component.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'play_sound',
    domain: 'audio',
    family: 'audio',
    summary: 'Play a 2D sound by path via the play_sound_2d bridge action, with an engine fallback sound.',
    whenToUse: ['A 2D (non-spatial) sound must be played at runtime.'],
    whenNotToUse: ['A spatial sound at a location is needed (use manage_audio).'],
    inputProps: {
      soundPath: { type: 'string', description: 'Sound asset path.' },
      volume: { type: 'number', description: 'Volume multiplier (0 silences the request).' },
      pitch: { type: 'number', description: 'Pitch multiplier.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'instant',
    costResources: 'low',
    dispatchAction: 'play_sound_2d',
    dispatchMode: 'local',
    exampleInput: { action: 'play_sound', soundPath: '/Game/Audio/SFX_Click', volume: 1.0 },
    exampleOutput: { success: true, message: 'Sound played' },
    normalizationClass: NC,
    normalizationRationale: 'Distinct 2D audio capability re-dispatched to play_sound_2d; the TS wrapper falls back to an engine editor sound when the requested asset is missing.',
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'screenshot',
    domain: 'viewport',
    family: 'viewport',
    summary: 'Capture a screenshot of the editor viewport, game viewport, or full editor window.',
    whenToUse: ['A viewport or window screenshot must be captured, optionally as base64.'],
    whenNotToUse: ['A PIE session screenshot with camera control is needed (use control_editor).'],
    inputProps: {
      filename: { type: 'string', description: 'Screenshot filename base.' },
      mode: { type: 'string', enum: ['editor_viewport', 'game_viewport', 'full_editor_window'], description: 'Screenshot target mode.' },
      resolution: { type: 'string', description: 'Resolution as WxH.' },
      width: { type: 'number', description: 'Width in pixels.' },
      height: { type: 'number', description: 'Height in pixels.' },
      returnBase64: { type: 'boolean', description: 'Return PNG as base64. Defaults to false — a plain capture returns path + metadata. Set true for inline image data; pair with resolution= (e.g. "1280x720") to keep the PNG under the base64 size cap.' },
      includeMetadata: { type: 'boolean', description: 'Include capture metadata.' },
      metadata: { type: 'object', description: 'Optional metadata payload.', additionalProperties: true, 'x-unreal-reflection-boundary': true },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'low',
    dispatchAction: 'control_editor',
    dispatchMode: 'local',
    exampleInput: { action: 'screenshot', mode: 'editor_viewport', filename: 'Shot1' },
    exampleOutput: { success: true, message: 'Screenshot captured' },
    normalizationClass: 'A_TRUE_DUPLICATE',
    normalizationDisposition: 'alias',
    normalizationRationale: 'True duplicate (cap:shared:screenshot) shared with control_editor; system_control is the alias occurrence per the normalization inventory. The TS wrapper dispatches to control_editor for editor_viewport and full_editor_window modes and re-dispatches to system_control for game_viewport mode.',
  }),
];
