import type { ToolDefinition } from '../definitions/shared/tool-definition.js';

export const unrealGatewayToolDefinition: ToolDefinition = {
  name: 'unreal',
  description: 'Unreal Engine capability gateway. Search first, describe the exact contract, then execute a validated action. Use configure only to manage internal capability availability.',
  inputSchema: {
    type: 'object',
    properties: {
      operation: {
        type: 'string',
        enum: ['search', 'describe', 'execute', 'configure'],
        description: 'search finds capabilities. describe returns an exact parent-tool contract. execute runs one validated action. configure manages internal capability availability.'
      },
      query: { type: 'string', description: 'Search words for tools, categories, descriptions, or actions.' },
      capability: { type: 'string', description: 'Exact canonical capability ID (or declared alias) returned by search, e.g. asset.import. Preferred selector for describe.' },
      domain: { type: 'string', description: 'Capability domain to browse or filter by. Call describe with no selector to list domains.' },
      family: { type: 'string', description: 'Capability family inside a domain. Call describe with a domain to list its families.' },
      effect: { type: 'string', enum: ['read', 'write', 'destructive'], description: 'Filter search results by declared behavior effect.' },
      tool: { type: 'string', description: 'Exact canonical parent tool name returned by search or describe.' },
      action: { type: 'string', description: 'Exact action name returned by describe. For configure, this is a manage_tools action.' },
      param: { type: 'string', description: 'Exact parameter name (tool-union catalog) to inspect. Requires tool and action for full drill-down; resolves the single parameter schema. Use with describe only.' },
      params: { type: 'object', additionalProperties: true, description: 'Parameters for execute or configure. Keys are the action-specific parameter names returned by describe. Never include action or subAction here.' },
      consent: {
        type: 'object',
        properties: {
          capability: { type: 'string', description: 'Exact canonical capability ID this grant authorizes, as returned by describe.' },
          acknowledge: { type: 'string', enum: ['explicit', 'elevated'], description: "Acknowledgement strength. 'explicit' satisfies an explicit policy; 'elevated' is required by a destructive policy and also satisfies explicit." }
        },
        required: ['capability', 'acknowledge'],
        additionalProperties: false,
        description: "Per-call consent grant for a capability whose policy.consent is not 'none'. Bound to one capability and one call; never persisted, inherited or reused. Read the exact grant from describe.consentGrant. Use with execute only."
      },
      limit: { type: 'integer', minimum: 1, maximum: 25, description: 'Maximum search results to return. Defaults to 12.' },
      offset: { type: 'integer', minimum: 0, description: 'Zero-based search result offset. Defaults to 0.' },
      cursor: { type: 'string', description: 'Opaque search cursor from a previous response nextCursor. Supersedes offset.' },
      maxBytes: { type: 'integer', minimum: 512, maximum: 262144, description: 'Serialized byte ceiling for a search response. Results are dropped from the end until the response fits.' }
    },
    required: ['operation'],
    additionalProperties: false
  },
  outputSchema: {
    type: 'object',
    properties: {
      success: { type: 'boolean' },
      operation: { type: 'string' },
      error: { type: 'string' },
      errorCode: { type: 'string' },
      message: { type: 'string' },
      results: { type: 'array' },
      result: {},
      data: { description: "Execute payload projected against the capability's declared output schema. Same value as receipt.data, and the same location the native /mcp surface publishes." },
      tool: { type: 'string' },
      action: { type: 'string' },
      param: { type: 'string' },
      total: { type: 'integer' },
      offset: { type: 'integer' },
      limit: { type: 'integer' },
      hasMore: { type: 'boolean' },
      perActionSchemas: { type: 'boolean' },
      scope: { type: 'string', description: "Catalog scope: 'tool' for a tool summary, 'union' for the tool-union parameter catalog." },
      actions: { type: 'array', description: 'Paginated/filterable action list on tool-only describe.' },
      actionCount: { type: 'integer' },
      actionOffset: { type: 'integer' },
      actionLimit: { type: 'integer' },
      actionHasMore: { type: 'boolean' },
      parameters: { type: 'array', description: 'Paginated/filterable compact parameter catalog on tool+action describe.' },
      parameterCount: { type: 'integer' },
      parameterOffset: { type: 'integer' },
      parameterLimit: { type: 'integer' },
      parameterHasMore: { type: 'boolean' },
      required: { type: 'boolean', description: 'Whether the described param is required.' },
      schema: { type: 'object', description: 'Full schema of the single described param.' },
      drillDown: { type: 'object', description: 'Example nextCall payload to drill one level deeper.' },
      suggestions: { type: 'array', description: 'Closest-match names for an invalid tool/action/param call.' },
      nextCall: { type: 'object', description: 'Directly-invokable gateway request for guided self-correction.' },
      availableActions: { type: 'array' },
      availableParameters: { type: 'array' },
      catalogRevision: { type: 'string', description: 'Revision of the generated canonical capability catalog this response was served from.' },
      capability: { type: 'string', description: 'Canonical capability ID this response describes.' },
      parentTool: { type: 'string', description: 'Legacy parent tool that dispatches the described capability.' },
      domain: { type: 'string' },
      family: { type: 'string' },
      domains: { type: 'array', description: 'Bounded domain list on a catalog-level describe.' },
      families: { type: 'array', description: 'Bounded family list on a domain-level describe.' },
      capabilities: { type: 'array', description: 'Bounded capability list on a family-level describe.' },
      inputSchema: { type: 'object', description: 'Exact input schema of the described capability. Never a parent-tool union.' },
      outputSchema: { type: 'object', description: 'Exact output schema of the described capability.' },
      availability: { description: 'Whether the capability is available, disabled or unavailable, and why.' },
      behavior: { type: 'object' },
      policy: { type: 'object' },
      consentGrant: { type: 'object', description: "Exact consent grant this capability requires, ready to pass back as the execute call's consent sibling. Absent when policy.consent is 'none'." },
      cost: { type: 'object' },
      deprecation: { type: 'object' },
      hashes: { type: 'object', description: 'Per-record schema and content hashes from the generated catalog.' },
      runnable: { type: 'boolean', description: 'False when the capability cannot currently be executed; nextCall then points at the fix.' },
      migratedFrom: { type: 'object', description: 'Legacy tool/action pair that resolved to this capability.' },
      resolvedFromAlias: { type: 'string', description: 'Declared alias that resolved to this capability.' },
      nextCursor: { type: 'string', description: 'Cursor to pass back as cursor to continue a search.' },
      maxBytes: { type: 'integer' },
      truncated: { type: 'boolean', description: 'True when results were dropped to fit the byte budget.' },
      filters: { type: 'object', description: 'Filters applied to this search.' },
      reasons: { type: 'array' },
      outputs: { type: 'array' }
    },
    required: ['success', 'operation'],
    additionalProperties: true
  }
};
