/**
 * Component and actor inspection records (14 actions).
 *
 * All 14 dispatch to the control_actor bridge route (dispatchMode 'action')
 * because the TS inspect handlers re-route actor/component operations to
 * control_actor rather than the inspect parent. Grounded in:
 * - src/tools/handlers/inspect/inspect-components.ts: get_component_property,
 *   set_component_property dispatch to control_actor; get_component_details
 *   dispatches action 'get_components' to control_actor then filters locally
 *   (action-name mismatch surfaced); get_components dispatches to inspect but
 *   also re-routes to inspect_cdo when blueprintPath is supplied.
 * - src/tools/handlers/inspect/inspect-actor-actions.ts: get_metadata, add_tag,
 *   find_by_tag, create_snapshot, restore_snapshot, export, delete_object,
 *   list_objects, get_bounding_box all dispatch to control_actor.
 * - native McpAutomationBridge_EnvironmentHandlersInspect.cpp: find_by_tag is
 *   classified as a GLOBAL inspect action (bIsGlobalAction) on native, while TS
 *   routes it to control_actor - a TS/native routing mismatch surfaced in the
 *   find_by_tag rationale rather than normalized away.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { P } from './properties.js';

const D = 'inspect';
const NR = 'Distinct inspect verb and target; no cross-tool duplicate.';

export const COMPONENT_ACTOR_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_components', dispatchAction: 'get_components', domain: D, family: 'components',
    summary: 'List components on a world actor (or a Blueprint CDO when blueprintPath is supplied).',
    whenToUse: ['An actor\'s component list must be enumerated.'],
    whenNotToUse: ['A single component\'s properties are needed; use get_component_property.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, blueprintPath: P.blueprintPath },
    required: [],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'get_components', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Components listed', components: [] },
    outputProps: { components: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Component info objects.' } },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_component_property', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'components',
    summary: 'Read a property on a world actor component (cross-parent to control_actor).',
    whenToUse: ['A single component property value must be read.'],
    whenNotToUse: ['The whole component is needed; use get_component_details.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, propertyName: P.propertyName, propertyPath: P.propertyPath, blueprintPath: P.blueprintPath },
    required: ['componentName', 'propertyName'],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'get_component_property', actorName: 'PlayerStart_1', componentName: 'Billboard', propertyName: 'Sprite' },
    exampleOutput: { success: true, message: 'Component property read', value: null },
    outputProps: { value: P.value },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'set_component_property', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'components',
    summary: 'Write a property on a world actor component (cross-parent to control_actor).',
    whenToUse: ['A single component property value must be written.'],
    whenNotToUse: ['The component does not own the property; use get_components to enumerate.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, propertyName: P.propertyName, propertyPath: P.propertyPath, value: P.value },
    required: ['componentName', 'propertyName'],
    effect: 'write', costLatency: 'interactive', costResources: 'low',
    exampleInput: { action: 'set_component_property', actorName: 'PlayerStart_1', componentName: 'Billboard', propertyName: 'Sprite', value: null },
    exampleOutput: { success: true, message: 'Component property set' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_component_details', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'components',
    summary: 'Return a single component of a world actor (TS dispatches get_components to control_actor and filters locally).',
    whenToUse: ['One component\'s full details must be read.'],
    whenNotToUse: ['All components are needed; use get_components.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, blueprintPath: P.blueprintPath },
    required: ['componentName'],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'get_component_details', actorName: 'PlayerStart_1', componentName: 'Billboard' },
    exampleOutput: { success: true, message: 'Component details', componentName: 'Billboard' },
    outputProps: { componentName: P.componentName },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: 'Mismatch surfaced: inspect-components.ts dispatches action get_components to control_actor and filters the result locally in TS; native inspect would treat get_component_details as an object inspection. The canonical action name does not match the dispatched control_actor get_components action.',
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_metadata', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Read metadata key/value pairs from a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s metadata must be inspected.'],
    whenNotToUse: ['Metadata must be written; use manage_asset or control_actor set_metadata.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'get_metadata', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Metadata read' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'add_tag', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Add a tag to a world actor (cross-parent to control_actor).',
    whenToUse: ['A tag must be added to an actor for grouping or queries.'],
    whenNotToUse: ['The actor already has the tag.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, tag: P.tag },
    required: ['tag'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'add_tag', actorName: 'PlayerStart_1', tag: 'Spawn' },
    exampleOutput: { success: true, message: 'Tag added' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'find_by_tag', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Find world actors by tag (cross-parent to control_actor).',
    whenToUse: ['All actors with a given tag must be enumerated.'],
    whenNotToUse: ['Actors must be found by class; use find_by_class.'],
    inputProps: { tag: P.tag },
    required: [],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'find_by_tag', tag: 'Spawn' },
    exampleOutput: { success: true, message: 'Actors found', actors: [] },
    outputProps: { actors: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Matching actor info objects.' } },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: 'Mismatch surfaced: TS inspect-actor-actions.ts routes find_by_tag to control_actor, while native McpAutomationBridge_EnvironmentHandlersInspect.cpp classifies find_by_tag as a GLOBAL inspect action (bIsGlobalAction). The two surfaces disagree on routing; preserved in metadata, not normalized away.',
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'create_snapshot', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'snapshot',
    summary: 'Create a property snapshot of a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s state must be captured for later restore.'],
    whenNotToUse: ['No restore is planned.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, snapshotName: P.snapshotName },
    required: [],
    effect: 'write', costLatency: 'interactive', costResources: 'low',
    exampleInput: { action: 'create_snapshot', actorName: 'PlayerStart_1', snapshotName: 'snap_01' },
    exampleOutput: { success: true, message: 'Snapshot created' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'restore_snapshot', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'snapshot',
    summary: 'Restore a previously created property snapshot onto a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s state must be restored from a snapshot.'],
    whenNotToUse: ['No snapshot exists for the actor.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, snapshotName: P.snapshotName },
    required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, costLatency: 'interactive', costResources: 'low',
    exampleInput: { action: 'restore_snapshot', actorName: 'PlayerStart_1', snapshotName: 'snap_01' },
    exampleOutput: { success: true, message: 'Snapshot restored' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'export', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Export a world actor to a file (cross-parent to control_actor).',
    whenToUse: ['An actor must be serialized to an external file.'],
    whenNotToUse: ['The actor should be duplicated in-scene; use control_actor duplicate.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'read', costLatency: 'interactive', costResources: 'low',
    exampleInput: { action: 'export', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Actor exported' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'delete_object', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Delete a world actor by name (cross-parent to control_actor; dispatches action delete).',
    whenToUse: ['A world actor must be permanently removed from the level.'],
    whenNotToUse: ['The target is an asset path; use manage_asset delete (TS returns a NOT_FOUND hint).'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'destructive', costLatency: 'interactive', costResources: 'low',
    exampleInput: { action: 'delete_object', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Actor deleted', deleted: 'PlayerStart_1' },
    outputProps: { deleted: { type: 'string', description: 'Name of the deleted actor.' } },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'list_objects', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'List world actors (cross-parent to control_actor; dispatches action list_actors).',
    whenToUse: ['All actors in the current level must be enumerated.'],
    whenNotToUse: ['Only tagged actors are needed; use find_by_tag.'],
    inputProps: { filter: P.filter },
    required: [],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'list_objects' },
    exampleOutput: { success: true, message: 'Actors listed', actors: [] },
    outputProps: { actors: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Actor info objects.' } },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'find_by_class', dispatchAction: 'find_by_class', domain: D, family: 'actor',
    summary: 'Find world actors by class name or /Script path.',
    whenToUse: ['All actors of a specific class must be enumerated.'],
    whenNotToUse: ['Actors must be found by tag; use find_by_tag.'],
    inputProps: { className: P.className, classPath: P.classPath },
    required: ['className'],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'find_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Actors found', objects: [] },
    outputProps: { objects: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Matching object info.' } },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_bounding_box', dispatchAction: 'control_actor', dispatchMode: 'action', domain: D, family: 'actor',
    summary: 'Return the world-space bounding box of a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s bounds must be read.'],
    whenNotToUse: ['The actor does not have a visible mesh.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'read', costLatency: 'instant', costResources: 'low',
    exampleInput: { action: 'get_bounding_box', actorName: 'Cube_1' },
    exampleOutput: { success: true, message: 'Bounding box' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: NR,
  }),
];
