// scripts/generate-console-command-policy.ts
// Deterministic generator for the one canonical console-command policy.
//
// Source of truth: src/utils/commands/console-command-policy-rules.ts
// (typed rule data from Task 6). It emits two generated artifacts from the
// SAME in-memory rule set so TypeScript and native transports share one policy:
//   - src/utils/commands/console-command-policy.generated.ts  (serialized mirror)
//   - plugins/.../ConsoleCommand/McpAutomationBridge_ConsoleCommandPolicy.generated.h
//
// Run:
//   node --loader ts-node/esm scripts/generate-console-command-policy.ts        (generate)
//   node --loader ts-node/esm scripts/generate-console-command-policy.ts --check (CI gate)
//
// The native header is what the C++ surface compiles against. The TypeScript
// artifact is a drift-detection mirror, NOT a runtime import: the validator
// (src/utils/commands/command-validator.ts) evaluates the typed rules through
// console-command-policy-generated.ts instead. Handwritten block lists were
// removed from the validator. This generator is deterministic: repeated runs
// produce byte-identical output, and --check fails (non-zero exit) when an
// on-disk artifact drifts.

import { existsSync, readFileSync, writeFileSync, renameSync, rmSync, mkdirSync, chmodSync, lstatSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

import {
  CONSOLE_COMMAND_POLICY_RULES,
  type ConsoleCommandPolicyRule,
  type ConsoleCommandPolicySurface,
  type ConsoleCommandRuleMatcher,
} from '../src/utils/commands/console-command-policy-rules.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

export const TS_PATH = resolve(root, 'src/utils/commands/console-command-policy.generated.ts');
export const NATIVE_PATH = resolve(
  root,
  'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/Domains/ConsoleCommand/McpAutomationBridge_ConsoleCommandPolicy.generated.h',
);

const TS_HEADER = `// GENERATED by scripts/generate-console-command-policy.ts -- do not edit.
`;
const NATIVE_HEADER = `// GENERATED by scripts/generate-console-command-policy.ts -- do not edit.
`;


function emitMatcher(matcher: ConsoleCommandRuleMatcher): string {
  switch (matcher.kind) {
    case 'contains-any':
      return `{ kind: 'contains-any', values: [${matcher.values.map((v) => jsString(v)).join(', ')}] }`;
    case 'first-token':
      return `{ kind: 'first-token', values: [${matcher.values.map((v) => jsString(v)).join(', ')}] }`;
    case 'whitespace-bounded-anywhere':
      return `{ kind: 'whitespace-bounded-anywhere', values: [${matcher.values.map((v) => jsString(v)).join(', ')}] }`;
    case 'pattern':
      return `{ kind: 'pattern', source: ${jsString(matcher.source)}, flags: ${jsString(matcher.flags)} }`;
    default: {
      const never: never = matcher;
      throw new Error(`Unhandled matcher: ${String(never)}`);
    }
  }
}

function jsString(value: string): string {
  // Emit a single-quoted, properly escaped JS string literal (lint-clean output).
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `'${escaped}'`;
}

function emitRule(rule: ConsoleCommandPolicyRule): string {
  return `  {
    id: ${jsString(rule.id)},
    appliesTo: ${jsString(rule.appliesTo)},
    reasonCode: ${jsString(rule.reasonCode)},
    matcher: ${emitMatcher(rule.matcher)},
  },`;
}

function nativeMatches(rule: ConsoleCommandPolicyRule, surface: ConsoleCommandPolicySurface): boolean {
  if (rule.appliesTo === 'both') return true;
  return rule.appliesTo === surface;
}

export function buildTsContent(): string {
  const rulesText = CONSOLE_COMMAND_POLICY_RULES.map(emitRule).join('\n');
  return (
    TS_HEADER +
    '// One canonical console-command policy shared by the TypeScript validator.\n' +
    '// Source of truth: scripts/generate-console-command-policy.ts ->\n' +
    '//   src/utils/commands/console-command-policy-rules.ts (Task 6 typed data).\n' +
    'export type ConsoleCommandGeneratedRule = {\n' +
    '  readonly id: string;\n' +
    '  readonly appliesTo: \'typescript\' | \'native\' | \'both\';\n' +
    '  readonly reasonCode: string;\n' +
    '  readonly matcher: unknown;\n' +
    '};\n\n' +
    'export const CONSOLE_COMMAND_POLICY_GENERATED_RULES: readonly ConsoleCommandGeneratedRule[] = [\n' +
    rulesText +
    '\n] as const;\n'
  );
}

export function emitNativeArray(name: string, items: readonly string[]): string {
  if (items.length === 0) {
    return `    static const TCHAR* const ${name}[] = {};\n`;
  }
  return (
    `    static const TCHAR* const ${name}[] = {\n` +
    items.map((item) => `        TEXT(${JSON.stringify(item)})`).join(',\n') +
    ',\n    };\n'
  );
}

export function buildNativeContent(): string {
  // Native artifact sources ONLY rules that apply to the native surface
  // (appliesTo === 'native' || 'both'). This guarantees zero runtime delta:
  // TS-only rules (flexible-import, flexible-call, dunder, os-system, etc.)
  // must never leak into the native validator.
  const nativeRules = CONSOLE_COMMAND_POLICY_RULES.filter((r) => nativeMatches(r, 'native'));

  const collectFirstToken = (reason: string): string[] => {
    const out: string[] = [];
    for (const r of nativeRules) {
      if (r.reasonCode === reason && r.matcher.kind === 'first-token') {
        out.push(...r.matcher.values);
      }
    }
    return Array.from(new Set(out));
  };
  const collectContains = (reason: string): string[] => {
    const out: string[] = [];
    for (const r of nativeRules) {
      if (r.reasonCode === reason && r.matcher.kind === 'contains-any') {
        out.push(...r.matcher.values);
      }
    }
    return Array.from(new Set(out));
  };

  // UNSAFE_SEPARATORS come from the shared.unsafe-separator rule (applies to both).
  const separatorRule = CONSOLE_COMMAND_POLICY_RULES.find(
    (r) => r.id === 'shared.unsafe-separator',
  );
  const tsUnsafeSeparators =
    separatorRule && separatorRule.matcher.kind === 'contains-any'
      ? Array.from(separatorRule.matcher.values)
      : [];
  // PYTHON first-token ('both') folds into BLOCKED_COMMANDS so the native
  // validator can drop its separate py/python Equals check without behavior change.
  const blocked = collectFirstToken('DANGEROUS_ENGINE_COMMAND')
    .concat(collectFirstToken('PYTHON_EXECUTION'));
  const restricted = collectFirstToken('RESTRICTED_ENGINE_COMMAND');
  const forbiddenNames = collectFirstToken('SHELL_COMMAND');
  const forbiddenTokens = collectContains('UNSAFE_TOKEN');

  return (
    NATIVE_HEADER +
    '// One canonical console-command policy shared by the native validator.\n' +
    '// Source of truth: scripts/generate-console-command-policy.ts ->\n' +
    '//   src/utils/commands/console-command-policy-rules.ts (Task 6 typed data).\n' +
    '// GENERATED artifacts are never hand-edited; re-run the generator after a rule change.\n' +
    '#pragma once\n' +
    '#include "CoreMinimal.h"\n\n' +
    'namespace McpGeneratedConsoleCommandPolicy\n{\n' +
    '    // Unsafe separators checked on both surfaces.\n' +
    '    static const TCHAR* const UNSAFE_SEPARATORS[] = {\n' +
    tsUnsafeSeparators.map((sep) => `        TEXT(${JSON.stringify(sep)})`).join(',\n') +
    ',\n    };\n\n' +
    '    // Commands blocked for security (DANGEROUS/RESTRICTED engine commands, py/python).\n' +
    emitNativeArray('BLOCKED_COMMANDS', blocked) +
    '\n' +
    emitNativeArray('RESTRICTED_COMMANDS', restricted) +
    '\n' +
    emitNativeArray('FORBIDDEN_COMMAND_NAMES', forbiddenNames) +
    '\n' +
    emitNativeArray('FORBIDDEN_TOKENS', forbiddenTokens) +
    '}\n'
  );
}

export type GeneratorResult = {
  readonly tsContent: string;
  readonly nativeContent: string;
};

export function buildConsoleCommandPolicy(): GeneratorResult {
  return {
    tsContent: buildTsContent(),
    nativeContent: buildNativeContent(),
  };
}

// ----------------------------------------------------------------------------
// Transactional write (mirror of scripts/gateway-manifest/write.ts).
// ----------------------------------------------------------------------------

const FINAL_FILE_MODE = 0o644;
const TEMP_FILE_MODE = 0o600;

function writeTargetTransactional(path: string, content: string): void {
  if (existsSync(path) && lstatSync(path).isSymbolicLink()) {
    throw new Error(`refusing to overwrite a symlink final target: ${path}`);
  }
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const tmp = `${path}.tmp-${randomUUID()}`;
  writeFileSync(tmp, content, { flag: 'wx', mode: TEMP_FILE_MODE });
  try {
    renameSync(tmp, path);
    chmodSync(path, FINAL_FILE_MODE);
  } catch (error) {
    rmSync(tmp, { force: true });
    throw error;
  }
}

export function runConsoleCommandPolicyGenerator(): { tsContent: string; nativeContent: string } {
  const { tsContent, nativeContent } = buildConsoleCommandPolicy();
  writeTargetTransactional(TS_PATH, tsContent);
  writeTargetTransactional(NATIVE_PATH, nativeContent);
  return { tsContent, nativeContent };
}

function checkDrift(): boolean {
  let drift = false;
  const { tsContent, nativeContent } = buildConsoleCommandPolicy();
  const targets: readonly [string, string][] = [
    [TS_PATH, tsContent],
    [NATIVE_PATH, nativeContent],
  ];
  for (const [path, content] of targets) {
    if (!existsSync(path)) {
      console.error(`[console-command-policy] DRIFT: ${path} is missing. Run scripts/generate-console-command-policy.ts`);
      drift = true;
      continue;
    }
    const existing = readFileSync(path, 'utf8');
    if (existing !== content) {
      console.error(`[console-command-policy] DRIFT: ${path} is stale. Run scripts/generate-console-command-policy.ts`);
      drift = true;
    }
  }
  return drift;
}

function main(): void {
  const mode = process.argv.slice(2).includes('--check') ? 'check' : 'generate';
  if (mode === 'check') {
    const drift = checkDrift();
    if (drift) {
      console.error('\n[console-command-policy] CHECK EXIT=1 (generated artifacts drifted)');
      process.exit(1);
    }
    console.error('[console-command-policy] CHECK EXIT=0 (generated artifacts up to date)');
    process.exit(0);
  }
  runConsoleCommandPolicyGenerator();
  console.error('[console-command-policy] GENERATED TS + native policy artifacts');
  process.exit(0);
}

// Node ESM entrypoint guard.
function isMainModule(): boolean {
  if (!process.argv[1]) return false;
  try {
    return resolve(process.argv[1]) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

if (isMainModule()) {
  try {
    main();
  } catch (error: unknown) {
    const message = error instanceof Error ? (error.stack ?? error.message) : String(error);
    console.error('[console-command-policy] generator failed:', message);
    process.exit(1);
  }
}
