// scripts/generate-gateway-manifest.ts
// Deterministic generator for the neutral gateway manifest.
// Source of truth: src/tools/catalog/consolidated-tool-definitions.ts
// Emits three artifacts from one in-memory model (no hand-maintained drift):
//   - src/gateway/gateway-manifest.generated.ts  (runtime import; compiled into dist)
//   - src/gateway/gateway-manifest.generated.json (neutral asset; parity/test source)
//   - plugins/.../Gateway/McpNativeGatewayManifest.h (compact embedded JSON for native)
// Run: node --loader ts-node/esm scripts/generate-gateway-manifest.ts [generate|check|--pilot]

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GatewayManifestSchema } from '../src/gateway/gateway-manifest-types.js';
import type { CapabilityRecord } from '../src/tools/catalog/capabilities/model.js';
import { consolidatedToolDefinitions } from '../src/tools/catalog/consolidated-tool-definitions.js';
import { compactManifest, MANIFEST_H, prettyManifest } from './gateway-manifest/emit.js';
import { defaultPilotCatalogPath, loadPilotCatalogRaw } from './gateway-manifest/load.js';
import { resolvePilotOutputDir, validatePilotCatalogPath } from './gateway-manifest/path-policy.js';
import { pilotHeaderText, pilotJson, pilotTsText } from './gateway-manifest/pilot.js';
import {
  PilotCatalogValidationError,
  type PilotValidationError,
  validatePilotCatalog
} from './gateway-manifest/validate.js';
import { checkManifestDrift, type ManifestDriftEntry, type ManifestTarget, writeManifestTargets } from './gateway-manifest/write.js';

export { buildGatewayManifest } from './gateway-manifest/build.js';
export { prettyManifest } from './gateway-manifest/emit.js';

export type PilotCheckOutcome =
  | { readonly kind: 'up_to_date' }
  | { readonly kind: 'drift'; readonly entries: readonly ManifestDriftEntry[] }
  | { readonly kind: 'validation_error'; readonly errors: readonly PilotValidationError[] };

const GENERATED_TS_HEADER = `/* eslint-disable */
// GENERATED by scripts/generate-gateway-manifest.ts -- do not edit.
// Re-run the generator after changing canonical tool definitions.
export const gatewayManifest = `;

function buildProductionTargets(root: string): ManifestTarget[] {
  const pretty = prettyManifest(consolidatedToolDefinitions);
  const compact = compactManifest(consolidatedToolDefinitions);
  return [
    [resolve(root, 'src/gateway/gateway-manifest.generated.ts'), `${GENERATED_TS_HEADER}${pretty};\n`],
    [resolve(root, 'src/gateway/gateway-manifest.generated.json'), `${pretty}\n`],
    [resolve(root, 'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/MCP/Gateway/McpNativeGatewayManifest.h'), MANIFEST_H(compact)],
  ];
}

function pilotOutputDir(root: string): string {
  return resolvePilotOutputDir(process.env.MCP_PILOT_OUTPUT_DIR, root);
}

function reportPilotValidationErrors(errors: readonly PilotValidationError[]): void {
  console.error('[gateway-manifest] pilot: canonical catalog validation failed:');
  for (const err of errors) {
    const idPart = err.canonicalId ? ` [id=${err.canonicalId}]` : '';
    console.error(`  ${err.pointer}: ${err.message}${idPart}`);
  }
}

function loadPilotCatalog(root: string, expectedIds?: readonly string[]): readonly CapabilityRecord[] {
  const catalogPath = validatePilotCatalogPath(defaultPilotCatalogPath(root), root);
  const raw = loadPilotCatalogRaw(catalogPath);
  const result = validatePilotCatalog(raw, expectedIds);
  if (!result.success) {
    throw new PilotCatalogValidationError(result.errors);
  }
  return result.records;
}

function loadExpectedPilotIds(root: string): readonly string[] | undefined {
  const pilotJsonPath = resolve(pilotOutputDir(root), 'pilot-manifest.json');
  if (!existsSync(pilotJsonPath)) return undefined;
  let text: string;
  try {
    text = readFileSync(pilotJsonPath, 'utf8');
  } catch (error) {
    console.warn(
      `[gateway-manifest] pilot: existing pilot output ${pilotJsonPath} exists but could not be read ` +
      `(${error instanceof Error ? error.message : String(error)}). Falling back to ordinary stale-drift check; ` +
      'expected-ID removal detection is disabled for this run. Regenerate pilot output to restore it.'
    );
    return undefined;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    console.warn(
      `[gateway-manifest] pilot: existing pilot output ${pilotJsonPath} is not valid JSON ` +
      `(${error instanceof Error ? error.message : String(error)}). Falling back to ordinary stale-drift check; ` +
      'expected-ID removal detection is disabled for this run. Regenerate pilot output to restore it.'
    );
    return undefined;
  }
  const result = GatewayManifestSchema.safeParse(parsed);
  if (!result.success) {
    console.warn(
      `[gateway-manifest] pilot: existing pilot output ${pilotJsonPath} failed schema validation ` +
      `(${result.error.issues.map((i) => i.message).join('; ')}). Falling back to ordinary stale-drift check; ` +
      'expected-ID removal detection is disabled for this run. Regenerate pilot output to restore it.'
    );
    return undefined;
  }
  return result.data.tools.map((t) => t.name);
}

function buildPilotTargets(root: string, records: readonly CapabilityRecord[]): ManifestTarget[] {
  const dir = pilotOutputDir(root);
  return [
    [resolve(dir, 'pilot-manifest.json'), pilotJson(records)],
    [resolve(dir, 'pilot-manifest.ts'), pilotTsText(records)],
    [resolve(dir, 'pilot-manifest.h'), pilotHeaderText(records)],
  ];
}

function runPilotGenerate(root: string): void {
  let records: readonly CapabilityRecord[];
  try {
    records = loadPilotCatalog(root);
  } catch (error) {
    if (error instanceof PilotCatalogValidationError) {
      reportPilotValidationErrors(error.errors);
      process.exitCode = 1;
      return;
    }
    throw error;
  }
  const targets = buildPilotTargets(root, records);
  writeManifestTargets(targets);
  console.log(`[gateway-manifest] pilot: wrote ${targets.length} files to ${pilotOutputDir(root)}`);
}

export function runPilotCheck(root: string): PilotCheckOutcome {
  const expectedIds = loadExpectedPilotIds(root);
  let records: readonly CapabilityRecord[];
  try {
    records = loadPilotCatalog(root, expectedIds);
  } catch (error) {
    if (error instanceof PilotCatalogValidationError) {
      reportPilotValidationErrors(error.errors);
      process.exitCode = 1;
      return { kind: 'validation_error', errors: error.errors };
    }
    throw error;
  }
  const targets = buildPilotTargets(root, records);
  const result = checkManifestDrift(targets);
  if (result.drift) {
    process.exitCode = 1;
    return { kind: 'drift', entries: result.entries };
  }
  console.log('[gateway-manifest] pilot: manifest artifacts are up to date.');
  return { kind: 'up_to_date' };
}

function main(): void {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const args = process.argv.slice(2);
  const isCheck = args.includes('--check');
  const isPilot = args.includes('--pilot');

  if (isPilot) {
    if (isCheck) runPilotCheck(root);
    else runPilotGenerate(root);
    return;
  }

  const targets = buildProductionTargets(root);

  if (isCheck) {
    const result = checkManifestDrift(targets);
    if (result.drift) process.exitCode = 1;
    else console.log('[gateway-manifest] check: manifest artifacts are up to date.');
  } else {
    writeManifestTargets(targets);
    console.log(`[gateway-manifest] wrote ${targets.length} manifest artifacts.`);
  }
}

if (process.argv[1]?.endsWith('generate-gateway-manifest.ts')) main();
