/* eslint-disable */
// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.
// Re-run the generator after changing canonical tool definitions or capability records.

export interface GeneratedParentRoutingEntry {
  readonly name: string;
  readonly category: 'core' | 'world' | 'gameplay' | 'utility';
  readonly handlerKey: string;
}

export const GENERATED_PARENT_ROUTING: readonly GeneratedParentRoutingEntry[] = [
  {
    "name": "animation_physics",
    "category": "gameplay",
    "handlerKey": "animation"
  },
  {
    "name": "build_environment",
    "category": "world",
    "handlerKey": "environment"
  },
  {
    "name": "control_actor",
    "category": "core",
    "handlerKey": "actor"
  },
  {
    "name": "control_editor",
    "category": "core",
    "handlerKey": "editor"
  },
  {
    "name": "inspect",
    "category": "core",
    "handlerKey": "inspect"
  },
  {
    "name": "manage_ai",
    "category": "gameplay",
    "handlerKey": "ai"
  },
  {
    "name": "manage_asset",
    "category": "core",
    "handlerKey": "asset"
  },
  {
    "name": "manage_audio",
    "category": "utility",
    "handlerKey": "audio"
  },
  {
    "name": "manage_blueprint",
    "category": "core",
    "handlerKey": "blueprint"
  },
  {
    "name": "manage_character",
    "category": "gameplay",
    "handlerKey": "character"
  },
  {
    "name": "manage_combat",
    "category": "gameplay",
    "handlerKey": "combat"
  },
  {
    "name": "manage_effect",
    "category": "gameplay",
    "handlerKey": "effect"
  },
  {
    "name": "manage_gas",
    "category": "gameplay",
    "handlerKey": "gas"
  },
  {
    "name": "manage_geometry",
    "category": "world",
    "handlerKey": "geometry"
  },
  {
    "name": "manage_interaction",
    "category": "gameplay",
    "handlerKey": "interaction"
  },
  {
    "name": "manage_inventory",
    "category": "gameplay",
    "handlerKey": "inventory"
  },
  {
    "name": "manage_level",
    "category": "core",
    "handlerKey": "level"
  },
  {
    "name": "manage_level_structure",
    "category": "world",
    "handlerKey": "levelStructure"
  },
  {
    "name": "manage_networking",
    "category": "utility",
    "handlerKey": "networking"
  },
  {
    "name": "manage_pcg",
    "category": "world",
    "handlerKey": "pcg"
  },
  {
    "name": "manage_sequence",
    "category": "utility",
    "handlerKey": "sequence"
  },
  {
    "name": "manage_tools",
    "category": "core",
    "handlerKey": "tools"
  },
  {
    "name": "system_control",
    "category": "core",
    "handlerKey": "system"
  }
];
