/**
 * manage_gas capability records (31 actions). Grounded in manage-gas-tool.ts
 * action enum, gas-action-routes.ts, gas-handlers.ts, and the native GAS domain
 * (Plugins/.../Private/Domains/GAS/). All 31 are editor authoring of GAS
 * assets; the GameplayAbilities plugin gates them (native returns EDITOR_ONLY
 * when the plugin is absent).
 *
 * Each record declares exactly the parameters its own action accepts: the
 * required set comes from gas-action-routes.ts, the optional set from the fields
 * the matching native handler reads. Action-specific parameters live in
 * ./gas.props.ts; only genuinely shared ones come from ../properties.js.
 */
import type { CapabilityRecordSource } from '../../../index.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { GAS_P as G } from './gas.props.js';

const T = 'manage_gas';
const F = 'gas';
const W = ['A Gameplay Ability System asset must be authored.'];
const GAS_PLUGIN = ['GameplayAbilities'];
const PROMOTED = 'Promoted from a hidden native GAS route after the gateway migration.';
const POST = 'post-migration' as const;

export const GAS_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.add_ability_system_component`, action: 'add_ability_system_component', family: F,
    summary: 'Add an AbilitySystemComponent to a Blueprint.', whenToUse: W, whenNotToUse: ['Component exists.'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, componentName: G.componentName }, required: ['action', 'blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_ability_system_component', blueprintPath: '/Game/BP_Char', componentName: 'AbilitySystemComponent' }, exampleOutput: { success: true, message: 'ASC added' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_asc`, action: 'configure_asc', family: F,
    summary: 'Configure an AbilitySystemComponent.', whenToUse: ['ASC defaults must change.'], whenNotToUse: ['Use add_ability_system_component.'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, componentName: G.componentName, replicationMode: G.replicationMode }, required: ['action', 'blueprintPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'configure_asc', blueprintPath: '/Game/BP_Char', replicationMode: 'Mixed' }, exampleOutput: { success: true, message: 'ASC configured' } }),
  buildRecord({ parentTool: T, id: `${T}.create_attribute_set`, action: 'create_attribute_set', family: F,
    summary: 'Create an AttributeSet class/asset.', whenToUse: W, whenNotToUse: ['Use add_attribute.'],
    inputProps: { action: P.action, name: P.name, path: P.path }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_attribute_set', name: 'AS_Char' }, exampleOutput: { success: true, message: 'AttributeSet created' } }),
  buildRecord({ parentTool: T, id: `${T}.add_attribute`, action: 'add_attribute', family: F,
    summary: 'Add an attribute to an AttributeSet.', whenToUse: ['An attribute is needed.'], whenNotToUse: ['Use create_attribute_set.'],
    inputProps: { action: P.action, attributeSetPath: P.attributeSetPath, attributeName: P.attributeName, attributeType: G.attributeType, defaultValue: G.defaultValue }, required: ['action', 'attributeSetPath', 'attributeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_attribute', attributeSetPath: '/Game/AS_Char', attributeName: 'Health', attributeType: 'Health', defaultValue: 100 }, exampleOutput: { success: true, message: 'Attribute added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_attribute_base_value`, action: 'set_attribute_base_value', family: F,
    summary: 'Set an attribute base value.', whenToUse: ['Default value must change.'], whenNotToUse: ['Use add_attribute.'],
    inputProps: { action: P.action, attributeSetPath: P.attributeSetPath, attributeName: P.attributeName, baseValue: G.baseValue }, required: ['action', 'attributeSetPath', 'attributeName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_attribute_base_value', attributeSetPath: '/Game/AS_Char', attributeName: 'Health', baseValue: 100 }, exampleOutput: { success: true, message: 'Base value set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_attribute_clamping`, action: 'set_attribute_clamping', family: F,
    summary: 'Configure attribute min/max clamping.', whenToUse: ['Attribute must clamp.'], whenNotToUse: ['Use set_attribute_base_value.'],
    inputProps: { action: P.action, attributeSetPath: P.attributeSetPath, attributeName: P.attributeName, clampMode: G.clampMode, minValue: P.num_, maxValue: P.num_ }, required: ['action', 'attributeSetPath', 'attributeName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_attribute_clamping', attributeSetPath: '/Game/AS_Char', attributeName: 'Health', clampMode: 'MinMax', minValue: 0, maxValue: 100 }, exampleOutput: { success: true, message: 'Clamping set' } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_ability`, action: 'create_gameplay_ability', family: F,
    summary: 'Create a Gameplay Ability asset.', whenToUse: W, whenNotToUse: ['Use add_ability_task.'],
    inputProps: { action: P.action, name: P.name, path: P.path }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    outputProps: { assetPath: P.assetPath }, outputRequired: ['assetPath'],
    exampleInput: { action: 'create_gameplay_ability', name: 'GA_Fire' }, exampleOutput: { success: true, message: 'Ability created', assetPath: '/Game/GA_Fire' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_tags`, action: 'set_ability_tags', family: F,
    summary: 'Configure ability tag requirements/granted.', whenToUse: ['Ability tags must change.'], whenNotToUse: ['Use create_gameplay_ability.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, abilityTags: G.abilityTags, cancelAbilitiesWithTag: G.cancelAbilitiesWithTag, blockAbilitiesWithTag: G.blockAbilitiesWithTag, activationRequiredTags: G.activationRequiredTags, activationBlockedTags: G.activationBlockedTags }, required: ['action', 'abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_tags', abilityPath: '/Game/GA_Fire', abilityTags: ['Ability.Fire'] }, exampleOutput: { success: true, message: 'Ability tags set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_costs`, action: 'set_ability_costs', family: F,
    summary: 'Configure ability cost (attribute spend).', whenToUse: ['Ability has a cost.'], whenNotToUse: ['Use set_ability_cooldown.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, costEffectPath: G.costEffectPath }, required: ['action', 'abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_costs', abilityPath: '/Game/GA_Fire', costEffectPath: '/Game/GE_ManaCost' }, exampleOutput: { success: true, message: 'Ability costs set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_cooldown`, action: 'set_ability_cooldown', family: F,
    summary: 'Configure ability cooldown.', whenToUse: ['Ability needs cooldown.'], whenNotToUse: ['Use set_ability_costs.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, cooldownEffectPath: G.cooldownEffectPath }, required: ['action', 'abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_cooldown', abilityPath: '/Game/GA_Fire', cooldownEffectPath: '/Game/GE_Cooldown' }, exampleOutput: { success: true, message: 'Cooldown set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_targeting`, action: 'set_ability_targeting', family: F,
    summary: 'Configure ability targeting spec.', whenToUse: ['Ability targets actors.'], whenNotToUse: ['No targeting.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, targetingMode: G.targetingMode, targetRange: G.targetRange, aoeRadius: G.aoeRadius }, required: ['action', 'abilityPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_targeting', abilityPath: '/Game/GA_Fire', targetingMode: 'AOE', targetRange: 1000, aoeRadius: 250 }, exampleOutput: { success: true, message: 'Targeting set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_ability_task`, action: 'add_ability_task', family: F,
    summary: 'Add a task node to an ability.', whenToUse: ['Ability needs a task.'], whenNotToUse: ['Use create_gameplay_ability.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, taskType: P.string_ }, required: ['action', 'abilityPath', 'taskType'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_ability_task', abilityPath: '/Game/GA_Fire', taskType: 'PlayMontageAndWait' }, exampleOutput: { success: true, message: 'Ability task added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_activation_policy`, action: 'set_activation_policy', family: F,
    summary: 'Configure ability activation policy.', whenToUse: ['Activation trigger must change.'], whenNotToUse: ['Default policy.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, activationPolicy: G.activationPolicy }, required: ['action', 'abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    normalizationClass: 'F_OBSOLETE_VERSION_SPECIFIC', normalizationRationale: 'Native reads raw field + normalized policy; map documented in route-disposition ledger (route:gas:set_activation_policy).',
    exampleInput: { action: 'set_activation_policy', abilityPath: '/Game/GA_Fire', activationPolicy: 'OnInputPressed' }, exampleOutput: { success: true, message: 'Activation policy set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_instancing_policy`, action: 'set_instancing_policy', family: F,
    summary: 'Configure ability instancing policy.', whenToUse: ['Instancing must change.'], whenNotToUse: ['Use set_activation_policy.'],
    inputProps: { action: P.action, abilityPath: P.abilityPath, instancingPolicy: G.instancingPolicy }, required: ['action', 'abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_instancing_policy', abilityPath: '/Game/GA_Fire', instancingPolicy: 'InstancedPerActor' }, exampleOutput: { success: true, message: 'Instancing policy set' } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_effect`, action: 'create_gameplay_effect', family: F,
    summary: 'Create a Gameplay Effect asset.', whenToUse: W, whenNotToUse: ['Use add_effect_modifier.'],
    inputProps: { action: P.action, name: P.name, path: P.path, durationType: G.durationType }, required: ['action', 'name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_gameplay_effect', name: 'GE_Damage', durationType: 'Instant' }, exampleOutput: { success: true, message: 'Gameplay effect created' } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_duration`, action: 'set_effect_duration', family: F,
    summary: 'Set a Gameplay Effect duration.', whenToUse: ['Effect has a duration.'], whenNotToUse: ['Use create_gameplay_effect.'],
    inputProps: { action: P.action, effectPath: P.effectPath, durationType: G.durationType, duration: P.duration, period: G.period }, required: ['action', 'effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_duration', effectPath: '/Game/GE_Damage', durationType: 'HasDuration', duration: 5, period: 1 }, exampleOutput: { success: true, message: 'Effect duration set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_modifier`, action: 'add_effect_modifier', family: F,
    summary: 'Add a modifier to a Gameplay Effect.', whenToUse: ['Effect modifies an attribute.'], whenNotToUse: ['Use set_effect_duration.'],
    inputProps: { action: P.action, effectPath: P.effectPath, attributeName: P.attributeName, modifierOperation: G.modifierOperation, modifierMagnitude: G.modifierMagnitude, targetAttribute: G.targetAttribute }, required: ['action', 'effectPath', 'attributeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_modifier', effectPath: '/Game/GE_Damage', attributeName: 'Health', modifierOperation: 'Add', modifierMagnitude: -10 }, exampleOutput: { success: true, message: 'Effect modifier added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_modifier_magnitude`, action: 'set_modifier_magnitude', family: F,
    summary: 'Set a modifier magnitude.', whenToUse: ['Modifier amount must change.'], whenNotToUse: ['Use add_effect_modifier.'],
    inputProps: { action: P.action, effectPath: P.effectPath, modifierIndex: G.modifierIndex, modifierMagnitude: G.modifierMagnitude, magnitudeCalculationType: G.magnitudeCalculationType, setByCallerTag: G.setByCallerTag }, required: ['action', 'effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_modifier_magnitude', effectPath: '/Game/GE_Damage', modifierIndex: 0, modifierMagnitude: -15 }, exampleOutput: { success: true, message: 'Modifier magnitude set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_execution_calculation`, action: 'add_effect_execution_calculation', family: F,
    summary: 'Add an execution calculation to an effect.', whenToUse: ['Complex magnitude calc needed.'], whenNotToUse: ['Simple modifier suffices.'],
    inputProps: { action: P.action, effectPath: P.effectPath, calculationClass: P.string_ }, required: ['action', 'effectPath', 'calculationClass'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_execution_calculation', effectPath: '/Game/GE_Damage', calculationClass: '/Script/Game.DamageExecCalc' }, exampleOutput: { success: true, message: 'Execution calc added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_cue`, action: 'add_effect_cue', family: F,
    summary: 'Add a gameplay cue to an effect.', whenToUse: ['Effect needs a cue.'], whenNotToUse: ['Use create_gameplay_cue_notify.'],
    inputProps: { action: P.action, effectPath: P.effectPath, cueTag: P.tag }, required: ['action', 'effectPath', 'cueTag'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_cue', effectPath: '/Game/GE_Damage', cueTag: 'GameplayCue.Damage' }, exampleOutput: { success: true, message: 'Effect cue added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_stacking`, action: 'set_effect_stacking', family: F,
    summary: 'Configure effect stacking rules.', whenToUse: ['Effects must stack.'], whenNotToUse: ['Use set_effect_duration.'],
    inputProps: { action: P.action, effectPath: P.effectPath, stackingType: G.stackingType, stackLimitCount: G.stackLimitCount, stackDurationRefreshPolicy: G.stackDurationRefreshPolicy, stackPeriodResetPolicy: G.stackPeriodResetPolicy, stackExpirationPolicy: G.stackExpirationPolicy }, required: ['action', 'effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_stacking', effectPath: '/Game/GE_Damage', stackingType: 'AggregateByTarget', stackLimitCount: 3 }, exampleOutput: { success: true, message: 'Stacking set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_tags`, action: 'set_effect_tags', family: F,
    summary: 'Configure effect gr/asset tags.', whenToUse: ['Effect tags must change.'], whenNotToUse: ['Use add_effect_cue.'],
    inputProps: { action: P.action, effectPath: P.effectPath, grantedTags: G.grantedTags, applicationRequiredTags: G.applicationRequiredTags, removalTags: G.removalTags, immunityTags: G.immunityTags }, required: ['action', 'effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_tags', effectPath: '/Game/GE_Damage', grantedTags: ['State.Burning'] }, exampleOutput: { success: true, message: 'Effect tags set' } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_cue_notify`, action: 'create_gameplay_cue_notify', family: F,
    summary: 'Create a Gameplay Cue Notify asset.', whenToUse: W, whenNotToUse: ['Use add_effect_cue.'],
    inputProps: { action: P.action, name: P.name, path: P.path, cueType: P.string_, cueTag: P.tag }, required: ['action', 'name', 'cueType'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_gameplay_cue_notify', name: 'GC_Damage', cueType: 'Static', cueTag: 'GameplayCue.Damage' }, exampleOutput: { success: true, message: 'Cue notify created' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_cue_trigger`, action: 'configure_cue_trigger', family: F,
    summary: 'Configure a gameplay cue trigger.', whenToUse: ['Cue trigger must change.'], whenNotToUse: ['Use create_gameplay_cue_notify.'],
    inputProps: { action: P.action, cuePath: P.cuePath, triggerType: G.triggerType }, required: ['action', 'cuePath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'configure_cue_trigger', cuePath: '/Game/GC_Damage', triggerType: 'Executed' }, exampleOutput: { success: true, message: 'Cue trigger configured' } }),
  buildRecord({ parentTool: T, id: `${T}.set_cue_effects`, action: 'set_cue_effects', family: F,
    summary: 'Set cue effect parameters.', whenToUse: ['Cue FX must change.'], whenNotToUse: ['Use configure_cue_trigger.'],
    inputProps: { action: P.action, cuePath: P.cuePath, particleSystemPath: G.particleSystemPath, soundPath: G.soundPath, cameraShakePath: G.cameraShakePath, decalPath: G.decalPath }, required: ['action', 'cuePath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_cue_effects', cuePath: '/Game/GC_Damage', particleSystemPath: '/Game/FX/P_Damage' }, exampleOutput: { success: true, message: 'Cue effects set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_tag_to_asset`, action: 'add_tag_to_asset', family: F,
    summary: 'Add a gameplay tag to an asset.', whenToUse: ['Asset must carry a tag.'], whenNotToUse: ['Use set_effect_tags.'],
    inputProps: { action: P.action, assetPath: P.assetPath, tagName: P.string_, tag: P.tag }, required: ['action', 'assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_tag_to_asset', assetPath: '/Game/GA_Fire', tagName: 'Ability.Fire' }, exampleOutput: { success: true, message: 'Tag added' } }),
  buildRecord({ parentTool: T, id: `${T}.get_gas_info`, action: 'get_gas_info', family: F,
    summary: 'Read GAS asset metadata.', whenToUse: ['Inspect GAS assets.'], whenNotToUse: ['Mutate assets.'],
    inputProps: { action: P.action, assetPath: P.assetPath }, required: ['action', 'assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: GAS_PLUGIN,
    // `abilityCount` was declared but is never set by the handler
    // (McpAutomationBridge_GASHandlersInfo.cpp), so output projection produced
    // an empty payload and get_gas_info reported success carrying nothing.
    // Declared below is exactly what the handler emits.
    outputProps: {
      gasType: P.string_, assetName: P.string_, assetPath: P.assetPath,
      class: P.string_, parentClass: P.string_, generatedClass: P.string_,
      durationPolicy: P.string_, instancingPolicy: P.string_,
      netExecutionPolicy: P.string_, stackingType: P.string_,
      modifierCount: P.num_, cueCount: P.num_,
    }, outputRequired: [],
      exampleInput: { action: 'get_gas_info', assetPath: '/Game/BP_Char' }, exampleOutput: { success: true, message: 'GAS info', gasType: 'GameplayAbility', assetName: 'GA_Dash', instancingPolicy: 'InstancedPerActor' } }),
  buildRecord({ parentTool: T, id: `${T}.create_ability_set`, action: 'create_ability_set', family: F,
    summary: 'Create a Gameplay Ability Set blueprint that groups abilities granted together.',
    whenToUse: ['Several abilities are always granted as one unit.'],
    whenNotToUse: ['A single ability is enough; use create_gameplay_ability.'],
    inputProps: { action: P.action, setPath: G.setPath, assetPath: P.assetPath, setName: G.setName },
    required: ['action'], requiredOneOf: ['setPath', 'assetPath'],
    outputProps: { setPath: G.setPath, status: P.string_, setName: G.setName, assetName: P.string_, variables: P.arrayOfStrings }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_ability_set', setPath: '/Game/GAS/AS_Hero', setName: 'HeroCore' },
    exampleOutput: { success: true, message: 'Ability set created', setPath: '/Game/GAS/AS_Hero', status: 'created', setName: 'HeroCore' },
    normalizationRationale: PROMOTED, normalizationProvenance: POST }),
  buildRecord({ parentTool: T, id: `${T}.add_ability`, action: 'add_ability', family: F,
    summary: 'Add an ability to an existing Gameplay Ability Set.',
    whenToUse: ['An ability must join a set that already exists.'],
    whenNotToUse: ['The ability is granted directly to an actor; use grant_ability.'],
    inputProps: { action: P.action, setPath: G.setPath, abilityPath: P.abilityPath, abilityClass: G.abilityClass },
    required: ['action', 'setPath'], requiredOneOf: ['abilityPath', 'abilityClass'],
    outputProps: { setPath: G.setPath, abilityPath: P.abilityPath, abilityClass: G.abilityClass, note: P.string_ }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_ability', setPath: '/Game/GAS/AS_Hero', abilityPath: '/Game/GAS/GA_Dash' },
    exampleOutput: { success: true, message: 'Ability added', setPath: '/Game/GAS/AS_Hero', abilityPath: '/Game/GAS/GA_Dash' },
    normalizationRationale: PROMOTED, normalizationProvenance: POST }),
  buildRecord({ parentTool: T, id: `${T}.grant_ability`, action: 'grant_ability', family: F,
    summary: 'Grant an ability to an actor blueprint that owns an AbilitySystemComponent.',
    whenToUse: ['An actor must start play already owning an ability.'],
    whenNotToUse: ['The ability belongs to a reusable set; use add_ability.'],
    inputProps: { action: P.action, actorPath: G.actorPath, blueprintPath: P.blueprintPath, abilityPath: P.abilityPath, abilityClass: G.abilityClass, abilityLevel: G.abilityLevel, inputID: G.inputID },
    required: ['action'], requiredOneOf: ['actorPath', 'blueprintPath'],
    outputProps: { actorPath: G.actorPath, abilityClass: G.abilityClass, abilityLevel: G.abilityLevel, inputID: G.inputID, hasASC: P.bool_, createdInitialAbilitiesVar: P.bool_, note: P.string_ }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'grant_ability', actorPath: '/Game/BP_Hero', abilityPath: '/Game/GAS/GA_Dash', abilityLevel: 1, inputID: 3 },
    exampleOutput: { success: true, message: 'Ability granted', actorPath: '/Game/BP_Hero', abilityLevel: 1, inputID: 3, hasASC: true },
    normalizationRationale: PROMOTED, normalizationProvenance: POST }),
  buildRecord({ parentTool: T, id: `${T}.create_execution_calculation`, action: 'create_execution_calculation', family: F,
    summary: 'Create a GameplayEffectExecutionCalculation blueprint for custom effect math.',
    whenToUse: ['Effect magnitude needs code the modifier curve cannot express.'],
    whenNotToUse: ['A scalable float or attribute-based modifier is enough.'],
    inputProps: { action: P.action, name: P.name, path: P.path },
    required: ['action', 'name'],
    outputProps: { assetPath: P.assetPath, name: P.name, parentClass: P.string_, reusedExisting: P.bool_, variablesAdded: P.arrayOfStrings, note: P.string_ }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_execution_calculation', name: 'GEEC_Damage', path: '/Game/GAS' },
    exampleOutput: { success: true, message: 'Execution calculation created', assetPath: '/Game/GAS/GEEC_Damage', name: 'GEEC_Damage', reusedExisting: false },
    normalizationRationale: PROMOTED, normalizationProvenance: POST }),
];
