/**
 * Timeline lifecycle records: create, open, duplicate, rename, delete, list.
 *
 * Grounded in sequence-core-actions.ts (create/open) and
 * sequence-asset-actions.ts (duplicate/rename/delete/get_metadata/list).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildRecord, P, SEQ_PLUGINS } from './helpers.js';

const FAMILY = 'timeline';
const DOMAIN = 'sequence';
const NR = 'Distinct Sequencer lifecycle operation with unique target and rollback semantics.';

export const TIMELINE_LIFECYCLE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'sequence.create',
    action: 'create',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a new Level Sequence asset in the content browser.',
    whenToUse: ['A new cinematic or animation sequence asset is needed.'],
    whenNotToUse: ['An existing sequence should be opened instead.'],
    inputProps: { action: P.action, name: P.name, path: P.path },
    required: ['action', 'name'],
    // Native HandleSequenceCreate (SequenceHandlersAssetCreation.cpp:5-109)
    // never emits sequencePath: it verifies with assetPath/assetName/assetClass/
    // existsAfter (AddAssetVerification) on create, or verifiedPath/existsAfter
    // (VerifyAssetExists) when the asset already exists. Declared exactly.
    outputProps: {
      assetPath: { type: 'string', description: 'Created sequence asset path (verification).' },
      assetName: { type: 'string', description: 'Created sequence asset name (verification).' },
      assetClass: { type: 'string', description: 'Created sequence asset class (verification).' },
      verifiedPath: { type: 'string', description: 'Verified existing asset path.' },
      existsAfter: { type: 'boolean', description: 'Whether the asset existed after the call.' },
    },
    outputRequired: [],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'create', name: 'SEQ_Master', path: '/Game/Cinematics' },
    exampleOutput: { success: true, assetPath: '/Game/Cinematics/SEQ_Master', assetName: 'SEQ_Master', existsAfter: true },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
  buildRecord({
    id: 'sequence.open',
    action: 'open',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Open an existing Level Sequence in the Sequencer editor.',
    whenToUse: ['An existing sequence must be opened for editing.'],
    whenNotToUse: ['A new sequence should be created instead.'],
    inputProps: { action: P.action, path: P.path },
    required: ['action', 'path'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'open', path: '/Game/Cinematics/SEQ_Master' },
    exampleOutput: { success: true, message: 'Sequence opened' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
  buildRecord({
    id: 'sequence.duplicate',
    action: 'duplicate',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Duplicate a Level Sequence asset to a new destination.',
    whenToUse: ['A sequence must be copied to a different folder or name.'],
    whenNotToUse: ['The sequence should be renamed in place.'],
    inputProps: { action: P.action, path: P.path, destinationPath: P.destinationPath, newName: P.newName },
    required: ['action', 'path', 'destinationPath', 'newName'],
    outputProps: { sequencePath: P.sequencePath },
    outputRequired: ['sequencePath'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'duplicate', path: '/Game/Cinematics/SEQ_Master', destinationPath: '/Game/Cinematics/Copies', newName: 'SEQ_Copy' },
    exampleOutput: { success: true, sequencePath: '/Game/Cinematics/Copies/SEQ_Copy' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
  buildRecord({
    id: 'sequence.rename',
    action: 'rename',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Rename a Level Sequence asset in place.',
    whenToUse: ['A sequence asset needs a new name.'],
    whenNotToUse: ['The sequence should be duplicated to preserve the original.'],
    inputProps: { action: P.action, path: P.path, newName: P.newName },
    required: ['action', 'path', 'newName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    latency: 'interactive',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'rename', path: '/Game/Cinematics/SEQ_Master', newName: 'SEQ_Renamed' },
    exampleOutput: { success: true, message: 'Sequence renamed' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
  buildRecord({
    id: 'sequence.delete',
    action: 'delete',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Permanently delete a Level Sequence asset.',
    whenToUse: ['A sequence asset must be permanently removed.'],
    whenNotToUse: ['The sequence should only be unloaded or hidden.'],
    inputProps: { action: P.action, path: P.path },
    required: ['action', 'path'],
    effect: 'destructive',
    behavior: { safeToRetry: false, supportsUndo: false },
    latency: 'interactive',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'delete', path: '/Game/Cinematics/SEQ_Disposable' },
    exampleOutput: { success: true, message: 'Sequence deleted' },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
  buildRecord({
    id: 'sequence.list',
    action: 'list',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'List Level Sequence assets under a content path.',
    whenToUse: ['Available sequences under a folder must be enumerated.'],
    whenNotToUse: ['A specific known sequence path is already available.'],
    inputProps: { action: P.action, path: P.path },
    required: ['action'],
    outputProps: { sequences: { type: 'array', items: P.sequencePath, description: 'Discovered sequence paths.' } },
    outputRequired: ['sequences'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: SEQ_PLUGINS,
    exampleInput: { action: 'list', path: '/Game/Cinematics' },
    exampleOutput: { success: true, sequences: ['/Game/Cinematics/SEQ_Master'] },
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: NR,
  }),
];
