/**
 * Grounded in src/tools/definitions/core/blueprint/manage-blueprint-core-properties.ts
 * and src/tools/handlers/blueprint/ blueprint-core-actions.ts.
 *
 * create_blueprint is the canonical Widget Blueprint creation action; the
 * native route create_widget (reachable via system_control) maps to it as an
 * alias (route disposition: map).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { BP_PLUGINS, buildRecord } from './helpers.js';
import { P } from './properties.js';

const FAMILY = 'lifecycle';
const DOMAIN = 'blueprint';

export const BLUEPRINT_LIFECYCLE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'blueprint.create',
    action: 'create',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['new blueprint', 'blueprint class', 'actor blueprint', 'make blueprint', 'blueprint asset', 'subclass', 'derive from'],
    aliases: ['blueprint.make_blueprint', 'blueprint.new_blueprint'],
    summary: 'Create a new Blueprint asset from a parent class.',
    whenToUse: ['A new Blueprint of a known parent class is needed.'],
    whenNotToUse: ['An existing Blueprint should be opened or modified instead.'],
    // blueprint-core-actions.ts:87 forwards `properties` into blueprint_create and
    // native ApplyBlueprintProperties writes each entry onto the generated CDO, so
    // the field is consumed here even though no manage_blueprint record declared it.
    inputProps: { action: P.action, name: P.name, savePath: P.savePath, parentClass: P.parentClass, properties: P.properties },
    required: ['action', 'name', 'savePath', 'parentClass'],
    outputProps: { blueprintPath: P.blueprintPath },
    outputRequired: ['blueprintPath'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create', name: 'BP_TestActor', savePath: '/Game/Blueprints', parentClass: '/Script/Engine.Actor' },
    exampleOutput: { success: true, blueprintPath: '/Game/Blueprints/BP_TestActor' },
  }),
  buildRecord({
    id: 'blueprint.create_blueprint',
    action: 'create_blueprint',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a Blueprint asset with explicit type and path.',
    whenToUse: ['A Blueprint must be created with a specific type hint.'],
    whenNotToUse: ['The simpler create action suffices when only a parent class is needed.'],
    inputProps: { action: P.action, name: P.name, savePath: P.savePath, parentClass: P.parentClass, blueprintType: P.blueprintType },
    required: ['action', 'name', 'savePath', 'parentClass'],
    outputProps: { blueprintPath: P.blueprintPath },
    outputRequired: ['blueprintPath'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_blueprint', name: 'BP_Typed', savePath: '/Game/Blueprints', parentClass: '/Script/Engine.Pawn', blueprintType: 'Character' },
    exampleOutput: { success: true, blueprintPath: '/Game/Blueprints/BP_Typed' },
  }),
  buildRecord({
    id: 'blueprint.get_blueprint',
    action: 'get_blueprint',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['blueprint info', 'blueprint metadata', 'list variables', 'list functions', 'inspect blueprint', 'blueprint details', 'blueprint variables', 'blueprint functions', 'blueprint components'],
    aliases: ['blueprint.list_variables', 'blueprint.list_blueprint_variables'],
    summary: 'Retrieve metadata for one Blueprint asset.',
    whenToUse: ['Blueprint parent class, components, or variables must be inspected.'],
    whenNotToUse: ['The full graph or node details are needed (use get_graph_details).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath },
    required: ['action', 'blueprintPath'],
    outputProps: {
      parentClass: P.parentClass,
      name: { type: 'string', description: 'Blueprint asset name.' },
      assetPath: { type: 'string', description: 'Resolved object path of the Blueprint.' },
      blueprintType: { type: 'string', description: 'Blueprint type (Normal, Interface, MacroLibrary, FunctionLibrary, ...).' },
      compileStatus: { type: 'string', description: 'Last compile status.' },
      hasCompileErrors: { type: 'boolean', description: 'Whether the last compile reported errors.' },
      variables: { type: 'array', description: 'Blueprint variables (NewVariables).', items: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Variable entry: name, type, category, replication, default value.' } },
      functions: { type: 'array', description: 'User function graphs with parameters.', items: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Function entry: name, parameters, nodeCount.' } },
      events: { type: 'array', description: 'Event graph entry points.', items: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Event entry: name, eventType.' } },
      functionGraphs: { type: 'array', description: 'Names of function graphs.', items: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Graph entry.' } },
      eventGraphs: { type: 'array', description: 'Names of event graphs.', items: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Graph entry.' } },
      defaults: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Class default values keyed by property name (text).' },
      metadata: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Blueprint metadata recorded by the bridge.' },
      details: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Additional snapshot fields not named by the contract.' },
    },
    outputRequired: ['parentClass'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_blueprint', blueprintPath: '/Game/Blueprints/BP_TestActor' },
    exampleOutput: { success: true, parentClass: '/Script/Engine.Actor', name: 'BP_TestActor', variables: [], functions: [] },
  }),
  buildRecord({
    id: 'blueprint.get',
    action: 'get',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read a property value from a Blueprint asset or its CDO.',
    whenToUse: ['A single property must be read from the Blueprint CDO.'],
    whenNotToUse: ['The entire Blueprint metadata is needed (use get_blueprint).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, propertyName: P.propertyName },
    required: ['action', 'blueprintPath', 'propertyName'],
    outputProps: { propertyValue: P.propertyValue },
    outputRequired: ['propertyValue'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get', blueprintPath: '/Game/Blueprints/BP_TestActor', propertyName: 'Health' },
    exampleOutput: { success: true, propertyValue: 100 },
  }),
  buildRecord({
    id: 'blueprint.ensure_exists',
    action: 'ensure_exists',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['get or create blueprint', 'idempotent create', 'create if missing'],
    summary: 'Ensure a Blueprint asset exists, creating it if absent.',
    whenToUse: ['Idempotent setup requires a Blueprint to exist without failing on duplicates.'],
    whenNotToUse: ['A fresh Blueprint is always required even if one exists.'],
    inputProps: { action: P.action, name: P.name, savePath: P.savePath, parentClass: P.parentClass },
    required: ['action', 'name', 'savePath', 'parentClass'],
    outputProps: { blueprintPath: P.blueprintPath },
    outputRequired: ['blueprintPath'],
    effect: 'write',
    behavior: { idempotency: 'idempotent', safeToRetry: true },
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'ensure_exists', name: 'BP_Standard', savePath: '/Game/Blueprints', parentClass: '/Script/Engine.Actor' },
    exampleOutput: { success: true, blueprintPath: '/Game/Blueprints/BP_Standard' },
  }),
  buildRecord({
    id: 'blueprint.compile',
    action: 'compile',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['build blueprint', 'recompile', 'compile errors', 'compile blueprint'],
    summary: 'Compile a Blueprint asset, optionally saving after compile.',
    whenToUse: ['Blueprint changes must be compiled to take effect.'],
    whenNotToUse: ['The Blueprint has no pending changes.'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, saveAfterCompile: P.saveAfterCompile },
    required: ['action', 'blueprintPath'],
    effect: 'write',
    behavior: { longRunning: true, supportsUndo: true },
    latency: 'long-running',
    resources: 'high',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'compile', blueprintPath: '/Game/Blueprints/BP_TestActor', saveAfterCompile: true },
    exampleOutput: { success: true, message: 'Blueprint compiled and saved' },
  }),
];
