/**
 * Pin handles: `fromNodeId`+`fromPinName` and `toNodeId`+`toPinName` are the
 * correlation keys for connect_pins and break_pin_links. connect_pins uses
 * AllocateDefaultPins as a fallback when pins are not yet materialized.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { BP_PLUGINS, buildRecord } from './helpers.js';
import { P } from './properties.js';

const FAMILY = 'graph';
const DOMAIN = 'blueprint';

export const GRAPH_PINS_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'blueprint.connect_pins',
    action: 'connect_pins',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Connect two graph pins (exec or data) by nodeGuid and pin name.',
    whenToUse: ['An exec or data link between two existing nodes must be created.'],
    whenNotToUse: ['Links must be broken (use break_pin_links).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, fromNodeId: P.fromNodeId, fromPinName: P.fromPinName, toNodeId: P.toNodeId, toPinName: P.toPinName, sourceNode: P.sourceNode, targetNode: P.targetNode, sourcePin: P.sourcePin, targetPin: P.targetPin, linkedTo: P.linkedTo },
    required: ['action', 'blueprintPath', 'fromNodeId', 'fromPinName', 'toNodeId', 'toPinName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'connect_pins', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', fromNodeId: 'A1B2C3D4', fromPinName: 'OutExec', toNodeId: 'E5F6G7H8', toPinName: 'InExec' },
    exampleOutput: { success: true, message: 'Pins connected' },
  }),
  buildRecord({
    id: 'blueprint.break_pin_links',
    action: 'break_pin_links',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Break all links from one pin on a graph node.',
    whenToUse: ['All links from a specific pin must be removed.'],
    whenNotToUse: ['A single link should be redirected (use connect_pins after breaking).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, pinName: P.pinName, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId', 'pinName'],
    effect: 'destructive',
    behavior: { supportsUndo: false },
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'break_pin_links', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4', pinName: 'OutExec' },
    exampleOutput: { success: true, message: 'Pin links broken' },
  }),
  buildRecord({
    id: 'blueprint.set_node_property',
    action: 'set_node_property',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Set a property on a graph node by nodeGuid.',
    whenToUse: ['A node-level property (e.g. comment, position) must be updated.'],
    whenNotToUse: ['A pin default value is the target (use set_pin_default_value).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, propertyName: P.propertyName, propertyValue: P.propertyValue, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId', 'propertyName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent', safeToRetry: true },
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'set_node_property', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4', propertyName: 'NodeComment', propertyValue: 'Entry point' },
    exampleOutput: { success: true, message: 'Node property set' },
  }),
  buildRecord({
    id: 'blueprint.set_pin_default_value',
    action: 'set_pin_default_value',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Set the default value of a data pin on a graph node.',
    whenToUse: ['A pin\'s default literal value must be set when it has no incoming link.'],
    whenNotToUse: ['The pin should receive its value from a linked node (use connect_pins).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, pinName: P.pinName, propertyValue: P.propertyValue, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId', 'pinName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent', safeToRetry: true },
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'set_pin_default_value', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4', pinName: 'InString', propertyValue: 'Hello' },
    exampleOutput: { success: true, message: 'Pin default value set' },
  }),
  buildRecord({
    id: 'blueprint.add_construction_script',
    action: 'add_construction_script',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Add or open the Construction Script graph for a Blueprint.',
    whenToUse: ['The Construction Script graph must be created or opened for editing.'],
    whenNotToUse: ['An event graph is needed (use create_node in EventGraph).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath },
    required: ['action', 'blueprintPath'],
    outputProps: { graphName: P.graphName },
    outputRequired: ['graphName'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'add_construction_script', blueprintPath: '/Game/Blueprints/BP_Test' },
    exampleOutput: { success: true, graphName: 'ConstructionScript' },
  }),
];
