/**
 * Graph handles: create_node returns `nodeGuid` (string) which is the
 * correlation key for subsequent get_node_details, connect_pins, and
 * get_pin_details calls. Pin handles are `pinName` (string) on a given node.
 * create_struct_make_break_nodes also returns `nodeGuid` and compiles the
 * Blueprint, surfacing pin/diagnostic detail for the created Make/Break node.
 */
import type { CapabilityRecordSource } from '../../index.js';
import { BP_PLUGINS, buildRecord } from './helpers.js';
import { P } from './properties.js';

const FAMILY = 'graph';
const DOMAIN = 'blueprint';

export const GRAPH_NODES_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'blueprint.create_node',
    action: 'create_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a graph node (function call, event, variable, branch, etc.) in a Blueprint graph.',
    whenToUse: ['A new node must be placed in a Blueprint event or function graph.'],
    whenNotToUse: ['A reroute node for wire organization is needed (use create_reroute_node).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeType: P.nodeType, memberName: P.memberName, posX: P.posX, posY: P.posY, functionName: P.functionName, eventName: P.eventName, customEventName: P.customEventName, memberClass: P.memberClass, targetClass: P.targetClass, inputAxisName: P.inputAxisName, inputActionPath: P.inputActionPath, inputActionAssetPath: P.inputActionAssetPath, actionPath: P.actionPath },
    required: ['action', 'blueprintPath', 'nodeType', 'posX', 'posY'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      graphName: P.graphName,
      nodeClass: { type: 'string', description: 'Resolved UK2Node class name.' },
      nodeName: P.nodeName,
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeType: 'CallFunction', memberName: 'PrintString', posX: 100, posY: 200 },
    exampleOutput: { success: true, nodeGuid: 'A1B2C3D4', graphName: 'EventGraph', nodeClass: 'UK2Node_CallFunction', nodeName: 'Print String' },
  }),
  buildRecord({
    id: 'blueprint.add_node',
    action: 'add_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Add a node to a Blueprint graph (alias of create_node with simplified type resolution).',
    whenToUse: ['A node must be added using a friendly type alias (e.g. Branch, Cast, GetVariable).'],
    whenNotToUse: ['Full member-class control is needed (use create_node).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeType: P.nodeType, posX: P.posX, posY: P.posY, memberName: P.memberName, functionName: P.functionName, eventName: P.eventName, nodeName: P.nodeName },
    required: ['action', 'blueprintPath', 'nodeType'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      graphName: P.graphName,
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'add_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeType: 'Branch', posX: 50, posY: 50 },
    exampleOutput: { success: true, nodeGuid: 'E5F6G7H8', graphName: 'EventGraph' },
  }),
  buildRecord({
    id: 'blueprint.delete_node',
    action: 'delete_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Delete a node from a Blueprint graph by its nodeGuid.',
    whenToUse: ['A graph node must be permanently removed.'],
    whenNotToUse: ['The node should be moved rather than deleted.'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId'],
    effect: 'destructive',
    behavior: { safeToRetry: false, supportsUndo: false },
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'delete_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
    exampleOutput: { success: true, message: 'Node deleted' },
  }),
  buildRecord({
    id: 'blueprint.create_reroute_node',
    action: 'create_reroute_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a reroute node for organizing exec/data wire paths in a Blueprint graph.',
    whenToUse: ['Wire paths need a reroute node for cleaner layout.'],
    whenNotToUse: ['A functional node is needed (use create_node).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, posX: P.posX, posY: P.posY },
    required: ['action', 'blueprintPath', 'posX', 'posY'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Reroute node identifier.' },
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_reroute_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', posX: 300, posY: 300 },
    exampleOutput: { success: true, nodeGuid: 'R9S0T1U2' },
  }),
  buildRecord({
    id: 'blueprint.get_node_details',
    action: 'get_node_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read details for one graph node, including its pins and linked connections.',
    whenToUse: ['A single node\'s pins, type, and links must be inspected.'],
    whenNotToUse: ['All nodes in a graph are needed (use get_graph_details).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId'],
    outputProps: {
      nodeId: P.nodeId,
      nodeName: P.nodeName,
      nodeTitle: { type: 'string', description: 'Display title of the node.' },
      comment: { type: 'string', description: 'Node comment if present.' },
      pins: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Pin descriptors (name, direction, type, links).', 'x-unreal-reflection-boundary': true },
    },
    outputRequired: ['nodeId'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_node_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
    exampleOutput: { success: true, nodeId: 'A1B2C3D4', nodeName: 'Print String', nodeTitle: 'Print String', pins: [] },
  }),
  buildRecord({
    id: 'blueprint.get_graph_details',
    action: 'get_graph_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read all nodes in a Blueprint graph, optionally including per-node pins and links.',
    whenToUse: ['The full node list of a graph must be inspected in one call.'],
    whenNotToUse: ['A single node\'s details are needed (use get_node_details).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, includePins: P.includePins },
    required: ['action', 'blueprintPath'],
    outputProps: {
      nodes: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Node descriptors (nodeId, nodeName, nodeTitle; pins if includePins=true).', 'x-unreal-reflection-boundary': true },
    },
    outputRequired: ['nodes'],
    effect: 'read',
    latency: 'interactive',
    resources: 'medium',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_graph_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', includePins: true },
    exampleOutput: { success: true, nodes: [{ nodeId: 'A1B2C3D4', nodeName: 'Print String' }] },
  }),
  buildRecord({
    id: 'blueprint.get_pin_details',
    action: 'get_pin_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read pin details (direction, type, links, defaults) for one node in a Blueprint graph.',
    whenToUse: ['Pin-level details including linkedTo connections must be inspected for a single node.'],
    whenNotToUse: ['All nodes with pins are needed (use get_graph_details with includePins).'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid },
    required: ['action', 'blueprintPath', 'nodeId'],
    outputProps: {
      nodeId: P.nodeId,
      pins: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Pin descriptors (pinName, direction, pinType, pinSubType, linkedTo[], defaults).', 'x-unreal-reflection-boundary': true },
    },
    outputRequired: ['pins'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_pin_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
    exampleOutput: { success: true, nodeId: 'A1B2C3D4', pins: [{ pinName: 'InExec', direction: 'EGPD_Input', pinType: 'exec' }] },
  }),
  buildRecord({
    id: 'blueprint.list_node_types',
    action: 'list_node_types',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'List available Blueprint node types that can be created via create_node or add_node.',
    whenToUse: ['The set of creatable node types must be enumerated before node creation.'],
    whenNotToUse: ['A specific node type is already known.'],
    inputProps: { action: P.action, blueprintPath: P.blueprintPath },
    required: ['action'],
    outputProps: {
      nodeTypes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            className: { type: 'string', description: 'Blueprint node class name (e.g. UK2Node_CallFunction).' },
            displayName: { type: 'string', description: 'Localized node display name shown in the Blueprint palette.' },
          },
          required: ['className', 'displayName'],
        },
        description: 'Available Blueprint node types, each an object with className and displayName.',
      },
      count: { type: 'number', description: 'Total number of node types listed.' },
    },
    outputRequired: ['nodeTypes', 'count'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'list_node_types', blueprintPath: '/Game/Blueprints/BP_Test' },
    exampleOutput: { success: true, nodeTypes: [{ className: 'UK2Node_CallFunction', displayName: 'Call Function' }], count: 1 },
  }),
  buildRecord({
    id: 'blueprint.create_struct_make_break_nodes',
    action: 'create_struct_make_break_nodes',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a Make or Break Struct node in a Blueprint graph from a UserDefinedStruct or native UScriptStruct.',
    whenToUse: ['A MakeStruct or BreakStruct node must be placed for a known struct type.'],
    whenNotToUse: ['A general CallFunction or event node is needed (use create_node).'],
    inputProps: {
      action: P.action,
      blueprintPath: P.blueprintPath,
      structPath: P.structPath,
      nodeType: { type: 'string', enum: ['make', 'break'], description: 'Struct node kind: make (UK2Node_MakeStruct) or break (UK2Node_BreakStruct).' },
      graphName: P.graphName,
      posX: P.posX,
      posY: P.posY,
    },
    required: ['action', 'blueprintPath', 'structPath', 'nodeType'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      nodeType: { type: 'string', enum: ['make', 'break'], description: 'Echoed struct node kind.' },
      structPath: { type: 'string', description: 'Resolved struct object path.' },
      pinNames: { type: 'array', items: { type: 'string' }, description: 'Pin display names (legacy).' },
      pinTypes: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Per-pin objects: { name, direction, type, category, subCategory }.', 'x-unreal-reflection-boundary': true },
      diagnostics: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Compile messages: { severity, message }.', 'x-unreal-reflection-boundary': true },
      compilerStatus: { type: 'string', description: 'Blueprint status after compile (UpToDate, UpToDateWithWarnings, Error, Dirty, BeingCreated).' },
      compiled: { type: 'boolean', description: 'True when the Blueprint is up-to-date (warnings allowed).' },
      assetPath: { type: 'string', description: 'Asset path of the created node (verification).' },
      assetName: { type: 'string', description: 'Name of the created node (verification).' },
      existsAfter: { type: 'boolean', description: 'Whether the node exists after creation (verification).' },
      assetClass: { type: 'string', description: 'Class of the created node (verification).' },
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    behavior: { longRunning: false, supportsUndo: true },
    latency: 'interactive',
    resources: 'medium',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_struct_make_break_nodes', blueprintPath: '/Game/Blueprints/BP_Test', structPath: '/Game/Blueprints/Structs/FMyStruct', nodeType: 'make', graphName: 'EventGraph', posX: 100, posY: 200 },
    exampleOutput: { success: true, nodeGuid: 'A1B2C3D4', nodeType: 'make', structPath: '/Game/Blueprints/Structs/FMyStruct', pinNames: ['A', 'B'], pinTypes: [{ name: 'A', direction: 'input', type: 'Float', category: 'float', subCategory: '' }], diagnostics: [], compilerStatus: 'UpToDate', compiled: true, assetPath: '/Game/Blueprints/BP_Test', assetName: 'Make MyStruct', existsAfter: true, assetClass: 'UK2Node_MakeStruct' },
  }),
];
