/**
 * Shared JSON-Schema property fragments for world-domain records.
 *
 * Each property is a Draft-2020-12 schema fragment. Records reference these via
 * the P map so input schemas declare only the params the implementation body
 * actually consumes - never the full parent-tool union.
 */
import type { JsonObject } from '../../index.js';
import { str, num, bool } from '../shared/schema-props.js';

const int = (d: string): JsonObject => ({ type: 'integer', description: d });
const arr = (d: string, item: JsonObject): JsonObject => ({ type: 'array', items: item, description: d });
const vec3 = (d: string): JsonObject => ({
  type: 'object', description: d,
  properties: { x: num('X'), y: num('Y'), z: num('Z') },
  additionalProperties: false,
});
const rot = (d: string): JsonObject => ({
  type: 'object', description: d,
  properties: { pitch: num('Pitch'), yaw: num('Yaw'), roll: num('Roll') },
  additionalProperties: false,
});

export const P = {
  levelName: str('Level asset name.'),
  levelPath: str('Canonical /Game level asset path.'),
  parentLevel: str('Parent level asset path.'),
  sublevelName: str('Sub-level asset name.'),
  sublevelPath: str('Sub-level asset path.'),
  bCreateWorldPartition: bool('Create with World Partition enabled.'),
  bUseExternalActors: bool('Enable One File Per Actor (OFPA) for Data Layer compatibility.'),
  streamingMethod: str('Level streaming method: Blueprint, AlwaysLoaded, or Disabled.'),
  bShouldBeVisible: bool('Level should be visible when loaded.'),
  bShouldBlockOnLoad: bool('Block game until level is loaded.'),
  bDisableDistanceStreaming: bool('Disable distance-based streaming.'),
  streamingDistance: num('Distance/radius for streaming volume.'),
  streamingUsage: str('Streaming volume usage mode.'),
  createVolume: bool('Create a streaming volume (true) or report existing volumes (false).'),
  boundsOrigin: vec3('Origin of level bounds.'),
  boundsExtent: vec3('Extent of level bounds.'),
  bAutoCalculateBounds: bool('Auto-calculate bounds from content.'),
  bEnableWorldPartition: bool('Enable World Partition for level.'),
  gridCellSize: num('World Partition grid cell size.'),
  loadingRange: num('Loading range for grid cells.'),
  gridName: str('World Partition runtime hash set grid name.'),
  gridPriority: num('World Partition grid priority (higher wins when grids overlap).'),
  dataLayerName: str('Data layer name.'),
  bIsInitiallyVisible: bool('Data layer initially visible.'),
  bIsInitiallyLoaded: bool('Data layer initially loaded.'),
  dataLayerType: str('Type of data layer: Runtime or Editor.'),
  actorName: str('Actor name in the level.'),
  actorPath: str('Actor path in the level.'),
  hlodLayerName: str('HLOD layer name.'),
  hlodLayerPath: str('Canonical /Game HLOD layer asset path.'),
  bIsSpatiallyLoaded: bool('HLOD is spatially loaded.'),
  cellSize: num('HLOD cell size.'),
  loadingDistance: num('HLOD loading distance.'),
  volumeName: str('Volume actor name.'),
  volumeLocation: vec3('Location of the volume.'),
  volumeExtent: vec3('Extent of the volume.'),
  location: vec3('World location {x, y, z}.'),
  rotation: rot('Rotation {pitch, yaw, roll}.'),
  extent: vec3('Extent (half-size) of the volume in each axis.'),
  sphereRadius: num('Radius for sphere trigger volumes.'),
  capsuleRadius: num('Radius for capsule trigger volumes.'),
  capsuleHalfHeight: num('Half-height for capsule trigger volumes.'),
  boxExtent: vec3('Extent for box trigger volumes.'),
  bPainCausing: bool('Whether the volume causes pain/damage.'),
  damagePerSec: num('Damage per second for pain volumes.'),
  bWaterVolume: bool('Whether this is a water volume.'),
  fluidFriction: num('Fluid friction for physics volumes.'),
  terminalVelocity: num('Terminal velocity in the volume.'),
  priority: num('Priority for audio volume.'),
  bEnabled: bool('Whether the audio volume is enabled.'),
  reverbVolume: num('Volume level for reverb (0.0-1.0).'),
  fadeTime: num('Fade time for audio volume.'),
  cullDistances: arr('Size/distance pairs for cull distance volumes.', {
    type: 'object',
    properties: { size: num('Object size threshold.'), cullDistance: num('Distance at which to cull.') },
    additionalProperties: false,
  }),
  bUnbound: bool('Whether post process volume affects entire world.'),
  blendRadius: num('Blend radius for post process volume.'),
  blendWeight: num('Blend weight (0.0-1.0) for post process.'),
  filter: str('Type filter for get_volumes_info (e.g. "Trigger", "Physics").'),
  volumeType: str('Volume type for get_volumes_info.'),
  bBlockOnSlowStreaming: bool('Block on slow streaming.'),
  bounds: {
    type: 'object', description: 'Bounds {origin, extent}.',
    properties: { origin: vec3('Origin.'), extent: vec3('Extent.') },
    additionalProperties: false,
  } as JsonObject,
  boundsArray: {
    type: 'array',
    description: 'Volume bounds as a six-number array [minX, minY, minZ, maxX, maxY, maxZ].',
    items: { type: 'number' },
    minItems: 6,
    maxItems: 6,
  } as JsonObject,
  createIfMissing: bool('Create the grid if missing.'),
  layerType: str('Layer type for runtime hash set grid.'),
  nodeClass: str('Level blueprint graph node class.'),
  nodePosition: { type: 'object', description: 'Node graph position {x, y}.', properties: { x: num('X'), y: num('Y') }, additionalProperties: false } as JsonObject,
  nodeName: str('Level blueprint node name.'),
  sourceNodeName: str('Source node name for connection.'),
  sourcePinName: str('Source pin name.'),
  targetNodeName: str('Target node name for connection.'),
  targetPinName: str('Target pin name.'),
  levelInstanceName: str('Level instance actor name.'),
  levelAssetPath: str('Canonical /Game level asset path for instancing.'),
  instanceLocation: vec3('Location of the level instance.'),
  instanceRotation: rot('Rotation of the level instance.'),
  instanceScale: vec3('Scale of the level instance.'),
  packedLevelName: str('Name for the packed level actor.'),
  bPackBlueprints: bool('Include blueprints in packed level.'),
  bPackStaticMeshes: bool('Include static meshes in packed level.'),
  save: bool('Whether to save the level after the operation.'),
  // geometry
  dimensions: vec3('Primitive dimensions {x, y, z}.'),
  radius: num('Primitive radius.'),
  height: num('Primitive height.'),
  width: num('Primitive width along X.'),
  depth: num('Primitive depth along Z.'),
  scale: vec3('Spawn scale {x, y, z}.'),
  thickness: num('Shell wall thickness (scalar).'),
  innerRadius: num('Inner radius (torus minor radius, ring/pipe inner wall).'),
  outerRadius: num('Outer radius for ring and pipe primitives.'),
  widthSegments: int('Tessellation segments along width.'),
  heightSegments: int('Tessellation segments along height.'),
  depthSegments: int('Tessellation segments along depth.'),
  radialSegments: int('Radial tessellation segments for circular primitives.'),
  numSides: int('Number of sides for cylinder, cone, disc, ring, torus.'),
  numRings: int('Number of rings for sphere, capsule, torus, arch.'),
  numSteps: int('Number of steps for stair primitives.'),
  numTurns: num('Number of turns for spiral stairs (converted to a curve angle).'),
  stepWidth: num('Width of each stair step.'),
  stepHeight: num('Height of each stair step.'),
  stepDepth: num('Depth of each stair step.'),
  segments: int('Number of segments for the operation.'),
  amount: num('Generic amount (bevel size, inset/extrude distance).'),
  distance: num('Distance for offset-style operations.'),
  angle: num('Angle in degrees.'),
  position: vec3('Position {x, y, z} for the operation.'),
  uvRotation: num('UV rotation in degrees (transform_uvs takes a scalar, not a rotator).'),
  outputPath: str('Canonical /Game output asset path.'),
  lodCount: int('Number of LOD levels to generate.'),
  lodIndex: int('Specific LOD index to configure.'),
  hullCount: int('Number of convex hulls for decomposition.'),
  maxHullCount: int('Maximum hull count for complex collision generation.'),
  maxHullVerts: int('Maximum vertices per hull for complex collision generation.'),
  maxVerticesPerHull: int('Maximum vertices per convex hull.'),
  hullPrecision: num('Precision for convex hull generation.'),
  targetHullCount: int('Target hull count for collision simplification.'),
  simplificationFactor: num('Collision simplification factor.'),
  reductionPercent: num('Percent of triangles to reduce.'),
  trianglePercent: num('Percent of triangles to keep for LOD reduction.'),
  recomputeNormals: bool('Recompute normals for the LOD.'),
  recomputeTangents: bool('Recompute tangents for the LOD.'),
  screenSizes: arr('Screen size for each LOD.', num('Screen size.')),
  steps: int('Number of steps.'),
  count: int('Count of repeated elements.'),
  iterations: int('Number of iterations for smooth/remesh.'),
  targetTriangleCount: num('Target triangle count for simplification.'),
  targetEdgeLength: num('Target edge length for remeshing.'),
  weldDistance: num('Distance threshold for vertex welding.'),
  uvChannel: int('UV channel index (0-7).'),
  uvScale: { type: 'object', description: 'UV scale {u, v}.', properties: { u: num('U'), v: num('V') }, additionalProperties: false } as JsonObject,
  uvOffset: { type: 'object', description: 'UV offset {u, v}.', properties: { u: num('U'), v: num('V') }, additionalProperties: false } as JsonObject,
  hardEdgeAngle: num('Angle threshold for hard edges (degrees).'),
  computeWeightedNormals: bool('Use area-weighted normals.'),
  collisionType: str('Collision complexity type.'),
  strength: num('Deformation strength.'),
  weight: num('Weight for lattice deformation.'),
  latticeResolution: int('Control lattice resolution for lattice deformation.'),
  heightScale: num('Texture displacement height scale.'),
  midpoint: num('Texture luminance midpoint for displacement.'),
  texturePath: str('Canonical /Game texture asset path.'),
  targetActor: str('Target actor name for boolean operations.'),
  triangleIndices: arr('Triangle ids the operation is limited to; omit to apply it to the whole mesh.', { type: 'integer' }),
  toolActor: str('Tool actor name for boolean operations.'),
  trimActorName: str('Trim actor name for boolean trim.'),
  splineActorName: str('Spline actor name for extrude/sweep along spline.'),
  keepTool: bool('Keep the tool actor after the operation.'),
  keepInside: bool('Keep geometry inside the tool.'),
  cap: bool('Cap open ends of tubes.'),
  axis: str('Deformation axis: X, Y, or Z.'),
  center: vec3('Center of operation.'),
  offset: vec3('Offset vector.'),
  // geometry: DynamicMesh authoring. Names match the native payload fields
  // exactly; a rename here silently stops the handler from reading the value.
  enableCollision: bool('Enable simple collision on the created DynamicMesh actor.'),
  vertexIndex: int('Index of the vertex the operation targets.'),
  triangleIndex: int('Index of the triangle the operation targets.'),
  groupID: int('Polygroup id assigned to the appended triangle.'),
  v0: vec3('First corner {x, y, z} of the appended triangle.'),
  v1: vec3('Second corner {x, y, z} of the appended triangle.'),
  v2: vec3('Third corner {x, y, z} of the appended triangle.'),
  translation: vec3('Translation {x, y, z} applied to every mesh vertex.'),
  r: num('Red channel, 0-1.'),
  g: num('Green channel, 0-1.'),
  b: num('Blue channel, 0-1.'),
  a: num('Alpha channel, 0-1.'),
  setAll: bool('Apply the colour to every vertex instead of one.'),
  u: num('U coordinate.'),
  v: num('V coordinate.'),
  splitAngle: num('Angle threshold in degrees above which normals are split.'),
  // pcg
  graphPath: str('PCG graph asset path (e.g. /Game/PCG/PCG_MyGraph).'),
  parentGraphPath: str('Parent PCG graph asset path for subgraph insertion.'),
  subgraphPath: str('PCG subgraph asset path used by subgraph nodes.'),
  assetPath: str('Canonical /Game asset path.'),
  path: str('Canonical /Game directory path.'),
  name: str('Name for the new asset or node.'),
  nodeType: str('PCG node type alias or UPCGSettings class path/name.'),
  settingsClass: str('UPCGSettings class path/name for the PCG node.'),
  nodeId: str('PCG node identifier.'),
  sourceNodeId: str('Source node identifier for pin connection.'),
  targetNodeId: str('Target node identifier for pin connection.'),
  sourcePin: str('Source pin name.'),
  targetPin: str('Target pin name.'),
  inputName: str('PCG input pin name.'),
  outputName: str('PCG output pin name.'),
  componentName: str('Component name for PCG execution.'),
  componentPath: str('Component path/name for PCG execution.'),
  createComponent: bool('Create a new PCG component when no selector is supplied.'),
  force: bool('Force regeneration even if a result already exists.'),
  pcgScope: str("Partition grid target scope: 'world' or 'component'."),
  pcgGridSize: num('PCG partition grid cell size.'),
  classPath: str('Class path/name.'),
  actorClass: str('Actor class path/name.'),
  meshPath: str('Canonical /Game static mesh asset path.'),
  overwrite: bool('Overwrite the asset when it already exists.'),
  posX: num('Node graph X position.'),
  posY: num('Node graph Y position.'),
  x: num('Node graph X position (alias of posX).'),
  y: num('Node graph Y position (alias of posY).'),
  title: str('Node title (alias of nodeName).'),
  settings: {
    type: 'object', description: 'UPCGSettings property key-value pairs applied by reflection.',
    additionalProperties: true, 'x-unreal-reflection-boundary': true,
  } as JsonObject,
  // shared
  success: bool('Whether the action succeeded.'),
  message: str('Human-readable result message.'),
};

export type PropertyMap = JsonObject;
